<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/index_saver.hpp' l='41' u='w' c='_ZN5boost11multi_index6detail11index_saverC1ERKT0_m'/>
<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/index_saver.hpp' l='47' u='c' c='_ZN5boost11multi_index6detail11index_saver3addEPT_RTL0__j'/>
<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/index_saver.hpp' l='63' u='c' c='_ZNK5boost11multi_index6detail11index_saver4saveETL0__S3_RTL0_0_j'/>
<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/index_saver.hpp' l='97' u='c' c='_ZNK5boost11multi_index6detail11index_saver4saveETL0__S3_RTL0_0_j'/>
<dec f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/index_saver.hpp' l='126' type='index_matcher::algorithm&lt;Node, Allocator&gt;'/>
