<def f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1418' ll='1441'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1419'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1422'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1445' c='_ZN5boost6spirit7classic18access_node_action6actionC1ERKT_RKT0_'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1448' c='_ZN5boost6spirit7classic18access_node_action6actionC1ERKT_RKT0_'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1456' c='_ZNK5boost6spirit7classic18access_node_action6action5parseERKTL0__'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1455' c='_ZNK5boost6spirit7classic18access_node_action6action5parseERKTL0__'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1474' c='_ZNK5boost6spirit7classic18access_node_action6action9predicateEv'/>
<fun r='_ZN5boost6spirit7classic18access_node_action6actionC1ERKT_RKT0_'/>
<fun r='_ZNK5boost6spirit7classic18access_node_action6action5parseERKTL0__'/>
<fun r='_ZNK5boost6spirit7classic18access_node_action6action9predicateEv'/>
<mbr r='boost::spirit::classic::access_node_action::action::actor' t='ActionT'/>
<fun r='_ZN5boost6spirit7classic18access_node_action6actionC1ERKT_RKT0_'/>
<fun r='_ZNK5boost6spirit7classic18access_node_action6action5parseERKTL0__'/>
<fun r='_ZNK5boost6spirit7classic18access_node_action6action9predicateEv'/>
