<dec f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='168' type='boost::json::kind'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='180' u='w' c='_ZN5boost4json6detail6scalarC1ENS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='188' u='w' c='_ZN5boost4json6detail6scalarC1EbNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='197' u='w' c='_ZN5boost4json6detail6scalarC1ElNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='206' u='w' c='_ZN5boost4json6detail6scalarC1EmNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='215' u='w' c='_ZN5boost4json6detail6scalarC1EdNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='110' u='r' c='_ZNK5boost4json5value9is_scalarEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1154' u='w' c='_ZN5boost4json5valueaSEDn'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1188' u='w' c='_ZN5boost4json5valueaSET_'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1241' u='w' c='_ZN5boost4json5valueaSEx'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1294' u='w' c='_ZN5boost4json5valueaSEy'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1322' u='w' c='_ZN5boost4json5valueaSEd'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1707' u='r' c='_ZNK5boost4json5value4kindEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1924' u='r' c='_ZNK5boost4json5value12is_primitiveEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='1925' u='r' c='_ZNK5boost4json5value12is_primitiveEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3640' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3651' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3662' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3691' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3702' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3712' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3738' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3743' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/value.hpp' l='3748' u='r' c='_ZNK5boost4json5value9to_numberERNS0_5errorE'/>
<offset>64</offset>
<doc f='boost-1.85.0/libs/json/include/boost/json/detail/value.hpp' l='168'>// must come second</doc>
