<dec f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='63' type='boost::json::kind'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='191' u='r' c='_ZNK5boost4json6detail11string_impl4sizeEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='200' u='r' c='_ZNK5boost4json6detail11string_impl8capacityEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='208' u='r' c='_ZN5boost4json6detail11string_impl4sizeEm'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='241' u='r' c='_ZN5boost4json6detail11string_impl7destroyERKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='248' u='r' c='_ZN5boost4json6detail11string_impl7destroyERKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='316' u='r' c='_ZN5boost4json6detail11string_impl4termEm'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='334' u='r' c='_ZN5boost4json6detail11string_impl4dataEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='343' u='r' c='_ZNK5boost4json6detail11string_impl4dataEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='37' u='w' c='_ZN5boost4json6detail11string_implC1Ev'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='51' u='w' c='_ZN5boost4json6detail11string_implC1EmRKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='59' u='w' c='_ZN5boost4json6detail11string_implC1EmRKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='443' u='r' c='_ZN5boost4json6detail11string_impl13shrink_to_fitERKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='448' u='w' c='_ZN5boost4json6detail11string_impl13shrink_to_fitERKNS0_11storage_ptrE'/>
<offset>0</offset>
<doc f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='63'>// must come first</doc>
