<dec f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='75' type='boost::json::kind'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='233' u='w' c='_ZN5boost4json6detail11string_impl11release_keyERm'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='83' u='w' c='_ZN5boost4json6detail11string_implC1ENS1_5key_tENS_4core17basic_string_viewIcEERKNS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/string_impl.ipp' l='104' u='w' c='_ZN5boost4json6detail11string_implC1ENS1_5key_tENS_4core17basic_string_viewIcEES6_RKNS0_11storage_ptrE'/>
<offset>0</offset>
<doc f='boost-1.85.0/libs/json/include/boost/json/detail/string_impl.hpp' l='75'>// must come first</doc>
