<dec f='boost-1.85.0/libs/url/include/boost/url/scheme.hpp' l='80' type='4'/>
<doc f='boost-1.85.0/libs/url/include/boost/url/scheme.hpp' l='70'>/**
     * The Hypertext Transfer Protocol URI Scheme

       URLs of this type indicate a resource which
       is interacted with using the HTTP protocol.

       @par Specification
       @li &lt;a href=&quot;https://datatracker.ietf.org/doc/html/rfc7230&quot;&gt;
            Hypertext Transfer Protocol (HTTP/1.1) (rfc7230)&lt;/a&gt;
    */</doc>
<use f='boost-1.85.0/libs/url/src/scheme.cpp' l='70' u='r' c='_ZN5boost4urls16string_to_schemeENS_4core17basic_string_viewIcEE'/>
<use f='boost-1.85.0/libs/url/src/scheme.cpp' l='100' c='_ZN5boost4urls9to_stringENS0_6schemeE'/>
<use f='boost-1.85.0/libs/url/src/scheme.cpp' l='118' c='_ZN5boost4urls12default_portENS0_6schemeE'/>
