<def f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1346' ll='1369'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1347'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1350'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1373' c='_ZN5boost6spirit7classic19access_match_action6actionC1ERKT_RKT0_'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1376' c='_ZN5boost6spirit7classic19access_match_action6actionC1ERKT_RKT0_'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1384' c='_ZNK5boost6spirit7classic19access_match_action6action5parseERKTL0__'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1383' c='_ZNK5boost6spirit7classic19access_match_action6action5parseERKTL0__'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/tree/common.hpp' l='1401' c='_ZNK5boost6spirit7classic19access_match_action6action9predicateEv'/>
<fun r='_ZN5boost6spirit7classic19access_match_action6actionC1ERKT_RKT0_'/>
<fun r='_ZNK5boost6spirit7classic19access_match_action6action5parseERKTL0__'/>
<fun r='_ZNK5boost6spirit7classic19access_match_action6action9predicateEv'/>
<mbr r='boost::spirit::classic::access_match_action::action::actor' t='ActionT'/>
<fun r='_ZN5boost6spirit7classic19access_match_action6actionC1ERKT_RKT0_'/>
<fun r='_ZNK5boost6spirit7classic19access_match_action6action5parseERKTL0__'/>
<fun r='_ZNK5boost6spirit7classic19access_match_action6action9predicateEv'/>
