<dec f='boost-1.85.0/libs/json/include/boost/json/detail/handler.hpp' l='38' type='boost::json::value_stack'/>
<use f='boost-1.85.0/libs/json/include/boost/json/impl/parser.ipp' l='56' u='m' c='_ZN5boost4json6parser5resetENS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/impl/parser.ipp' l='159' u='m' c='_ZN5boost4json6parser7releaseEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/impl/stream_parser.ipp' l='56' u='m' c='_ZN5boost4json13stream_parser5resetENS0_11storage_ptrE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/impl/stream_parser.ipp' l='176' u='m' c='_ZN5boost4json13stream_parser7releaseEv'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='23' u='w' c='_ZN5boost4json6detail7handlerC1EDpOT_'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='57' u='m' c='_ZN5boost4json6detail7handler13on_object_endEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='75' u='m' c='_ZN5boost4json6detail7handler12on_array_endEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='86' u='m' c='_ZN5boost4json6detail7handler11on_key_partENS_4core17basic_string_viewIcEEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='97' u='m' c='_ZN5boost4json6detail7handler6on_keyENS_4core17basic_string_viewIcEEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='108' u='m' c='_ZN5boost4json6detail7handler14on_string_partENS_4core17basic_string_viewIcEEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='119' u='m' c='_ZN5boost4json6detail7handler9on_stringENS_4core17basic_string_viewIcEEmRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='139' u='m' c='_ZN5boost4json6detail7handler8on_int64ElNS_4core17basic_string_viewIcEERNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='150' u='m' c='_ZN5boost4json6detail7handler9on_uint64EmNS_4core17basic_string_viewIcEERNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='161' u='m' c='_ZN5boost4json6detail7handler9on_doubleEdNS_4core17basic_string_viewIcEERNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='171' u='m' c='_ZN5boost4json6detail7handler7on_boolEbRNS_6system10error_codeE'/>
<use f='boost-1.85.0/libs/json/include/boost/json/detail/impl/handler.ipp' l='179' u='m' c='_ZN5boost4json6detail7handler7on_nullERNS_6system10error_codeE'/>
<offset>0</offset>
