<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/value_compare.hpp' l='34' u='w' c='_ZN5boost11multi_index6detail16value_comparisonC1ERKT0_RKT1_'/>
<use f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/value_compare.hpp' l='42' u='c' c='_ZNK5boost11multi_index6detail16value_comparisonclENS_11call_traitsIT_E10param_typeES6_'/>
<dec f='boost-1.85.0/libs/multi_index/include/boost/multi_index/detail/value_compare.hpp' l='47' type='Compare'/>
