<def f='boost-1.85.0/libs/test/include/boost/test/tools/assertion.hpp' l='174' macro='1'/>
<use f='boost-1.85.0/libs/test/include/boost/test/tools/assertion.hpp' l='85'/>
<use f='boost-1.85.0/libs/test/include/boost/test/tools/assertion.hpp' l='85' c='_ZN5boost10test_tools9assertion15expression_basermEOTL0__'/>
<use f='boost-1.85.0/libs/test/include/boost/test/tools/assertion.hpp' l='85' c='_ZN5boost10test_tools9assertion15expression_basermEOTL0__'/>
<fun r='_ZN5boost10test_tools9assertion2op3MOD4evalERKT_RKT0_'/>
<fun r='_ZN5boost10test_tools9assertion2op3MOD6reportERSoRKTL0__RKT0_'/>
<fun r='_ZN5boost10test_tools9assertion2op3MOD7forwardEv'/>
<fun r='_ZN5boost10test_tools9assertion2op3MOD6revertEv'/>
