<dec f='boost-1.85.0/libs/regex/include/boost/regex/v5/states.hpp' l='265' type='boost::re_detail_500::commit_type'/>
<use f='boost-1.85.0/libs/regex/include/boost/regex/v5/basic_regex_parser.hpp' l='2820' u='w' c='_ZN5boost13re_detail_50018basic_regex_parser15parse_perl_verbEv'/>
<use f='boost-1.85.0/libs/regex/include/boost/regex/v5/basic_regex_parser.hpp' l='2845' u='w' c='_ZN5boost13re_detail_50018basic_regex_parser15parse_perl_verbEv'/>
<use f='boost-1.85.0/libs/regex/include/boost/regex/v5/basic_regex_parser.hpp' l='2870' u='w' c='_ZN5boost13re_detail_50018basic_regex_parser15parse_perl_verbEv'/>
<use f='boost-1.85.0/libs/regex/include/boost/regex/v5/perl_matcher_non_recursive.hpp' l='1122' u='r' c='_ZN5boost13re_detail_50012perl_matcher12match_commitEv'/>
<offset>128</offset>
