<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/non_terminal/parser_id.hpp' l='32' c='_ZN5boost6spirit7classic9parser_idC1Em'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/non_terminal/parser_id.hpp' l='37' u='r' c='_ZNK5boost6spirit7classic9parser_id7to_longEv'/>
<dec f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/non_terminal/parser_id.hpp' l='44' type='std::size_t'/>
<offset>0</offset>
