<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/parser.hpp' l='140' c='_ZNK5boost6spirit7classic6parserixERKTL0__'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/parser.hpp' l='143' c='_ZNK5boost6spirit7classic6parserixERKTL0__'/>
<def f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/composite/actions.hpp' l='85' ll='127'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/composite/actions.hpp' l='85'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/core/composite/actions.hpp' l='89'/>
<fun r='_ZN5boost6spirit7classic6actionC1ERKT_RKT0_'/>
<fun r='_ZNK5boost6spirit7classic6action5parseERKTL0__'/>
<fun r='_ZNK5boost6spirit7classic6action9predicateEv'/>
<mbr r='boost::spirit::classic::action::actor' t='ActionT'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/meta/refactoring.hpp' l='264' c='_ZNK5boost6spirit7classic17attach_action_genixERKNS1_6actionITL0__TL0_0_EE'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/meta/refactoring.hpp' l='265' c='_ZNK5boost6spirit7classic17attach_action_genixERKNS1_6actionITL0__TL0_0_EE'/>
<use f='boost-1.85.0/libs/spirit/include/boost/spirit/home/classic/meta/refactoring.hpp' l='267' c='_ZNK5boost6spirit7classic17attach_action_genixERKNS1_6actionITL0__TL0_0_EE'/>
