<def f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='728' ll='840'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='777' c='_ZN7testing6ActionIFT_DpT0_EEC1ERKNS0_ITL0__EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='803' c='_ZNK7testing6ActionIFT_DpT0_EEcvNS_10OnceActionIS4_EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='869' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='870' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='896' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='897' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='946' c='_ZNK7testing8internal12ReturnActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1150' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1157' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1192' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1199' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1257' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1258' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1364' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1378' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1401'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1456'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1459' c='_ZNK7testing8internal14WithArgsActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1460' c='_ZNK7testing8internal14WithArgsActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1499'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1501' c='_ZNK7testing8internal11DoAllActionIJT_EEcvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1614'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1615'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1617' c='_ZNK7testing8internal11DoAllActionIJT_DpT0_EEcvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1622' c='_ZNK7testing8internal11DoAllActionIJT_DpT0_EEcvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1623' c='_ZNK7testing8internal11DoAllActionIJT_DpT0_EEcvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='1737' c='_ZNK7testing8internal11ThrowActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='2141' c='_ZN7testing8internal10MakeActionEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='2142' c='_ZN7testing8internal10MakeActionEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='2147' c='_ZN7testing8internal10MakeActionESt10shared_ptrIT0_E'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='2148' c='_ZN7testing8internal10MakeActionESt10shared_ptrIT0_E'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='306' c='_ZN7testing8internal10OnCallSpec13WillByDefaultERKNS_6ActionIT_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='324' c='_ZNK7testing8internal10OnCallSpec9GetActionEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='347'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='890' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EED1Ev'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='985' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EE8WillOnceENS_10OnceActionIS5_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='996' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EE8WillOnceENS_6ActionIS5_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1002' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EE8WillOnceENS_6ActionIS5_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1011' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EE14WillRepeatedlyERKNS_6ActionIS5_EE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1059' c='_ZNK7testing8internal16TypedExpectationIFT_DpT0_EE15repeated_actionEv'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1159' c='_ZNK7testing8internal16TypedExpectationIFT_DpT0_EE16GetCurrentActionEPKNS0_14FunctionMockerIS5_EERKNS0_8FunctionIS5_E13ArgumentTupleE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1184' c='_ZNK7testing8internal16TypedExpectationIFT_DpT0_EE16GetCurrentActionEPKNS0_14FunctionMockerIS5_EERKNS0_8FunctionIS5_E13ArgumentTupleE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1196' c='_ZN7testing8internal16TypedExpectationIFT_DpT0_EE21GetActionForArgumentsEPKNS0_14FunctionMockerIS5_EERKNS0_8FunctionIS5_E13ArgumentTupleEPSoSG_'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1229'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1594' c='_ZN7testing8internal14FunctionMockerIFT_DpT0_EE30UntypedFindMatchingExpectationEPKvPS8_PbPSoSB_'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1675' c='_ZNK7testing8internal14FunctionMockerIFT_DpT0_EE13PerformActionEPKvOSt5tupleIJS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='googletest-1.12.1/googlemock/include/gmock/gmock-spec-builders.h' l='1675' c='_ZNK7testing8internal14FunctionMockerIFT_DpT0_EE13PerformActionEPKvOSt5tupleIJS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<doc f='googletest-1.12.1/googlemock/include/gmock/gmock-actions.h' l='722'>// An Action&lt;R(Args...)&gt; is a copyable and IMMUTABLE (except by assignment)
// object that represents an action to be taken when a mock function of type
// R(Args...) is called. The implementation of Action&lt;T&gt; is just a
// std::shared_ptr to const ActionInterface&lt;T&gt;. Don&apos;t inherit from Action! You
// can view an object implementing ActionInterface&lt;F&gt; as a concrete action
// (including its current state), and an Action&lt;F&gt; object as a handle to it.</doc>
<fun r='_ZN7testing6ActionIFT_DpT0_EEC1Ev'/>
<fun r='_ZN7testing6ActionIFT_DpT0_EEC1EOTL0__'/>
<fun r='_ZN7testing6ActionIFT_DpT0_EEC1EPNS_15ActionInterfaceIS4_EE'/>
<fun r='_ZN7testing6ActionIFT_DpT0_EEC1ERKNS0_ITL0__EE'/>
<fun r='_ZNK7testing6ActionIFT_DpT0_EE11IsDoDefaultEv'/>
<fun r='_ZNK7testing6ActionIFT_DpT0_EE7PerformENS_8internal8FunctionIS4_E13ArgumentTupleE'/>
<fun r='_ZNK7testing6ActionIFT_DpT0_EEcvNS_10OnceActionIS4_EEEv'/>
<fun r='_ZN7testing6ActionIFT_DpT0_EE4InitEOTL0__St17integral_constantIbLb1EE'/>
<fun r='_ZN7testing6ActionIFT_DpT0_EE4InitEOTL0__St17integral_constantIbLb0EE'/>
<mbr r='testing::Action::fun_' t='::std::function&lt;F&gt;'/>
