<def f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='891' ll='935'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='895' c='_ZN7testing8internal2REC1ERKS1_'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='910' c='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='913' c='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='917' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='918' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='818' c='_ZN7testing8internal19MatchesRegexMatcherC1EPKNS0_2REEb'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='862'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='870' c='_ZN7testing12MatchesRegexEPKNS_8internal2REE'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='876' c='_ZN7testing12MatchesRegexERKT_'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='882' c='_ZN7testing13ContainsRegexEPKNS_8internal2REE'/>
<use f='googletest-1.12.1/googletest/include/gtest/gtest-matchers.h' l='888' c='_ZN7testing13ContainsRegexERKT_'/>
<use f='googletest-1.12.1/googletest/include/gtest/internal/gtest-death-test-internal.h' l='176' c='_ZN7testing8internal20MakeDeathTestMatcherB5cxx11ENS0_2REE'/>
<size>144</size>
<doc f='googletest-1.12.1/googletest/include/gtest/internal/gtest-port.h' l='889'>// A simple C++ wrapper for &lt;regex.h&gt;.  It uses the POSIX Extended
// Regular Expression syntax.</doc>
<fun r='_ZN7testing8internal2REC1ERKS1_'/>
<fun r='_ZN7testing8internal2REC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN7testing8internal2REC1EPKc'/>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZNK7testing8internal2RE7patternEv'/>
<fun r='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
<mbr r='testing::internal::RE::pattern_' o='0' t='const char *'/>
<mbr r='testing::internal::RE::is_valid_' o='64' t='bool'/>
<mbr r='testing::internal::RE::full_regex_' o='128' t='regex_t'/>
<mbr r='testing::internal::RE::partial_regex_' o='640' t='regex_t'/>
<use f='googletest-1.12.1/googletest/src/gtest-port.cc' l='675' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='googletest-1.12.1/googletest/src/gtest-port.cc' l='684' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<size>144</size>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
