<dec f='fmt-8.1.0/include/fmt/core.h' l='2719' type='1'/>
<use f='fmt-8.1.0/include/fmt/core.h' l='2756' u='r' c='_ZN3fmt2v86detail21parse_float_type_specERKNS0_18basic_format_specsIT0_EEOT_'/>
<use f='fmt-8.1.0/include/fmt/format.h' l='1828' u='r' c='_ZN3fmt2v86detail14do_write_floatET_RKT0_RKNS0_18basic_format_specsIT1_EENS1_11float_specsENS1_10locale_refE'/>
<use f='fmt-8.1.0/include/fmt/format.h' l='2024' u='r' c='_ZN3fmt2v86detail5writeET0_T1_NS0_18basic_format_specsIT_EENS1_10locale_refE'/>
<use f='fmt-8.1.0/include/fmt/format-inl.h' l='2426' u='r' c='_ZN3fmt2v86detail14snprintf_floatET_iNS1_11float_specsERNS1_6bufferIcEE'/>
<doc f='fmt-8.1.0/include/fmt/core.h' l='2719'>// Exponent notation with the default precision of 6, e.g. 1.2e-3.</doc>
