<def f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1354' ll='1443'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1399' c='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1472' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1473' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1499' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1500' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1563' c='_ZNK7testing8internal12ReturnActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1578' c='_ZNK7testing8internal12ReturnActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1673' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1680' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1715' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1723' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1781' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1781' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1887' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1901' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1924'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1937' c='_ZNK7testing8internal14WithArgsActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1939' c='_ZNK7testing8internal14WithArgsActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1965' c='_ZNK7testing8internal11DoAllActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1967' c='_ZNK7testing8internal11DoAllActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1968' c='_ZNK7testing8internal11DoAllActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='1977' c='_ZNK7testing8internal11DoAllActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='2075' c='_ZNK7testing8internal11ThrowActioncvNS_6ActionIFTL0__DpTL0_0_EEEEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='2452' c='_ZN7testing8internal10MakeActionEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='2453' c='_ZN7testing8internal10MakeActionEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='2458' c='_ZN7testing8internal10MakeActionESt10shared_ptrIT0_E'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='2459' c='_ZN7testing8internal10MakeActionESt10shared_ptrIT0_E'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='8547' c='_ZN7testing8internal10OnCallSpec13WillByDefaultERKNS_6ActionIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='8565' c='_ZNK7testing8internal10OnCallSpec9GetActionEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='8588'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9135' c='_ZN7testing8internal16TypedExpectationD1Ev'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9227' c='_ZN7testing8internal16TypedExpectation8WillOnceERKNS_6ActionIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9233' c='_ZN7testing8internal16TypedExpectation8WillOnceERKNS_6ActionIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9241' c='_ZN7testing8internal16TypedExpectation14WillRepeatedlyERKNS_6ActionIT_EE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9291' c='_ZNK7testing8internal16TypedExpectation15repeated_actionEv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9383' c='_ZNK7testing8internal16TypedExpectation16GetCurrentActionEPKNS0_14FunctionMockerIT_EERKNS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9408' c='_ZNK7testing8internal16TypedExpectation16GetCurrentActionEPKNS0_14FunctionMockerIT_EERKNS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9420' c='_ZN7testing8internal16TypedExpectation21GetActionForArgumentsEPKNS0_14FunctionMockerIT_EERKNS0_8FunctionIS3_E13ArgumentTupleEPSoSC_'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9453'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9622' c='_ZN7testing8internal18ActionResultHolder13PerformActionERKNS_6ActionITL0__EEONS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9662' c='_ZN7testing8internal18ActionResultHolderIvE13PerformActionERKNS_6ActionIT_EEONS0_8FunctionIS4_E13ArgumentTupleE'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9776' c='_ZNK7testing8internal14FunctionMockerIFT_DpT0_EE20UntypedPerformActionEPKvPv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9776' c='_ZNK7testing8internal14FunctionMockerIFT_DpT0_EE20UntypedPerformActionEPKvPv'/>
<use f='fmt-8.1.0/test/gtest/gmock/gmock.h' l='9930' c='_ZN7testing8internal14FunctionMockerIFT_DpT0_EE30UntypedFindMatchingExpectationEPKvPS8_PbPSoSB_'/>
<fun r='_ZN7testing6ActionC1Ev'/>
<fun r='_ZN7testing6ActionC1EOTL0__'/>
<fun r='_ZN7testing6ActionC1EPNS_15ActionInterfaceIT_EE'/>
<fun r='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<fun r='_ZNK7testing6Action11IsDoDefaultEv'/>
<fun r='_ZNK7testing6Action7PerformENS_8internal8FunctionIT_E13ArgumentTupleE'/>
<fun r='_ZN7testing6Action4InitEOTL0__St17integral_constantIbLb1EE'/>
<fun r='_ZN7testing6Action4InitEOTL0__St17integral_constantIbLb0EE'/>
<mbr r='testing::Action::fun_' t='::std::function&lt;F&gt;'/>
