<def f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1142' ll='1186'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1146' c='_ZN7testing8internal2REC1ERKS1_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1161' c='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1164' c='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1168' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1169' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6904' c='_ZN7testing8internal19MatchesRegexMatcherC1EPKNS0_2REEb'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6948'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6956' c='_ZN7testing12MatchesRegexEPKNS_8internal2REE'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6962' c='_ZN7testing12MatchesRegexERKT_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6968' c='_ZN7testing13ContainsRegexEPKNS_8internal2REE'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='6974' c='_ZN7testing13ContainsRegexERKT_'/>
<use f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='7165' c='_ZN7testing8internal20MakeDeathTestMatcherB5cxx11ENS0_2REE'/>
<size>144</size>
<doc f='fmt-8.1.0/test/gtest/gtest/gtest.h' l='1140'>// A simple C++ wrapper for &lt;regex.h&gt;.  It uses the POSIX Extended
// Regular Expression syntax.</doc>
<fun r='_ZN7testing8internal2REC1ERKS1_'/>
<fun r='_ZN7testing8internal2REC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN7testing8internal2REC1EPKc'/>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZNK7testing8internal2RE7patternEv'/>
<fun r='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
<mbr r='testing::internal::RE::pattern_' o='0' t='const char *'/>
<mbr r='testing::internal::RE::is_valid_' o='64' t='bool'/>
<mbr r='testing::internal::RE::full_regex_' o='128' t='regex_t'/>
<mbr r='testing::internal::RE::partial_regex_' o='640' t='regex_t'/>
<use f='fmt-8.1.0/test/gtest/gmock-gtest-all.cc' l='11052' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='fmt-8.1.0/test/gtest/gmock-gtest-all.cc' l='11061' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<size>144</size>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
