<dec f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jpeglib.h' l='195' type='int'/>
<offset>160</offset>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='200' u='r' c='validate_script'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='230' u='r' c='validate_script'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='331' u='r' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='413' u='w' c='fill_a_scan'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='430' u='w' c='fill_scans'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='450' u='w' c='fill_dc_scans'/>
