<dec f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jpeglib.h' l='196' type='int'/>
<offset>256</offset>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='233' u='r' c='validate_script'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='334' u='r' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='416' u='w' c='fill_a_scan'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='433' u='w' c='fill_scans'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcparam.c' l='452' u='w' c='fill_dc_scans'/>
