<def f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-aat-layout-morx-table.hh' l='866' ll='884'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-aat-layout-morx-table.hh' l='983' c='_ZNK3AAT5Chain13compile_flagsEPK20hb_aat_map_builder_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-aat-layout-morx-table.hh' l='1118'/>
<size>12</size>
<fun r='_ZNK3AAT7Feature8sanitizeEP21hb_sanitize_context_t'/>
<mbr r='AAT::Feature::featureType' o='0' t='OT::HBUINT16'/>
<mbr r='AAT::Feature::featureSetting' o='16' t='OT::HBUINT16'/>
<mbr r='AAT::Feature::enableFlags' o='32' t='OT::HBUINT32'/>
<mbr r='AAT::Feature::disableFlags' o='64' t='OT::HBUINT32'/>
<fun r='_ZNK3AAT7Feature31_instance_assertion_on_line_883Ev'/>
<fun r='_ZNK3AAT7Feature8get_sizeEv'/>
<smbr r='AAT::Feature::null_size' t='const unsigned int'/>
<smbr r='AAT::Feature::min_size' t='const unsigned int'/>
<smbr r='AAT::Feature::static_size' t='const unsigned int'/>
