<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='99' u='m' c='_ZN3CFF7point_t7set_intEii'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='103' u='w' c='_ZN3CFF7point_t6move_xERKNS_8number_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='106' u='r' c='_ZN3CFF7point_t4moveERKS0_'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='108' type='CFF::number_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='189' u='a' c='_ZNK3CFF15cs_interp_env_t5get_xEv'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='848' u='m' c='_ZN3CFF12path_procs_t5flex1ERT0_RT1_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-cff-interp-cs-common.hh' l='855' u='w' c='_ZN3CFF12path_procs_t5flex1ERT0_RT1_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='278' u='m' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='278' u='r' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='278' u='w' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='278' u='r' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='279' u='m' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='279' u='r' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='279' u='w' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='279' u='r' c='_ZN8bounds_t6updateERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='290' u='m' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='290' u='r' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='290' u='w' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='290' u='r' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='291' u='m' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='291' u='r' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='291' u='w' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='291' u='r' c='_ZN8bounds_t5mergeERKS_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='306' u='m' c='_ZNK8bounds_t5emptyEv'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='306' u='r' c='_ZNK8bounds_t5emptyEv'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='371' u='w' c='_ZN23cff1_cs_opset_extents_t12process_seacERN3CFF20cff1_cs_interp_env_tER20cff1_extents_param_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='418' u='m' c='_ZNK2OT4cff113accelerator_t11get_extentsEP9hb_font_tjP18hb_glyph_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='418' u='r' c='_ZNK2OT4cff113accelerator_t11get_extentsEP9hb_font_tjP18hb_glyph_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='425' u='m' c='_ZNK2OT4cff113accelerator_t11get_extentsEP9hb_font_tjP18hb_glyph_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='426' u='m' c='_ZNK2OT4cff113accelerator_t11get_extentsEP9hb_font_tjP18hb_glyph_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='459' u='m' c='_ZN17cff1_path_param_t7move_toERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='466' u='m' c='_ZN17cff1_path_param_t7line_toERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='478' u='m' c='_ZN17cff1_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='479' u='m' c='_ZN17cff1_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='480' u='m' c='_ZN17cff1_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff1-table.cc' l='525' u='w' c='_ZN20cff1_cs_opset_path_t12process_seacERN3CFF20cff1_cs_interp_env_tER17cff1_path_param_t'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='53' u='m' c='_ZN20cff2_extents_param_t13update_boundsERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='53' u='r' c='_ZN20cff2_extents_param_t13update_boundsERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='54' u='m' c='_ZN20cff2_extents_param_t13update_boundsERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='54' u='r' c='_ZN20cff2_extents_param_t13update_boundsERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='164' u='m' c='_ZN17cff2_path_param_t7move_toERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='167' u='m' c='_ZN17cff2_path_param_t7line_toERKN3CFF7point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='171' u='m' c='_ZN17cff2_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='172' u='m' c='_ZN17cff2_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-cff2-table.cc' l='173' u='m' c='_ZN17cff2_path_param_t8cubic_toERKN3CFF7point_tES3_S3_'/>
