<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2748' u='r' c='_ZNK17DomConnectionHint11hasElementXEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2767' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5895' u='r' c='_ZNK17DomConnectionHint5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5906' u='r' c='_ZN17DomConnectionHint11setElementXEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5918' u='r' c='_ZN17DomConnectionHint13clearElementXEv'/>
