<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1239' u='r' c='_ZNK8DomColor13hasElementRedEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1264' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='2421' u='r' c='_ZNK8DomColor5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='2435' u='r' c='_ZN8DomColor13setElementRedEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='2453' u='r' c='_ZN8DomColor15clearElementRedEv'/>
