<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2753' u='r' c='_ZNK17DomConnectionHint11hasElementYEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2768' type='2'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5898' u='r' c='_ZNK17DomConnectionHint5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5912' u='r' c='_ZN17DomConnectionHint11setElementYEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='5923' u='r' c='_ZN17DomConnectionHint13clearElementYEv'/>
