<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1694' u='r' c='_ZNK8DomPoint11hasElementYEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1706' type='2'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3316' u='r' c='_ZNK8DomPoint5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3330' u='r' c='_ZN8DomPoint11setElementYEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3341' u='r' c='_ZN8DomPoint13clearElementYEv'/>
