<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2282' u='r' c='_ZNK9DomPointF11hasElementXEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2298' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4500' u='r' c='_ZNK9DomPointF5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4511' u='r' c='_ZN9DomPointF11setElementXEd'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4523' u='r' c='_ZN9DomPointF13clearElementXEv'/>
