<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1689' u='r' c='_ZNK8DomPoint11hasElementXEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1705' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3313' u='r' c='_ZNK8DomPoint5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3324' u='r' c='_ZN8DomPoint11setElementXEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3336' u='r' c='_ZN8DomPoint13clearElementXEv'/>
