<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2287' u='r' c='_ZNK9DomPointF11hasElementYEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2299' type='2'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4503' u='r' c='_ZNK9DomPointF5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4517' u='r' c='_ZN9DomPointF11setElementYEd'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4528' u='r' c='_ZN9DomPointF13clearElementYEv'/>
