<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2315' u='r' c='_ZNK8DomRectF11hasElementXEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2343' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4570' u='r' c='_ZNK8DomRectF5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4587' u='r' c='_ZN8DomRectF11setElementXEd'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4611' u='r' c='_ZN8DomRectF13clearElementXEv'/>
