<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1727' u='r' c='_ZNK7DomRect11hasElementYEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1751' type='2'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3386' u='r' c='_ZNK7DomRect5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3406' u='r' c='_ZN7DomRect11setElementYEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3429' u='r' c='_ZN7DomRect13clearElementYEv'/>
