<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1722' u='r' c='_ZNK7DomRect11hasElementXEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='1750' type='1'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3383' u='r' c='_ZNK7DomRect5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3400' u='r' c='_ZN7DomRect11setElementXEi'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='3424' u='r' c='_ZN7DomRect13clearElementXEv'/>
