<use f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2320' u='r' c='_ZNK8DomRectF11hasElementYEv'/>
<dec f='qtbase-6.5.0/src/tools/uic/ui4.h' l='2344' type='2'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4573' u='r' c='_ZNK8DomRectF5writeER16QXmlStreamWriterRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4593' u='r' c='_ZN8DomRectF11setElementYEd'/>
<use f='qtbase-6.5.0/src/tools/uic/ui4.cpp' l='4616' u='r' c='_ZN8DomRectF13clearElementYEv'/>
