<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='63' u='w' c='_ZN15glyph_metrics_tC1Ev'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='66' u='w' c='_ZN15glyph_metrics_tC1E6QFixedS0_S0_S0_S0_S0_'/>
<dec f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='73' type='QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='80' u='r' c='_ZNK15glyph_metrics_t7isValidEv'/>
<offset>32</offset>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3014' u='m' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3025' u='m' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qtextureglyphcache.cpp' l='149' u='m' c='_ZN18QTextureGlyphCache8populateEP11QFontEnginexPKjPK11QFixedPoint6QFlagsIN8QPainter10RenderHintEEb'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1469' u='w' c='_ZN13QFontEngineFT16getUnscaledGlyphEjP12QPainterPathP15glyph_metrics_t'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1661' u='m' c='_ZNK13QFontEngineFT19scaledBitmapMetricsERK15glyph_metrics_tRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1669' u='w' c='_ZNK13QFontEngineFT19scaledBitmapMetricsERK15glyph_metrics_tRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1718' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1721' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1745' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1745' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1759' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1759' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1765' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1791' u='w' c='_ZN13QFontEngineFT11boundingBoxEj'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1806' u='w' c='_ZN13QFontEngineFT11boundingBoxEj'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1839' u='w' c='_ZN13QFontEngineFT19alphaMapBoundingBoxEjRK11QFixedPointRK10QTransformN11QFontEngine11GlyphFormatE'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1855' u='w' c='_ZN13QFontEngineFT19alphaMapBoundingBoxEjRK11QFixedPointRK10QTransformN11QFontEngine11GlyphFormatE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='594' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='596' u='w' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='596' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='602' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='760' u='r' c='_ZN11QFontEngine19addBitmapFontToPathEddRK12QGlyphLayoutP12QPainterPath6QFlagsIN9QTextItem10RenderFlagEE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='867' u='m' c='_ZN11QFontEngine16alphaMapForGlyphEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='869' u='m' c='_ZN11QFontEngine16alphaMapForGlyphEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1965' u='w' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1965' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1965' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1967' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1967' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1968' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1968' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1990' u='w' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1990' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1990' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1992' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1992' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1993' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1993' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='626' u='r' c='_ZNK12QFontMetrics12boundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='662' u='r' c='_ZNK12QFontMetrics12boundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='697' u='r' c='_ZNK12QFontMetrics12boundingRectE5QChar'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='829' u='r' c='_ZNK12QFontMetrics17tightBoundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='862' u='r' c='_ZNK12QFontMetrics17tightBoundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1542' u='m' c='_ZNK13QFontMetricsF12boundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1577' u='m' c='_ZNK13QFontMetricsF12boundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1610' u='m' c='_ZNK13QFontMetricsF12boundingRectE5QChar'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1750' u='m' c='_ZNK13QFontMetricsF17tightBoundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1783' u='m' c='_ZNK13QFontMetricsF17tightBoundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qharfbuzzng.cpp' l='523' u='m' c='_ZL29_hb_qt_font_get_glyph_extentsP9hb_font_tPvjP18hb_glyph_extents_tS1_'/>
<use f='qtbase-6.5.0/src/gui/text/qrawfont.cpp' l='790' u='m' c='_ZNK8QRawFont12boundingRectEj'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2178' u='w' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2178' u='r' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2178' u='m' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2201' u='w' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2201' u='r' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2201' u='m' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='3806' u='m' c='_ZNK15glyph_metrics_t11transformedERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='3809' u='w' c='_ZNK15glyph_metrics_t11transformedERK10QTransform'/>
