<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='63' u='w' c='_ZN15glyph_metrics_tC1Ev'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='65' u='w' c='_ZN15glyph_metrics_tC1E6QFixedS0_S0_S0_S0_S0_'/>
<dec f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='72' type='QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='80' u='r' c='_ZNK15glyph_metrics_t7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='87' u='r' c='_ZNK15glyph_metrics_t11leftBearingEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine_p.h' l='95' u='r' c='_ZNK15glyph_metrics_t12rightBearingEv'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3013' u='m' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3024' u='m' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qtextureglyphcache.cpp' l='148' u='m' c='_ZN18QTextureGlyphCache8populateEP11QFontEnginexPKjPK11QFixedPoint6QFlagsIN8QPainter10RenderHintEEb'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1468' u='w' c='_ZN13QFontEngineFT16getUnscaledGlyphEjP12QPainterPathP15glyph_metrics_t'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1661' u='m' c='_ZNK13QFontEngineFT19scaledBitmapMetricsERK15glyph_metrics_tRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1668' u='w' c='_ZNK13QFontEngineFT19scaledBitmapMetricsERK15glyph_metrics_tRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1744' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1744' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1758' u='w' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1758' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1766' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1790' u='w' c='_ZN13QFontEngineFT11boundingBoxEj'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1805' u='w' c='_ZN13QFontEngineFT11boundingBoxEj'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1838' u='w' c='_ZN13QFontEngineFT19alphaMapBoundingBoxEjRK11QFixedPointRK10QTransformN11QFontEngine11GlyphFormatE'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1854' u='w' c='_ZN13QFontEngineFT19alphaMapBoundingBoxEjRK11QFixedPointRK10QTransformN11QFontEngine11GlyphFormatE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='593' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='595' u='w' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='595' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='603' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='760' u='r' c='_ZN11QFontEngine19addBitmapFontToPathEddRK12QGlyphLayoutP12QPainterPath6QFlagsIN9QTextItem10RenderFlagEE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='866' u='m' c='_ZN11QFontEngine16alphaMapForGlyphEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='868' u='m' c='_ZN11QFontEngine16alphaMapForGlyphEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1964' u='w' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1964' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1964' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1989' u='w' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1989' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='1989' u='r' c='_ZN16QFontEngineMulti11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='626' u='r' c='_ZNK12QFontMetrics12boundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='662' u='r' c='_ZNK12QFontMetrics12boundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='697' u='r' c='_ZNK12QFontMetrics12boundingRectE5QChar'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='829' u='r' c='_ZNK12QFontMetrics17tightBoundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='862' u='r' c='_ZNK12QFontMetrics17tightBoundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1542' u='m' c='_ZNK13QFontMetricsF12boundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1577' u='m' c='_ZNK13QFontMetricsF12boundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1610' u='m' c='_ZNK13QFontMetricsF12boundingRectE5QChar'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1750' u='m' c='_ZNK13QFontMetricsF17tightBoundingRectERK7QString'/>
<use f='qtbase-6.5.0/src/gui/text/qfontmetrics.cpp' l='1783' u='m' c='_ZNK13QFontMetricsF17tightBoundingRectERK7QStringRK11QTextOption'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='1165' u='m' c='_ZNK11QFontSubset10toTruetypeEv'/>
<use f='qtbase-6.5.0/src/gui/text/qharfbuzzng.cpp' l='522' u='m' c='_ZL29_hb_qt_font_get_glyph_extentsP9hb_font_tPvjP18hb_glyph_extents_tS1_'/>
<use f='qtbase-6.5.0/src/gui/text/qrawfont.cpp' l='790' u='m' c='_ZNK8QRawFont12boundingRectEj'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2177' u='w' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2177' u='r' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2177' u='m' c='_ZNK11QTextEngine11boundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2200' u='w' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2200' u='r' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='2200' u='m' c='_ZNK11QTextEngine16tightBoundingBoxEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='3806' u='m' c='_ZNK15glyph_metrics_t11transformedERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='3808' u='w' c='_ZNK15glyph_metrics_t11transformedERK10QTransform'/>
