<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='349' u='w' c='_ZN23hb_bit_set_invertible_t6iter_tC1ERKS_b'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='353' u='w' c='_ZN23hb_bit_set_invertible_t6iter_tC1ERKS_b'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='361' u='r' c='_ZN23hb_bit_set_invertible_t6iter_t8__next__Ev'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='361' u='w' c='_ZN23hb_bit_set_invertible_t6iter_t8__next__Ev'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='363' u='r' c='_ZNK23hb_bit_set_invertible_t6iter_t7__len__Ev'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set-invertible.hh' l='371' type='unsigned int'/>
<offset>96</offset>
