<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='867' u='w' c='_ZN12hb_bit_set_t6iter_tC1ERKS_b'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='871' u='w' c='_ZN12hb_bit_set_t6iter_tC1ERKS_b'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='879' u='r' c='_ZN12hb_bit_set_t6iter_t8__next__Ev'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='879' u='w' c='_ZN12hb_bit_set_t6iter_t8__next__Ev'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='881' u='r' c='_ZNK12hb_bit_set_t6iter_t7__len__Ev'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-bit-set.hh' l='889' type='unsigned int'/>
<offset>96</offset>
