<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='166' u='w' c='_ZN17hb_draw_session_tC1EP15hb_draw_funcs_tPvf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='174' u='a' c='_ZN17hb_draw_session_t7move_toEff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='177' u='a' c='_ZN17hb_draw_session_t7move_toEff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='183' u='a' c='_ZN17hb_draw_session_t7line_toEff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='186' u='a' c='_ZN17hb_draw_session_t7line_toEff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='194' u='a' c='_ZN17hb_draw_session_t12quadratic_toEffff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='198' u='a' c='_ZN17hb_draw_session_t12quadratic_toEffff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='208' u='a' c='_ZN17hb_draw_session_t8cubic_toEffffff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='213' u='a' c='_ZN17hb_draw_session_t8cubic_toEffffff'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='220' u='a' c='_ZN17hb_draw_session_t10close_pathEv'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-draw.hh' l='228' type='hb_draw_state_t'/>
<offset>192</offset>
