<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='86' type='struct get_funcs_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='256' u='m' c='_ZN9hb_font_t18get_font_h_extentsEP17hb_font_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='263' u='m' c='_ZN9hb_font_t18get_font_v_extentsEP17hb_font_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='279' u='m' c='_ZN9hb_font_t17get_nominal_glyphEjPjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='289' u='m' c='_ZN9hb_font_t18get_nominal_glyphsEjPKjjPjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='301' u='m' c='_ZN9hb_font_t19get_variation_glyphEjjPjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='308' u='m' c='_ZN9hb_font_t19get_glyph_h_advanceEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='315' u='m' c='_ZN9hb_font_t19get_glyph_v_advanceEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='326' u='m' c='_ZN9hb_font_t20get_glyph_h_advancesEjPKjjPij'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='339' u='m' c='_ZN9hb_font_t20get_glyph_v_advancesEjPKjjPij'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='350' u='m' c='_ZN9hb_font_t18get_glyph_h_originEjPiS0_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='359' u='m' c='_ZN9hb_font_t18get_glyph_v_originEjPiS0_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='370' u='m' c='_ZN9hb_font_t19get_glyph_h_kerningEjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='382' u='m' c='_ZN9hb_font_t19get_glyph_v_kerningEjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='392' u='m' c='_ZN9hb_font_t17get_glyph_extentsEjP18hb_glyph_extents_t'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='402' u='m' c='_ZN9hb_font_t23get_glyph_contour_pointEjjPiS0_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='412' u='m' c='_ZN9hb_font_t14get_glyph_nameEjPcj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='423' u='m' c='_ZN9hb_font_t19get_glyph_from_nameEPKciPj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='432' u='m' c='_ZN9hb_font_t10draw_glyphEjP15hb_draw_funcs_tPv'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.hh' l='443' u='m' c='_ZN9hb_font_t11paint_glyphEjP16hb_paint_funcs_tPvjj'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_font_h_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_font_h_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_font_v_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_font_v_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_nominal_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_nominal_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_nominal_glyphs_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_nominal_glyphs_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_variation_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_variation_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_h_advance_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_h_advance_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_v_advance_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_v_advance_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_h_advances_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_h_advances_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_v_advances_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_v_advances_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_h_origin_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_h_origin_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_v_origin_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_v_origin_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_h_kerning_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_h_kerning_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_v_kerning_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_v_kerning_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_extents_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_contour_point_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_contour_point_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_name_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_name_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_glyph_from_name_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_glyph_from_name_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_draw_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_draw_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='935' u='m' c='hb_font_funcs_set_paint_glyph_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-font.cc' l='937' u='m' c='hb_font_funcs_set_paint_glyph_func'/>
