<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.hh' l='60' u='r' c='_ZN18hb_unicode_funcs_t6scriptEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.hh' l='60' u='r' c='_ZN18hb_unicode_funcs_t6scriptEj'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.hh' l='48' type='hb_unicode_script_func_t'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.hh' l='48' type='void *'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.hh' l='48' type='hb_destroy_func_t'/>
<offset>256</offset>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='266' macro='1' u='r' c='hb_unicode_funcs_destroy'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='266' macro='1' u='r' c='hb_unicode_funcs_destroy'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='266' macro='1' u='r' c='hb_unicode_funcs_destroy'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='r' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='r' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='r' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='r' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='w' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='w' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='r' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='w' c='hb_unicode_funcs_set_script_func'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-unicode.cc' l='406' macro='1' u='w' c='hb_unicode_funcs_set_script_func'/>
