<dec f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jpeglib.h' l='445' type='int'/>
<offset>3680</offset>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='340' u='r' c='emit_restart'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='498' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='641' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='846' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='851' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='863' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmarker.c' l='244' u='r' c='emit_dac'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmarker.c' l='339' u='r' c='emit_sos'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmarker.c' l='346' u='r' c='emit_sos'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmarker.c' l='577' u='r' c='write_scan_header'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='331' u='w' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='346' u='w' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='483' u='r' c='prepare_for_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='216' u='r' c='start_pass_phuff'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='464' u='r' c='emit_restart'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='666' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='690' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='931' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='956' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='1059' u='r' c='finish_pass_gather_phuff'/>
