<dec f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jpeglib.h' l='677' type='int'/>
<offset>4352</offset>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='316' u='r' c='decode_mcu_DC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='391' u='r' c='decode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='417' u='r' c='decode_mcu_DC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='458' u='r' c='decode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='459' u='r' c='decode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='653' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='656' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='659' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='682' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdarith.c' l='702' u='r' c='start_pass'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdhuff.c' l='89' u='r' c='start_pass_huff_decoder'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdmarker.c' l='368' u='w' c='get_sos'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdmarker.c' l='371' u='r' c='get_sos'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='106' u='r' c='start_pass_phuff_decoder'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='109' u='r' c='start_pass_phuff_decoder'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='119' u='r' c='start_pass_phuff_decoder'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='140' u='r' c='start_pass_phuff_decoder'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='291' u='r' c='decode_mcu_DC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='368' u='r' c='decode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='453' u='r' c='decode_mcu_DC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='504' u='r' c='decode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jdphuff.c' l='505' u='r' c='decode_mcu_AC_refine'/>
