<dec f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jpeglib.h' l='445' type='int'/>
<offset>3776</offset>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='397' u='r' c='encode_mcu_DC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='491' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='494' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='503' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='510' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='576' u='r' c='encode_mcu_DC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='625' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='628' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='647' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcarith.c' l='658' u='r' c='encode_mcu_AC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmarker.c' l='348' u='r' c='emit_sos'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='334' u='w' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcmaster.c' l='349' u='w' c='select_scan_parameters'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='488' u='r' c='encode_mcu_DC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='667' u='r' c='encode_mcu_AC_first'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='758' u='r' c='encode_mcu_DC_refine'/>
<use f='qtbase-6.5.0/src/3rdparty/libjpeg/src/jcphuff.c' l='932' u='r' c='encode_mcu_AC_refine'/>
