<dec f='qtbase-6.5.0/src/tools/uic/shared/language.h' l='13' type='0'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='554' u='r' c='_ZN3CPP19WriteInitialization8acceptUIEP5DomUI'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1133' c='_ZNK3CPP19WriteInitialization23writeStringListPropertyEPK13DomStringList'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1198' c='_ZN3CPP19WriteInitialization15writePropertiesERK7QStringS3_RK5QListIP11DomPropertyEj'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1329' u='r' c='_ZN3CPP19WriteInitialization15writePropertiesERK7QStringS3_RK5QListIP11DomPropertyEj'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1353' u='r' c='_ZN3CPP19WriteInitialization15writePropertiesERK7QStringS3_RK5QListIP11DomPropertyEj'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1550' u='r' c='_ZN3CPP19WriteInitialization15writePropertiesERK7QStringS3_RK5QListIP11DomPropertyEj'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='1781' u='r' c='_ZN3CPP19WriteInitialization19writeIconPropertiesEPK15DomResourceIcon'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='2132' u='r' c='_ZN3CPP19WriteInitialization14disableSortingEP9DomWidgetRK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='2719' u='r' c='_ZN3CPP19WriteInitialization4Item12writeSetupUiERK7QStringNS1_15EmptyItemPolicyE'/>
<use f='qtbase-6.5.0/src/tools/uic/cpp/cppwriteinitialization.cpp' l='2756' u='r' c='_ZN3CPP19WriteInitialization4Item18writeRetranslateUiERK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/main.cpp' l='166' u='r' c='_Z6runUiciPPc'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='13'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='21' c='_ZN8language11setLanguageE8Language'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='288' u='r' c='_ZN8language13_formatStringER11QTextStreamRK7QStringS4_b'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='293' u='r' c='_ZN8language13_formatStringER11QTextStreamRK7QStringS4_b'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='325' c='_ZN8languagelsER11QTextStreamRKNS_24startFunctionDefinition1E'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='346' c='_ZN8languagelsER11QTextStreamRKNS_21endFunctionDefinitionE'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='360' c='_ZN8language20_formatStackVariableER11QTextStreamPKc11QStringViewb'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='426' c='_ZN8language16formatConnectionER11QTextStreamRKNS_10SignalSlotES4_16ConnectionSyntax'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='459' c='_ZN8language9boolValueEb'/>
<use f='qtbase-6.5.0/src/tools/uic/shared/language.cpp' l='471' u='r' c='_ZN8language9enumValueERK7QString'/>
<use f='qtbase-6.5.0/src/tools/uic/uic.cpp' l='231' c='_ZN3Uic5writeEP5DomUI'/>
<use f='qtbase-6.5.0/src/tools/uic/uic.cpp' l='240' u='r' c='_ZN3Uic5writeEP5DomUI'/>
<use f='qtbase-6.5.0/src/tools/uic/uic.cpp' l='256' c='_ZN3Uic5writeEP5DomUI'/>
<use f='qtbase-6.5.0/src/tools/uic/uic.cpp' l='272' u='r' c='_ZN3Uic5writeEP5DomUI'/>
