<dec f='qtbase-6.5.0/src/gui/painting/qdrawhelper_p.h' l='166' type='qreal'/>
<offset>128</offset>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3243' u='w' c='_ZL23getLinearGradientValuesP20LinearGradientValuesPK9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3245' u='r' c='_ZL23getLinearGradientValuesP20LinearGradientValuesPK9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3246' u='r' c='_ZL23getLinearGradientValuesP20LinearGradientValuesPK9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3247' u='r' c='_ZL23getLinearGradientValuesP20LinearGradientValuesPK9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3325' u='r' c='_ZL33qt_fetch_linear_gradient_templatePT0_PK8OperatorPK9QSpanDataiii'/>
