<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.hh' l='161'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.hh' l='162'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='66'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='140'/>
<def f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='746' ll='839'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='855' c='_ZNK2OT6Record6subsetEPNS_26hb_subset_layout_context_tEPKvS4_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='855' c='_ZNK2OT6Record6subsetEPNS_26hb_subset_layout_context_tEPKvS4_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='938'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='949' c='_ZNK2OT19RecordListOfFeature6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='951' c='_ZNK2OT19RecordListOfFeature6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='952' c='_ZNK2OT19RecordListOfFeature6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='964'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3085' c='_ZNK2OT30FeatureTableSubstitutionRecord43collect_feature_substitutes_with_variationsEP12hb_hashmap_tIjPKNS_7FeatureELb0EEPK8hb_set_tPKv'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3119'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3126' c='_ZNK2OT24FeatureTableSubstitution15find_substituteEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3139' c='_ZNK2OT24FeatureTableSubstitution15collect_lookupsEPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS1_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3215' c='_ZNK2OT22FeatureVariationRecord15collect_lookupsEPKvPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3294' c='_ZNK2OT17FeatureVariations15find_substituteEjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='3318' c='_ZNK2OT17FeatureVariations15collect_lookupsEPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS1_'/>
<size>6</size>
<fun r='_ZNK2OT7Feature16get_lookup_countEv'/>
<fun r='_ZNK2OT7Feature16get_lookup_indexEj'/>
<fun r='_ZNK2OT7Feature18get_lookup_indexesEjPjS1_'/>
<fun r='_ZNK2OT7Feature21add_lookup_indexes_toEP8hb_set_t'/>
<fun r='_ZNK2OT7Feature18get_feature_paramsEv'/>
<fun r='_ZNK2OT7Feature25intersects_lookup_indexesEPK8hb_map_t'/>
<fun r='_ZNK2OT7Feature6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tEPKNS_3TagE'/>
<fun r='_ZNK2OT7Feature8sanitizeEP21hb_sanitize_context_tPKNS_25Record_sanitize_closure_tE'/>
<mbr r='OT::Feature::featureParams' o='0' t='Offset16To&lt;OT::FeatureParams&gt;'/>
<mbr r='OT::Feature::lookupIndex' o='16' t='OT::IndexArray'/>
<fun r='_ZNK2OT7Feature8get_sizeEv'/>
<fun r='_ZNK2OT7Feature31_compiles_assertion_on_line_838Ev'/>
<fun r='_ZNK2OT7Feature31_instance_assertion_on_line_838Ev'/>
<smbr r='OT::Feature::null_size' t='const unsigned int'/>
<smbr r='OT::Feature::min_size' t='const unsigned int'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4339' c='_ZNK2OT8GSUBGPOS11get_featureEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4353' c='_ZNK2OT8GSUBGPOS21get_feature_variationEjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4360' c='_ZNK2OT8GSUBGPOS21get_feature_variationEjj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4370' c='_ZNK2OT8GSUBGPOS33feature_variation_collect_lookupsEPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS1_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4419' c='_ZNK2OT8GSUBGPOS14prune_featuresEPK8hb_map_tPK12hb_hashmap_tIjN2hb10shared_ptrI8hb_set_tEELb0EEPKS4_IjPKNS_7FeatureELb0EEPS7_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4446' c='_ZNK2OT8GSUBGPOS14prune_featuresEPK8hb_map_tPK12hb_hashmap_tIjN2hb10shared_ptrI8hb_set_tEELb0EEPKS4_IjPKNS_7FeatureELb0EEPS7_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4447' c='_ZNK2OT8GSUBGPOS14prune_featuresEPK8hb_map_tPK12hb_hashmap_tIjN2hb10shared_ptrI8hb_set_tEELb0EEPKS4_IjPKNS_7FeatureELb0EEPS7_'/>
<size>6</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='1438' c='hb_ot_layout_feature_with_variations_get_lookups'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='1686' c='hb_ot_layout_get_size_params'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='1749' c='hb_ot_layout_feature_get_name_ids'/>
<size>6</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='136' c='_ZL23_collect_layout_indicesP16hb_subset_plan_tRKT_P8hb_set_tS5_P12hb_hashmap_tIjN2hb10shared_ptrIS4_EELb0EEPS6_IjPKN2OT7FeatureELb0EE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='183' c='_ZL23_collect_layout_indicesP16hb_subset_plan_tRKT_P8hb_set_tS5_P12hb_hashmap_tIjN2hb10shared_ptrIS4_EELb0EEPS6_IjPKN2OT7FeatureELb0EE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='184' c='_ZL23_collect_layout_indicesP16hb_subset_plan_tRKT_P8hb_set_tS5_P12hb_hashmap_tIjN2hb10shared_ptrIS4_EELb0EEPS6_IjPKN2OT7FeatureELb0EE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='209' c='_ZL33_GSUBGPOS_find_duplicate_featuresRKN2OT8GSUBGPOSEPK8hb_map_tPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='234' c='_ZL33_GSUBGPOS_find_duplicate_featuresRKN2OT8GSUBGPOSEPK8hb_map_tPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='235' c='_ZL33_GSUBGPOS_find_duplicate_featuresRKN2OT8GSUBGPOSEPK8hb_map_tPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='239' c='_ZL33_GSUBGPOS_find_duplicate_featuresRKN2OT8GSUBGPOSEPK8hb_map_tPK8hb_set_tPK12hb_hashmap_tIjPKNS_7FeatureELb0EEPS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-subset-plan.cc' l='284' c='_ZL32_closure_glyphs_lookups_featuresP16hb_subset_plan_tP8hb_set_tP8hb_map_tS4_P12hb_hashmap_tIjN2hb10unique_ptrIS1_EELb0EEPS5_IjNS6_10shared_ptrIS1_E2470023'/>
<size>6</size>
