<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='44' u='w' c='_ZN2OT15contour_point_t4initEffb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='46' u='w' c='_ZN2OT15contour_point_t9translateERKS0_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='46' u='r' c='_ZN2OT15contour_point_t9translateERKS0_'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='48' type='float'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='76' u='r' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='77' u='r' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='78' u='w' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='84' u='r' c='_ZN2OT22contour_point_vector_t9translateERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='623' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='634' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='682' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='682' u='a' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='695' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='695' u='r' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/SimpleGlyph.hh' l='204' u='a' c='_ZNK2OT9glyf_impl11SimpleGlyph18get_contour_pointsERNS_22contour_point_vector_tEb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/SimpleGlyph.hh' l='287' u='r' c='_ZN2OT9glyf_impl11SimpleGlyph25compile_bytes_with_deltasERKNS_22contour_point_vector_tEbR10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/CompositeGlyph.hh' l='129' u='r' c='_ZNK2OT9glyf_impl20CompositeGlyphRecord19compile_with_deltasERKNS_15contour_point_tEPc'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/CompositeGlyph.hh' l='134' u='r' c='_ZNK2OT9glyf_impl20CompositeGlyphRecord19compile_with_deltasERKNS_15contour_point_tEPc'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='117' u='r' c='_ZN2OT9glyf_impl23VarCompositeGlyphRecord9transformERA4_fRNS_15contour_point_tEPf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='124' u='w' c='_ZN2OT9glyf_impl23VarCompositeGlyphRecord9transformERA4_fRNS_15contour_point_tEPf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='192' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='215' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='221' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='226' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='232' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='238' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='269' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='275' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='280' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='286' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='292' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='321' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord14set_variationsERNS0_14coord_setter_tE10hb_array_tINS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='98' u='r' c='_ZNK2OT9glyf_impl5Glyph10update_mtxEPK16hb_subset_plan_tiiiiRKNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='99' u='r' c='_ZNK2OT9glyf_impl5Glyph10update_mtxEPK16hb_subset_plan_tiiiiRKNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='132' u='r' c='_ZNK2OT9glyf_impl5Glyph20compile_header_bytesEPK16hb_subset_plan_tRKNS_22contour_point_vector_tER10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='138' u='r' c='_ZNK2OT9glyf_impl5Glyph20compile_header_bytesEPK16hb_subset_plan_tRKNS_22contour_point_vector_tER10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='329' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='330' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='353' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='353' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='353' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='405' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='405' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='491' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='492' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/path-builder.hh' l='52' u='r' c='_ZN2OT9glyf_impl14path_builder_t13consume_pointERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='239' u='r' c='_ZN2OT18glyf_accelerator_t19points_aggregator_t16contour_bounds_t3addERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='241' u='r' c='_ZN2OT18glyf_accelerator_t19points_aggregator_t16contour_bounds_t3addERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='309' u='r' c='_ZNK2OT18glyf_accelerator_t29get_advance_with_var_unscaledEP9hb_font_tjb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='309' u='r' c='_ZNK2OT18glyf_accelerator_t29get_advance_with_var_unscaledEP9hb_font_tjb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='325' u='r' c='_ZNK2OT18glyf_accelerator_t37get_leading_bearing_with_var_unscaledEP9hb_font_tjbPi'/>
<offset>0</offset>
