<inh f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-type.hh' l='59' c='OT::IntType'/>
<def f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-type.hh' l='186' ll='194'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-type.hh' l='188' c='_ZN2OT3TagaSEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='697' c='_ZNK2OT13FeatureParams6subsetEP19hb_subset_context_tPKNS_3TagE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='767' c='_ZNK2OT7Feature6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tEPKNS_3TagE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='876'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='891' c='_ZNK2OT13RecordArrayOf7get_tagEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='1038' c='_ZNK2OT7LangSys6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tEPKNS_3TagE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='1083' c='_ZNK2OT6Script16get_lang_sys_tagEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='1144' c='_ZNK2OT6Script6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tEPKNS_3TagE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-mvar-table.hh' l='45'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-mvar-table.hh' l='95' c='_ZN2OT4MVAR11tag_compareEPKvS2_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-mvar-table.hh' l='95' c='_ZN2OT4MVAR11tag_compareEPKvS2_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-os2-table.hh' l='368'/>
<size>4</size>
<doc f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-type.hh' l='184'>/* Array of four uint8s (length = 32 bits) used to identify a script, language
 * system, feature, or baseline */</doc>
<fun r='_ZN2OT3TagaSEj'/>
<fun r='_ZNK2OT3TagcvPKcEv'/>
<fun r='_ZN2OT3TagcvPcEv'/>
<fun r='_ZNK2OT3Tag31_instance_assertion_on_line_193Ev'/>
<fun r='_ZNK2OT3Tag8get_sizeEv'/>
<smbr r='OT::Tag::null_size' t='const unsigned int'/>
<smbr r='OT::Tag::min_size' t='const unsigned int'/>
<smbr r='OT::Tag::static_size' t='const unsigned int'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4320' c='_ZNK2OT8GSUBGPOS14get_script_tagEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4410' c='_ZNK2OT8GSUBGPOS13prune_langsysEPK8hb_map_tPK8hb_set_tP12hb_hashmap_tIjN2hb10unique_ptrIS4_EELb0EEPS4_'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='56' c='_ZNK2OT11TableRecord3cmpENS_3TagE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='71'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='102' c='_ZNK2OT19OpenTypeOffsetTable16find_table_indexEjPj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='207'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='233'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='280'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='346'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-open-file.hh' l='524'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-fvar-table.hh' l='190'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/Color/sbix/sbix.hh' l='69'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/Color/sbix/sbix.hh' l='303'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-meta-table.hh' l='58'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-stat-table.hh' l='75'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-base-table.hh' l='178'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-base-table.hh' l='281'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-base-table.hh' l='345'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-base-table.hh' l='433'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-jstf-table.hh' l='150' c='_ZNK2OT10JstfScript16get_lang_sys_tagEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-jstf-table.hh' l='202' c='_ZNK2OT4JSTF14get_script_tagEj'/>
<size>4</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-shaper-arabic-fallback.hh' l='245'/>
<size>4</size>
