<def f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='1079' ll='1202'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-common.hh' l='1204'/>
<size>10</size>
<fun r='_ZNK2OT6Script18get_lang_sys_countEv'/>
<fun r='_ZNK2OT6Script16get_lang_sys_tagEj'/>
<fun r='_ZNK2OT6Script17get_lang_sys_tagsEjPjS1_'/>
<fun r='_ZNK2OT6Script12get_lang_sysEj'/>
<fun r='_ZNK2OT6Script19find_lang_sys_indexEjPj'/>
<fun r='_ZNK2OT6Script20has_default_lang_sysEv'/>
<fun r='_ZNK2OT6Script20get_default_lang_sysEv'/>
<fun r='_ZNK2OT6Script13prune_langsysEPNS_26hb_prune_langsys_context_tEj'/>
<fun r='_ZNK2OT6Script6subsetEP19hb_subset_context_tPNS_26hb_subset_layout_context_tEPKNS_3TagE'/>
<fun r='_ZNK2OT6Script8sanitizeEP21hb_sanitize_context_tPKNS_25Record_sanitize_closure_tE'/>
<mbr r='OT::Script::defaultLangSys' o='0' t='Offset16To&lt;OT::LangSys&gt;'/>
<mbr r='OT::Script::langSys' o='16' t='RecordArrayOf&lt;OT::LangSys&gt;'/>
<fun r='_ZNK2OT6Script8get_sizeEv'/>
<fun r='_ZNK2OT6Script32_compiles_assertion_on_line_1201Ev'/>
<fun r='_ZNK2OT6Script32_instance_assertion_on_line_1201Ev'/>
<smbr r='OT::Script::null_size' t='const unsigned int'/>
<smbr r='OT::Script::min_size' t='const unsigned int'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4326' c='_ZNK2OT8GSUBGPOS10get_scriptEj'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout-gsubgpos.hh' l='4412' c='_ZNK2OT8GSUBGPOS13prune_langsysEPK8hb_map_tPK8hb_set_tP12hb_hashmap_tIjN2hb10unique_ptrIS4_EELb0EEPS4_'/>
<size>10</size>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='689' c='hb_ot_layout_script_get_language_tags'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='761' c='hb_ot_layout_script_select_language2'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='1107' c='_ZN29hb_collect_features_context_t7visitedERKN2OT6ScriptE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-layout.cc' l='1199' c='_ZL23script_collect_featuresP29hb_collect_features_context_tRKN2OT6ScriptEPKj'/>
<size>10</size>
