<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='44' u='w' c='_ZN2OT15contour_point_t4initEffb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='46' u='w' c='_ZN2OT15contour_point_t9translateERKS0_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='46' u='r' c='_ZN2OT15contour_point_t9translateERKS0_'/>
<dec f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='49' type='float'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='76' u='r' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='77' u='w' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='77' u='r' c='_ZN2OT22contour_point_vector_t9transformERA4_Kf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='84' u='r' c='_ZN2OT22contour_point_vector_t9translateERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='624' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='635' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='683' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='683' u='a' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='696' u='w' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/hb-ot-var-gvar-table.hh' l='696' u='r' c='_ZNK2OT4gvar13accelerator_t22apply_deltas_to_pointsEj10hb_array_tIiES2_INS_15contour_point_tEE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/SimpleGlyph.hh' l='206' u='a' c='_ZNK2OT9glyf_impl11SimpleGlyph18get_contour_pointsERNS_22contour_point_vector_tEb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/SimpleGlyph.hh' l='288' u='r' c='_ZN2OT9glyf_impl11SimpleGlyph25compile_bytes_with_deltasERKNS_22contour_point_vector_tEbR10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/CompositeGlyph.hh' l='130' u='r' c='_ZNK2OT9glyf_impl20CompositeGlyphRecord19compile_with_deltasERKNS_15contour_point_tEPc'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/CompositeGlyph.hh' l='135' u='r' c='_ZNK2OT9glyf_impl20CompositeGlyphRecord19compile_with_deltasERKNS_15contour_point_tEPc'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='118' u='r' c='_ZN2OT9glyf_impl23VarCompositeGlyphRecord9transformERA4_fRNS_15contour_point_tEPf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='125' u='w' c='_ZN2OT9glyf_impl23VarCompositeGlyphRecord9transformERA4_fRNS_15contour_point_tEPf'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='216' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='227' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='233' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='239' u='w' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord10get_pointsERNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='270' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='281' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='287' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/VarCompositeGlyph.hh' l='293' u='r' c='_ZNK2OT9glyf_impl23VarCompositeGlyphRecord30get_transformation_from_pointsE10hb_array_tINS_15contour_point_tEERA4_fRS3_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='100' u='r' c='_ZNK2OT9glyf_impl5Glyph10update_mtxEPK16hb_subset_plan_tiiiiRKNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='101' u='r' c='_ZNK2OT9glyf_impl5Glyph10update_mtxEPK16hb_subset_plan_tiiiiRKNS_22contour_point_vector_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='133' u='r' c='_ZNK2OT9glyf_impl5Glyph20compile_header_bytesEPK16hb_subset_plan_tRKNS_22contour_point_vector_tER10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='139' u='r' c='_ZNK2OT9glyf_impl5Glyph20compile_header_bytesEPK16hb_subset_plan_tRKNS_22contour_point_vector_tER10hb_array_tIKcE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='331' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='332' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='354' u='w' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='354' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='354' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='406' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/Glyph.hh' l='406' u='r' c='_ZNK2OT9glyf_impl5Glyph10get_pointsEP9hb_font_tRKT_RNS_22contour_point_vector_tEPS7_P16head_maxp_info_tPjbbb10hb_array_tIiEjSC_'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/path-builder.hh' l='52' u='r' c='_ZN2OT9glyf_impl14path_builder_t13consume_pointERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='240' u='r' c='_ZN2OT18glyf_accelerator_t19points_aggregator_t16contour_bounds_t3addERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='242' u='r' c='_ZN2OT18glyf_accelerator_t19points_aggregator_t16contour_bounds_t3addERKNS_15contour_point_tE'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='308' u='r' c='_ZNK2OT18glyf_accelerator_t29get_advance_with_var_unscaledEP9hb_font_tjb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='308' u='r' c='_ZNK2OT18glyf_accelerator_t29get_advance_with_var_unscaledEP9hb_font_tjb'/>
<use f='qtbase-6.5.0/src/3rdparty/harfbuzz-ng/src/OT/glyf/glyf.hh' l='324' u='r' c='_ZNK2OT18glyf_accelerator_t37get_leading_bearing_with_var_unscaledEP9hb_font_tjbPi'/>
<offset>32</offset>
