<dec f='qtbase-6.5.0/src/gui/kernel/qaction.h' l='175' type='0'/>
<use f='qtbase-6.5.0/src/gui/kernel/qaction.h' l='210' u='r' c='_ZN7QAction7triggerEv'/>
<use f='qtbase-6.5.0/src/gui/kernel/qaction.cpp' l='1046' u='r' c='_ZN7QAction5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/gui/kernel/qaction.cpp' l='1087' u='r' c='_ZN7QAction8activateENS_11ActionEventE'/>
<doc f='qtbase-6.5.0/src/gui/kernel/qaction.cpp' l='1165'>\value Trigger this will cause the QAction::triggered() signal to be emitted.</doc>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='148' u='r' c='_ZN12QTornOffMenu9onTriggerEP7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='1410' u='r' c='_ZN12QMenuPrivate19activateCausedStackERK5QListI8QPointerI7QWidgetEEP7QActionNS7_11ActionEventEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='1417' u='r' c='_ZN12QMenuPrivate19activateCausedStackERK5QListI8QPointerI7QWidgetEEP7QActionNS7_11ActionEventEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='1435' u='r' c='_ZN12QMenuPrivate14activateActionEP7QActionNS0_11ActionEventEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='1446' u='r' c='_ZN12QMenuPrivate14activateActionEP7QActionNS0_11ActionEventEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='1521' u='r' c='_ZN12QMenuPrivate18_q_actionTriggeredEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='2904' u='r' c='_ZN5QMenu17mouseReleaseEventEP11QMouseEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='3275' u='r' c='_ZN5QMenu13keyPressEventEP9QKeyEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='3284' u='r' c='_ZN5QMenu13keyPressEventEP9QKeyEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='3380' u='r' c='_ZN5QMenu13keyPressEventEP9QKeyEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenubar.cpp' l='995' u='r' c='_ZN8QMenuBar17mouseReleaseEventEP11QMouseEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenubar.cpp' l='1031' u='r' c='_ZN8QMenuBar13keyPressEventEP9QKeyEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenubar.cpp' l='1666' u='r' c='_ZN15QMenuBarPrivate28_q_internalShortcutActivatedEi'/>
