<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.h' l='46' u='r' c='_ZNK17QByteArrayMatcher7patternEv'/>
<dec f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.h' l='56' type='qsizetype'/>
<offset>2112</offset>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='86' u='w' c='_ZN17QByteArrayMatcherC1Ev'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='101' u='w' c='_ZN17QByteArrayMatcherC1EPKcx'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='103' u='w' c='_ZN17QByteArrayMatcherC1EPKcx'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='104' u='r' c='_ZN17QByteArrayMatcherC1EPKcx'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='115' u='w' c='_ZN17QByteArrayMatcherC1ERK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='116' u='r' c='_ZN17QByteArrayMatcherC1ERK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='168' u='w' c='_ZN17QByteArrayMatcher10setPatternERK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='169' u='r' c='_ZN17QByteArrayMatcher10setPatternERK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='184' u='r' c='_ZNK17QByteArrayMatcher7indexInEPKcxx'/>
<use f='qtbase-6.5.0/src/corelib/text/qbytearraymatcher.cpp' l='203' u='r' c='_ZNK17QByteArrayMatcher7indexInE14QByteArrayViewx'/>
