<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.h' l='423' u='w' c='_ZN18QCborValueConstRefC1Ev'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.h' l='425' u='w' c='_ZN18QCborValueConstRefC1EP21QCborContainerPrivatex'/>
<dec f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.h' l='428' type='qsizetype'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='41' u='w' c='_ZN10QCborArray8IteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='41' u='r' c='_ZN10QCborArray8IteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='48' u='r' c='_ZNK10QCborArray8IteratorixEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='50' u='r' c='_ZNK10QCborArray8IteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='50' u='r' c='_ZNK10QCborArray8IteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='52' u='r' c='_ZNK10QCborArray8IteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='52' u='r' c='_ZNK10QCborArray8IteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='53' u='r' c='_ZNK10QCborArray8IteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='53' u='r' c='_ZNK10QCborArray8IteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='54' u='r' c='_ZNK10QCborArray8IteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='54' u='r' c='_ZNK10QCborArray8IteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='55' u='r' c='_ZNK10QCborArray8IteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='55' u='r' c='_ZNK10QCborArray8IteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='56' u='r' c='_ZNK10QCborArray8IteratoreqERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='56' u='r' c='_ZNK10QCborArray8IteratoreqERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='58' u='r' c='_ZNK10QCborArray8IteratorltERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='58' u='r' c='_ZNK10QCborArray8IteratorltERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='59' u='r' c='_ZNK10QCborArray8IteratorleERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='59' u='r' c='_ZNK10QCborArray8IteratorleERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='60' u='r' c='_ZNK10QCborArray8IteratorgtERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='60' u='r' c='_ZNK10QCborArray8IteratorgtERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='61' u='r' c='_ZNK10QCborArray8IteratorgeERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='61' u='r' c='_ZNK10QCborArray8IteratorgeERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='62' u='w' c='_ZN10QCborArray8IteratorppEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='63' u='w' c='_ZN10QCborArray8IteratorppEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='64' u='w' c='_ZN10QCborArray8IteratormmEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='65' u='w' c='_ZN10QCborArray8IteratormmEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='66' u='w' c='_ZN10QCborArray8IteratorpLEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='67' u='w' c='_ZN10QCborArray8IteratormIEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='68' u='r' c='_ZNK10QCborArray8IteratorplEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='69' u='r' c='_ZNK10QCborArray8IteratormiEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='70' u='r' c='_ZNK10QCborArray8IteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='70' u='r' c='_ZNK10QCborArray8IteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='91' u='w' c='_ZN10QCborArray13ConstIteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='91' u='r' c='_ZN10QCborArray13ConstIteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='97' u='r' c='_ZNK10QCborArray13ConstIteratorixEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='99' u='r' c='_ZNK10QCborArray13ConstIteratoreqERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='99' u='r' c='_ZNK10QCborArray13ConstIteratoreqERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='101' u='r' c='_ZNK10QCborArray13ConstIteratorltERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='101' u='r' c='_ZNK10QCborArray13ConstIteratorltERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='102' u='r' c='_ZNK10QCborArray13ConstIteratorleERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='102' u='r' c='_ZNK10QCborArray13ConstIteratorleERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='103' u='r' c='_ZNK10QCborArray13ConstIteratorgtERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='103' u='r' c='_ZNK10QCborArray13ConstIteratorgtERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='104' u='r' c='_ZNK10QCborArray13ConstIteratorgeERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='104' u='r' c='_ZNK10QCborArray13ConstIteratorgeERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='105' u='r' c='_ZNK10QCborArray13ConstIteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='105' u='r' c='_ZNK10QCborArray13ConstIteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='107' u='r' c='_ZNK10QCborArray13ConstIteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='107' u='r' c='_ZNK10QCborArray13ConstIteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='108' u='r' c='_ZNK10QCborArray13ConstIteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='108' u='r' c='_ZNK10QCborArray13ConstIteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='109' u='r' c='_ZNK10QCborArray13ConstIteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='109' u='r' c='_ZNK10QCborArray13ConstIteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='110' u='r' c='_ZNK10QCborArray13ConstIteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='110' u='r' c='_ZNK10QCborArray13ConstIteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='111' u='w' c='_ZN10QCborArray13ConstIteratorppEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='112' u='w' c='_ZN10QCborArray13ConstIteratorppEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='113' u='w' c='_ZN10QCborArray13ConstIteratormmEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='114' u='w' c='_ZN10QCborArray13ConstIteratormmEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='115' u='w' c='_ZN10QCborArray13ConstIteratorpLEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='116' u='w' c='_ZN10QCborArray13ConstIteratormIEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='117' u='r' c='_ZNK10QCborArray13ConstIteratorplEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='118' u='r' c='_ZNK10QCborArray13ConstIteratormiEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='119' u='r' c='_ZNK10QCborArray13ConstIteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='119' u='r' c='_ZNK10QCborArray13ConstIteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='172' u='r' c='_ZN10QCborArray7extractENS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='212' u='r' c='_ZN10QCborArray6insertENS_8IteratorERK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='212' u='r' c='_ZN10QCborArray6insertENS_8IteratorERK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='214' u='r' c='_ZN10QCborArray6insertENS_13ConstIteratorERK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='214' u='r' c='_ZN10QCborArray6insertENS_13ConstIteratorERK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='215' u='r' c='_ZN10QCborArray5eraseENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='215' u='r' c='_ZN10QCborArray5eraseENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='216' u='r' c='_ZN10QCborArray5eraseENS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.h' l='216' u='r' c='_ZN10QCborArray5eraseENS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='47' u='w' c='_ZN8QCborMap8IteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='47' u='r' c='_ZN8QCborMap8IteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='51' u='r' c='_ZNK8QCborMap8IteratordeEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='60' u='r' c='_ZNK8QCborMap8Iterator3keyEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='63' u='r' c='_ZNK8QCborMap8IteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='63' u='r' c='_ZNK8QCborMap8IteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='65' u='r' c='_ZNK8QCborMap8IteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='65' u='r' c='_ZNK8QCborMap8IteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='66' u='r' c='_ZNK8QCborMap8IteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='66' u='r' c='_ZNK8QCborMap8IteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='67' u='r' c='_ZNK8QCborMap8IteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='67' u='r' c='_ZNK8QCborMap8IteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='68' u='r' c='_ZNK8QCborMap8IteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='68' u='r' c='_ZNK8QCborMap8IteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='69' u='r' c='_ZNK8QCborMap8IteratoreqERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='69' u='r' c='_ZNK8QCborMap8IteratoreqERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='71' u='r' c='_ZNK8QCborMap8IteratorltERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='71' u='r' c='_ZNK8QCborMap8IteratorltERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='72' u='r' c='_ZNK8QCborMap8IteratorleERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='72' u='r' c='_ZNK8QCborMap8IteratorleERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='73' u='r' c='_ZNK8QCborMap8IteratorgtERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='73' u='r' c='_ZNK8QCborMap8IteratorgtERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='74' u='r' c='_ZNK8QCborMap8IteratorgeERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='74' u='r' c='_ZNK8QCborMap8IteratorgeERKNS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='75' u='w' c='_ZN8QCborMap8IteratorppEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='76' u='w' c='_ZN8QCborMap8IteratorppEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='77' u='w' c='_ZN8QCborMap8IteratormmEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='78' u='w' c='_ZN8QCborMap8IteratormmEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='79' u='w' c='_ZN8QCborMap8IteratorpLEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='80' u='w' c='_ZN8QCborMap8IteratormIEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='81' u='r' c='_ZNK8QCborMap8IteratorplEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='82' u='r' c='_ZNK8QCborMap8IteratormiEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='83' u='r' c='_ZNK8QCborMap8IteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='83' u='r' c='_ZNK8QCborMap8IteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='107' u='w' c='_ZN8QCborMap13ConstIteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='107' u='r' c='_ZN8QCborMap13ConstIteratoraSERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='111' u='r' c='_ZNK8QCborMap13ConstIteratordeEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='119' u='r' c='_ZNK8QCborMap13ConstIterator3keyEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='122' u='r' c='_ZNK8QCborMap13ConstIteratoreqERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='122' u='r' c='_ZNK8QCborMap13ConstIteratoreqERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='124' u='r' c='_ZNK8QCborMap13ConstIteratorltERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='124' u='r' c='_ZNK8QCborMap13ConstIteratorltERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='125' u='r' c='_ZNK8QCborMap13ConstIteratorleERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='125' u='r' c='_ZNK8QCborMap13ConstIteratorleERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='126' u='r' c='_ZNK8QCborMap13ConstIteratorgtERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='126' u='r' c='_ZNK8QCborMap13ConstIteratorgtERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='127' u='r' c='_ZNK8QCborMap13ConstIteratorgeERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='127' u='r' c='_ZNK8QCborMap13ConstIteratorgeERKNS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='128' u='r' c='_ZNK8QCborMap13ConstIteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='128' u='r' c='_ZNK8QCborMap13ConstIteratoreqERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='130' u='r' c='_ZNK8QCborMap13ConstIteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='130' u='r' c='_ZNK8QCborMap13ConstIteratorltERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='131' u='r' c='_ZNK8QCborMap13ConstIteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='131' u='r' c='_ZNK8QCborMap13ConstIteratorleERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='132' u='r' c='_ZNK8QCborMap13ConstIteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='132' u='r' c='_ZNK8QCborMap13ConstIteratorgtERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='133' u='r' c='_ZNK8QCborMap13ConstIteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='133' u='r' c='_ZNK8QCborMap13ConstIteratorgeERKS0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='134' u='w' c='_ZN8QCborMap13ConstIteratorppEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='135' u='w' c='_ZN8QCborMap13ConstIteratorppEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='136' u='w' c='_ZN8QCborMap13ConstIteratormmEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='137' u='w' c='_ZN8QCborMap13ConstIteratormmEi'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='138' u='w' c='_ZN8QCborMap13ConstIteratorpLEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='139' u='w' c='_ZN8QCborMap13ConstIteratormIEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='140' u='r' c='_ZNK8QCborMap13ConstIteratorplEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='141' u='r' c='_ZNK8QCborMap13ConstIteratormiEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='142' u='r' c='_ZNK8QCborMap13ConstIteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='142' u='r' c='_ZNK8QCborMap13ConstIteratormiES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='252' u='r' c='_ZN8QCborMap5eraseENS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='254' u='r' c='_ZN8QCborMap7extractENS_13ConstIteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='274' u='r' c='_ZN8QCborMap6insertExRK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='280' u='r' c='_ZN8QCborMap6insertE13QLatin1StringRK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='286' u='r' c='_ZN8QCborMap6insertERK7QStringRK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.h' l='292' u='r' c='_ZN8QCborMap6insertERK10QCborValueS2_'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2294' u='r' c='_ZN21QCborContainerPrivate15findOrAddMapKeyE13QCborValueRefT_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2621' u='r' c='_ZN13QCborValueRef6assignES_RK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2626' u='r' c='_ZN13QCborValueRef6assignES_O10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2637' u='r' c='_ZN18QCborValueConstRef15concreteBooleanES_b'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2645' u='r' c='_ZN18QCborValueConstRef14concreteDoubleES_d'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2655' u='r' c='_ZN18QCborValueConstRef16concreteIntegralES_x'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2667' u='r' c='_ZN18QCborValueConstRef17concreteByteArrayES_RK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2670' u='r' c='_ZN18QCborValueConstRef17concreteByteArrayES_RK10QByteArray'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2675' u='r' c='_ZN18QCborValueConstRef14concreteStringES_RK7QString'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2678' u='r' c='_ZN18QCborValueConstRef14concreteStringES_RK7QString'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2683' u='r' c='_ZN18QCborValueConstRef8concreteES_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2688' u='r' c='_ZN18QCborValueConstRef12concreteTypeES_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2693' u='r' c='_ZNK18QCborValueConstRefixERK7QString'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2699' u='r' c='_ZNK18QCborValueConstRefixE17QLatin1StringView'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2705' u='r' c='_ZNK18QCborValueConstRefixEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.cpp' l='327' u='r' c='_ZN10QCborArray7extractENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborarray.cpp' l='328' u='r' c='_ZN10QCborArray7extractENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='794' u='r' c='_ZN8QCborMap4findEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='819' u='r' c='_ZN8QCborMap4findE17QLatin1StringView'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='844' u='r' c='_ZN8QCborMap4findERK7QString'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='869' u='r' c='_ZN8QCborMap4findERK10QCborValue'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='1049' u='r' c='_ZN8QCborMap5eraseENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='1050' u='r' c='_ZN8QCborMap5eraseENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='1066' u='r' c='_ZN8QCborMap7extractENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='1069' u='r' c='_ZN8QCborMap7extractENS_8IteratorE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcbormap.cpp' l='1070' u='r' c='_ZN8QCborMap7extractENS_8IteratorE'/>
