<dec f='qtbase-6.5.0/src/corelib/serialization/qcborstreamreader.h' l='40' type='192'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborstreamreader.h' l='99' u='r' c='_ZNK17QCborStreamReader5isTagEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborstreamreader.cpp' l='52' u='r'/>
<doc f='qtbase-6.5.0/src/corelib/serialization/qcborstreamreader.cpp' l='174'>\value Tag                   (Major type 6) Numbers giving further semantic value
                                to generic CBOR items. See \l QCborTag for more information.
   </doc>
