<dec f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.h' l='79' type='192'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.h' l='292' u='r' c='_ZN10QCborValue12isTag_helperENS_4TypeE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue_p.h' l='200' u='r' c='_ZN21QCborContainerPrivate6appendE8QCborTag'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue_p.h' l='288' u='r' c='_ZNK21QCborContainerPrivate7valueAtEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue_p.h' l='305' u='r' c='_ZN21QCborContainerPrivate9extractAtEx'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='858' u='r' c='_ZL21convertToExtendedTypeP21QCborContainerPrivate'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='910' u='r' c='_ZL9typeOrderN6QtCbor7ElementES0_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='1098' u='r' c='_ZL20compareElementNoDataRKN6QtCbor7ElementES2_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='1390' c='_ZL12encodeToCborR17QCborStreamWriterPK21QCborContainerPrivatex6QFlagsIN10QCborValue14EncodingOptionEE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='1414' u='r' c='_ZL12encodeToCborR17QCborStreamWriterPK21QCborContainerPrivatex6QFlagsIN10QCborValue14EncodingOptionEE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='1801' u='r' c='_ZN10QCborValueC1E8QCborTagRKS_'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2596' c='_ZNK10QCborValue6toCborER17QCborStreamWriter6QFlagsINS_14EncodingOptionEE'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2867' c='_Z5qHashRK10QCborValuem'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='2994' c='_ZL13debugContentsR6QDebugRK10QCborValue'/>
<doc f='qtbase-6.5.0/src/corelib/serialization/qcborvalue.cpp' l='307'>\value Tag                  An unknown or unrecognized extended type, represented by its
                                tag (a \l QCborTag) and the tagged value (a QCborValue)
    </doc>
<use f='qtbase-6.5.0/src/corelib/serialization/qjsoncbor.cpp' l='157' c='_ZL10makeStringPK21QCborContainerPrivatex14ConversionMode'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qjsoncbor.cpp' l='264' c='_Z16qt_convertToJsonP21QCborContainerPrivatex14ConversionMode'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qjsoncbor.cpp' l='389' c='_ZNK10QCborValue11toJsonValueEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qjsoncbor.cpp' l='549' c='_ZNK10QCborValue9toVariantEv'/>
<use f='qtbase-6.5.0/src/testlib/qtest.h' l='277' c='_ZN5QTest8Internal19QCborValueFormatter6formatERK10QCborValue'/>
