<dec f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='85' type='QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='94' u='m' c='_ZNK12QColorMatrix6isNullEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='99' u='m' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='100' u='m' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='101' u='m' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='111' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='112' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='113' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='116' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='118' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='118' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='118' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='120' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='120' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='121' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='121' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='m' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='139' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='140' u='m' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='m' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='m' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='148' u='m' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='152' u='m' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='153' u='m' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='154' u='m' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='196' u='r' c='_ZeqRK12QColorMatrixS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='196' u='r' c='_ZeqRK12QColorMatrixS1_'/>
<offset>0</offset>
<doc f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='84'>// We are storing the matrix transposed as that is more convenient:</doc>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='122' u='w' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='319' u='m' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='335' u='m' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='336' u='m' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='337' u='m' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='681' u='a' c='_ZN4QIcc14fromIccProfileERK10QByteArrayP11QColorSpace'/>
