<def f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='35'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='54' c='_ZN6QColorC1ENS_4SpecE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='75' c='_ZNK6QColor4specEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='167' c='_ZNK6QColor9convertToENS_4SpecE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='214'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.h' l='267' c='_ZN6QColorC1ENS_4SpecEttttt'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.cpp' l='762' c='_ZN6QColorC1ENS_4SpecE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.cpp' l='2336' c='_ZNK6QColor9convertToENS_4SpecE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolor.cpp' l='3037' c='_ZrsR11QDataStreamR6QColor'/>
<doc f='qtbase-6.5.0/src/gui/painting/qcolor.cpp' l='601'>/*!
    \enum QColor::Spec

    The type of color specified, either RGB, extended RGB, HSV, CMYK or HSL.

    \value Rgb
    \value Hsv
    \value Cmyk
    \value Hsl
    \value ExtendedRgb
    \value Invalid

    \sa spec(), convertTo()
*/</doc>
