<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='30' u='w' c='_ZN12QColorVectorC1Efff'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='32' u='w' c='_ZN12QColorVectorC1ERK7QPointF'/>
<dec f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='36' type='float'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='45' u='r' c='_ZNK12QColorVector6isNullEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='68' u='r' c='_ZeqRK12QColorVectorS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='68' u='r' c='_ZeqRK12QColorVectorS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='99' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='100' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='100' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='101' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='101' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='111' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='112' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='112' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='113' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='113' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='116' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='119' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='119' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='119' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='120' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='120' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='121' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='121' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='122' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='122' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='122' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='139' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='140' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='148' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='152' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='152' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='152' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='163' u='r' c='_ZN12QColorMatrix9fromScaleE12QColorVector'/>
<offset>0</offset>
<doc f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='36'>// X, x or red</doc>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='113' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='114' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='114' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='163' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='163' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='167' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='167' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='172' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='172' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='176' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='176' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='180' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='180' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='185' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='200' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='200' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='204' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='204' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='209' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='209' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='213' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='213' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='217' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='217' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='222' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='236' u='w' c='_ZNK15QColorTransform3mapE10QRgbaFloatI8qfloat16E'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='240' u='r' c='_ZNK15QColorTransform3mapE10QRgbaFloatI8qfloat16E'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='257' u='w' c='_ZNK15QColorTransform3mapE10QRgbaFloatIfE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='261' u='r' c='_ZNK15QColorTransform3mapE10QRgbaFloatIfE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='281' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='281' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='285' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='285' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='290' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='290' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='293' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='293' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='297' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='297' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='302' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='302' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='307' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='319' u='a' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='320' u='a' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='321' u='a' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='323' u='a' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='337' u='a' c='_ZL11applyMatrixP12QColorVectorxRK12QColorMatrix'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='455' u='a' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='492' u='a' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='495' u='a' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='496' u='w' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='496' u='r' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='548' u='a' c='_ZL19loadUnpremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='573' u='a' c='_ZL19loadUnpremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='576' u='w' c='_ZL19loadUnpremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='804' u='a' c='_ZL18storePremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='832' u='a' c='_ZL18storePremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='849' u='r' c='_ZL18storePremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='885' u='a' c='_ZL20storeUnpremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='909' u='a' c='_ZL20storeUnpremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='925' u='r' c='_ZL20storeUnpremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='941' u='a' c='_ZL11storeOpaquePT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='965' u='a' c='_ZL11storeOpaquePT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='981' u='r' c='_ZL11storeOpaquePT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='224' u='w' c='_ZN4QIccL17isValidIccProfileERK16ICCProfileHeader'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='335' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='339' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='343' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='347' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='711' u='r' c='_ZN4QIcc14fromIccProfileERK10QByteArrayP11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='720' u='r' c='_ZN4QIcc14fromIccProfileERK10QByteArrayP11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='721' u='r' c='_ZN4QIcc14fromIccProfileERK10QByteArrayP11QColorSpace'/>
