<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='30' u='w' c='_ZN12QColorVectorC1Efff'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='33' u='w' c='_ZN12QColorVectorC1ERK7QPointF'/>
<dec f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='37' type='float'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='45' u='r' c='_ZNK12QColorVector6isNullEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='69' u='r' c='_ZeqRK12QColorVectorS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='69' u='r' c='_ZeqRK12QColorVectorS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='99' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='99' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='100' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='101' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='101' u='r' c='_ZNK12QColorMatrix7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='111' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='111' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='112' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='113' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='113' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='116' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='116' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='117' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='118' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='118' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='120' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='122' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='122' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='w' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='123' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='124' u='r' c='_ZNK12QColorMatrix8invertedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='130' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='131' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='132' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='134' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='135' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='w' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='136' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='138' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='139' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='140' u='r' c='_ZNK12QColorMatrixmlERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='146' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='147' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='148' u='r' c='_ZNK12QColorMatrix3mapERK12QColorVector'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='153' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='153' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='153' u='r' c='_ZNK12QColorMatrix10transposedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='164' u='r' c='_ZN12QColorMatrix9fromScaleE12QColorVector'/>
<offset>32</offset>
<doc f='qtbase-6.5.0/src/gui/painting/qcolormatrix_p.h' l='37'>// Y, y or green</doc>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='113' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='115' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolorspace.cpp' l='115' u='r' c='_ZNK20QColorSpacePrimaries11toXyzMatrixEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='164' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='164' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='168' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='168' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='173' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='173' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='177' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='177' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='181' u='w' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='181' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='185' u='r' c='_ZNK15QColorTransform3mapEj'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='201' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='201' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='205' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='205' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='210' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='210' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='214' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='214' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='218' u='w' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='218' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='222' u='r' c='_ZNK15QColorTransform3mapE7QRgba64'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='237' u='w' c='_ZNK15QColorTransform3mapE10QRgbaFloatI8qfloat16E'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='241' u='r' c='_ZNK15QColorTransform3mapE10QRgbaFloatI8qfloat16E'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='258' u='w' c='_ZNK15QColorTransform3mapE10QRgbaFloatIfE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='262' u='r' c='_ZNK15QColorTransform3mapE10QRgbaFloatIfE'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='282' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='282' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='286' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='286' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='290' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='290' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='294' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='294' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='298' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='298' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='303' u='w' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='303' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='307' u='r' c='_ZNK15QColorTransform3mapERK6QColor'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='497' u='w' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='497' u='r' c='_ZL17loadPremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='577' u='w' c='_ZL19loadUnpremultipliedP12QColorVectorPKT_xPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='850' u='r' c='_ZL18storePremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='926' u='r' c='_ZL20storeUnpremultipliedPT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='982' u='r' c='_ZL11storeOpaquePT_PKS_PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='1199' u='r' c='_ZL9storeGrayPhPKjPK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qcolortransform.cpp' l='1207' u='r' c='_ZL9storeGrayPtPK7QRgba64PK12QColorVectorxPK22QColorTransformPrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='225' u='w' c='_ZN4QIccL17isValidIccProfileERK16ICCProfileHeader'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='336' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='340' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='344' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='348' u='r' c='_ZN4QIcc12toIccProfileERK11QColorSpace'/>
<use f='qtbase-6.5.0/src/gui/painting/qicc.cpp' l='711' u='r' c='_ZN4QIcc14fromIccProfileERK10QByteArrayP11QColorSpace'/>
