<use f='qtbase-6.5.0/src/widgets/util/qcompleter_p.h' l='115' u='w' c='_ZN17QCompletionEngineC1EP17QCompleterPrivate'/>
<dec f='qtbase-6.5.0/src/widgets/util/qcompleter_p.h' l='132' type='QCompleterPrivate *'/>
<offset>832</offset>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='400' u='r' c='_ZN17QCompletionEngine6filterERK5QListI7QStringE'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='419' u='r' c='_ZN17QCompletionEngine6filterERK5QListI7QStringE'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='434' u='r' c='_ZN17QCompletionEngine13filterHistoryEv'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='435' u='r' c='_ZN17QCompletionEngine13filterHistoryEv'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='449' u='r' c='_ZN17QCompletionEngine13filterHistoryEv'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='450' u='r' c='_ZN17QCompletionEngine13filterHistoryEv'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='450' u='r' c='_ZN17QCompletionEngine13filterHistoryEv'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='473' u='r' c='_ZNK17QCompletionEngine9matchHintERK7QStringRK11QModelIndexP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='498' u='r' c='_ZNK17QCompletionEngine11lookupCacheERK7QStringRK11QModelIndexP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='511' u='r' c='_ZN17QCompletionEngine11saveInCacheE7QStringRK11QModelIndexRK10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='535' u='r' c='_ZN17QCompletionEngine11saveInCacheE7QStringRK11QModelIndexRK10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='543' u='r' c='_ZN18QSortedModelEngine9indexHintE7QStringRK11QModelIndexN2Qt9SortOrderE'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='545' u='r' c='_ZN18QSortedModelEngine9indexHintE7QStringRK11QModelIndexN2Qt9SortOrderE'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='587' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='592' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='592' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='593' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='593' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='594' u='r' c='_ZNK18QSortedModelEngine9sortOrderERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='599' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='626' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='627' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='628' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='643' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='644' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='645' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='650' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='668' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='669' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='670' u='r' c='_ZN18QSortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='690' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='694' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='699' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='701' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='703' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='707' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='711' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='726' u='r' c='_ZN20QUnsortedModelEngine12buildIndicesERK7QStringRK11QModelIndexiRK12QIndexMapperP10QMatchData'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='741' u='r' c='_ZN20QUnsortedModelEngine14filterOnDemandEi'/>
<use f='qtbase-6.5.0/src/widgets/util/qcompleter.cpp' l='757' u='r' c='_ZN20QUnsortedModelEngine6filterERK7QStringRK11QModelIndexi'/>
