<dec f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker_p.h' l='36' type='int'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='281' u='w' c='_ZN16QCosmeticStroker5setupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='304' u='w' c='_ZN16QCosmeticStroker8clipLineERdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='308' u='w' c='_ZN16QCosmeticStroker8clipLineERdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='325' u='w' c='_ZN16QCosmeticStroker8clipLineERdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='329' u='w' c='_ZN16QCosmeticStroker8clipLineERdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='337' u='w' c='_ZN16QCosmeticStroker8clipLineERdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='353' u='w' c='_ZN16QCosmeticStroker8drawLineERK7QPointFS2_'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='397' u='w' c='_ZN16QCosmeticStroker18calculateLastPointEdddd'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='430' u='w' c='_ZN16QCosmeticStroker18calculateLastPointEdddd'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='434' u='w' c='_ZN16QCosmeticStroker18calculateLastPointEdddd'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='462' u='w' c='_ZN16QCosmeticStroker18calculateLastPointEdddd'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='466' u='w' c='_ZN16QCosmeticStroker18calculateLastPointEdddd'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='514' u='w' c='_ZN16QCosmeticStroker8drawPathERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='569' u='w' c='_ZN16QCosmeticStroker8drawPathERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='762' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='764' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='770' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='771' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='771' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='782' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='782' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='783' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='783' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='793' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='793' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='797' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='799' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='844' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='852' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='854' u='w' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='860' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='861' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='861' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='871' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='871' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='872' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='872' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='882' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='882' u='r' c='_ZL8drawLineP16QCosmeticStrokerddddi'/>
<offset>0</offset>
