<dec f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='655' type='1'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='769' u='r' c='_ZN4QCss6Parser14testCombinatorEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='786' u='r' c='_ZN4QCss6Parser9skipSpaceEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssscanner.cpp' l='164' u='r' c='_ZN21QCssScanner_Generated3lexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssscanner.cpp' l='433' u='r' c='_ZN21QCssScanner_Generated3lexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2258' u='r' c='_ZN21QCssScanner_Generated18handleCommentStartEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2329' u='r' c='_ZN4QCss6Parser5parseEPNS_10StyleSheetEN2Qt15CaseSensitivityE'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2334' u='r' c='_ZN4QCss6Parser5parseEPNS_10StyleSheetEN2Qt15CaseSensitivityE'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2340' u='r' c='_ZN4QCss6Parser5parseEPNS_10StyleSheetEN2Qt15CaseSensitivityE'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2361' u='r' c='_ZN4QCss6Parser5parseEPNS_10StyleSheetEN2Qt15CaseSensitivityE'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2481' u='r' c='_ZN4QCss6Parser15parseCombinatorEPNS_13BasicSelector8RelationE'/>
