<dec f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='695' type='30'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='759' u='r' c='_ZN4QCss6Parser15testElementNameEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser_p.h' l='784' u='r' c='_ZNK4QCss6Parser17lookupElementNameEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssscanner.cpp' l='219' u='r' c='_ZN21QCssScanner_Generated3lexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qcssparser.cpp' l='2622' c='_ZN4QCss6Parser16parseElementNameEP7QString'/>
