<dec f='qtbase-6.5.0/src/dbus/qdbusmessage_p.h' l='44' type='DBusMessage *'/>
<offset>1344</offset>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='39' u='w' c='_ZN19QDBusMessagePrivateC1Ev'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='48' u='r' c='_ZN19QDBusMessagePrivateD1Ev'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='49' u='r' c='_ZN19QDBusMessagePrivateD1Ev'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='217' u='w' c='_ZN19QDBusMessagePrivate15fromDBusMessageEP11DBusMessage6QFlagsIN15QDBusConnection20ConnectionCapabilityEE'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='451' u='r' c='_ZNK12QDBusMessage11createReplyERK5QListI8QVariantE'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='452' u='r' c='_ZNK12QDBusMessage11createReplyERK5QListI8QVariantE'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='470' u='r' c='_ZNK12QDBusMessage16createErrorReplyERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='471' u='r' c='_ZNK12QDBusMessage16createErrorReplyERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='624' u='r' c='_ZNK12QDBusMessage15isReplyRequiredEv'/>
<use f='qtbase-6.5.0/src/dbus/qdbusmessage.cpp' l='626' u='r' c='_ZNK12QDBusMessage15isReplyRequiredEv'/>
