<use f='qtbase-6.5.0/src/dbus/qdbuserror.h' l='69' u='w' c='_ZN10QDBusErrorC1EOS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.h' l='69' u='a' c='_ZN10QDBusErrorC1EOS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.h' l='80' u='m' c='_ZN10QDBusError4swapERS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.h' l='80' u='a' c='_ZN10QDBusError4swapERS_'/>
<dec f='qtbase-6.5.0/src/dbus/qdbuserror.h' l='93' type='QString'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='180' u='w' c='_ZN10QDBusErrorC1EPK9DBusError'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='196' u='w' c='_ZN10QDBusErrorC1ERK12QDBusMessage'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='208' u='w' c='_ZN10QDBusErrorC1ENS_9ErrorTypeERK7QString'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='216' u='w' c='_ZN10QDBusErrorC1ERKS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='216' u='r' c='_ZN10QDBusErrorC1ERKS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='228' u='w' c='_ZN10QDBusErroraSERKS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='228' u='r' c='_ZN10QDBusErroraSERKS_'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='243' u='w' c='_ZN10QDBusErroraSERK12QDBusMessage'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='247' u='m' c='_ZN10QDBusErroraSERK12QDBusMessage'/>
<use f='qtbase-6.5.0/src/dbus/qdbuserror.cpp' l='284' u='r' c='_ZNK10QDBusError7messageEv'/>
