<use f='qtbase-6.5.0/src/dbus/qdbusintegrator_p.h' l='122' u='w' c='_ZN17QDBusSpyCallEventC1EP22QDBusConnectionPrivateRK15QDBusConnectionRK12QDBusMessagePKPFvS7_Ei'/>
<dec f='qtbase-6.5.0/src/dbus/qdbusintegrator_p.h' l='129' type='QDBusMessage'/>
<use f='qtbase-6.5.0/src/dbus/qdbusintegrator.cpp' l='474' u='r' c='_ZN17QDBusSpyCallEventD1Ev'/>
<use f='qtbase-6.5.0/src/dbus/qdbusintegrator.cpp' l='475' u='r' c='_ZN17QDBusSpyCallEventD1Ev'/>
<use f='qtbase-6.5.0/src/dbus/qdbusintegrator.cpp' l='480' u='r' c='_ZN17QDBusSpyCallEvent13placeMetaCallEP7QObject'/>
<offset>384</offset>
