<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='44' u='w' c='_ZN6QDebug6StreamC1EP9QIODevice'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='47' u='w' c='_ZN6QDebug6StreamC1EP7QString'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='50' u='w' c='_ZN6QDebug6StreamC1E9QtMsgType'/>
<dec f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='54' type='QTextStream'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='83' u='m' c='_ZN6QDebug5spaceEv'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='85' u='m' c='_ZN6QDebug10maybeSpaceEv'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='96' u='m' c='_ZN6QDebug10maybeQuoteEc'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='99' u='m' c='_ZN6QDebuglsEb'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='100' u='m' c='_ZN6QDebuglsEc'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='101' u='m' c='_ZN6QDebuglsEs'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='102' u='m' c='_ZN6QDebuglsEt'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='105' u='m' c='_ZN6QDebuglsEi'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='106' u='m' c='_ZN6QDebuglsEj'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='107' u='m' c='_ZN6QDebuglsEl'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='108' u='m' c='_ZN6QDebuglsEm'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='109' u='m' c='_ZN6QDebuglsEx'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='110' u='m' c='_ZN6QDebuglsEy'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='111' u='a' c='_ZN6QDebuglsE8qfloat16'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='112' u='m' c='_ZN6QDebuglsEf'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='113' u='m' c='_ZN6QDebuglsEd'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='114' u='m' c='_ZN6QDebuglsEPKc'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='115' u='m' c='_ZN6QDebuglsEPKDs'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='122' u='m' c='_ZN6QDebuglsEPKv'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='123' u='m' c='_ZN6QDebuglsEDn'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='125' u='a' c='_ZN6QDebuglsEPFR11QTextStreamS1_E'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.h' l='130' u='a' c='_ZN6QDebuglsE22QTextStreamManipulator'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='182' u='m' c='_ZN6QDebug7putUcs4Ej'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='184' u='m' c='_ZN6QDebug7putUcs4Ej'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='187' u='m' c='_ZN6QDebug7putUcs4Ej'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='189' u='m' c='_ZN6QDebug7putUcs4Ej'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='190' u='a' c='_ZN6QDebug7putUcs4Ej'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='323' u='m' c='_ZN6QDebug9putStringEPK5QCharm'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='327' u='m' c='_ZN6QDebug9putStringEPK5QCharm'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='328' u='m' c='_ZN6QDebug9putStringEPK5QCharm'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='343' u='m' c='_ZN6QDebug12putByteArrayEPKcmNS_13Latin1ContentE'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='347' u='m' c='_ZN6QDebug12putByteArrayEPKcmNS_13Latin1ContentE'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='348' u='m' c='_ZN6QDebug12putByteArrayEPKcmNS_13Latin1ContentE'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='369' u='m' c='_ZN6QDebug11resetFormatEv'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='963' u='m' c='_ZN23QDebugStateSaverPrivateC1EPN6QDebug6StreamE'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='975' u='m' c='_ZN23QDebugStateSaverPrivate12restoreStateEv'/>
<use f='qtbase-6.5.0/src/corelib/io/qdebug.cpp' l='979' u='m' c='_ZN23QDebugStateSaverPrivate12restoreStateEv'/>
