<dec f='qtbase-6.5.0/src/network/kernel/qdnslookup.h' l='174' type='33'/>
<doc f='qtbase-6.5.0/src/network/kernel/qdnslookup.cpp' l='202'>\value SRV      service records.</doc>
<use f='qtbase-6.5.0/src/network/kernel/qdnslookup_unix.cpp' l='333' u='r' c='_ZN18QDnsLookupRunnable5queryEiRK10QByteArrayRK12QHostAddressP15QDnsLookupReply'/>
