<dec f='qtbase-6.5.0/src/platformsupport/input/evdevtouch/qevdevtouchfilter_p.h' l='90' type='QEvdevTouchFilter::mat2'/>
<use f='qtbase-6.5.0/src/platformsupport/input/evdevtouch/qevdevtouchfilter_p.h' l='106' u='w' c='_ZN17QEvdevTouchFilter10initializeEff'/>
<use f='qtbase-6.5.0/src/platformsupport/input/evdevtouch/qevdevtouchfilter_p.h' l='118' u='r' c='_ZN17QEvdevTouchFilter6updateEfff'/>
<offset>320</offset>
