<dec f='qtbase-6.5.0/src/corelib/kernel/qcoreevent.h' l='72' type='13'/>
<doc f='qtbase-6.5.0/src/corelib/kernel/qcoreevent.h' l='72'>// move widget</doc>
<doc f='qtbase-6.5.0/src/corelib/kernel/qcoreevent.cpp' l='155'>\value Move                             Widget&apos;s position changed (QMoveEvent).
    </doc>
<use f='qtbase-6.5.0/src/gui/kernel/qevent.cpp' l='1672' u='r' c='_ZN10QMoveEventC1ERK6QPointS2_'/>
<use f='qtbase-6.5.0/src/gui/kernel/qevent.cpp' l='3855' c='_ZL14eventClassNameN6QEvent4TypeE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qevent.cpp' l='4136' c='_Zls6QDebugPK6QEvent'/>
<use f='qtbase-6.5.0/src/gui/kernel/qwindow.cpp' l='2427' c='_ZN7QWindow5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/graphicsview/qgraphicsproxywidget.cpp' l='920' c='_ZN20QGraphicsProxyWidget11eventFilterEP7QObjectP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qapplication.cpp' l='792' c='_ZN12QApplication13compressEventEP6QEventP7QObjectP14QPostEventList'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qapplication.cpp' l='814' c='_ZN12QApplication13compressEventEP6QEventP7QObjectP14QPostEventList'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidget.cpp' l='9070' c='_ZN7QWidget5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidgetwindow.cpp' l='258' c='_ZN13QWidgetWindow5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwindowcontainer.cpp' l='280' c='_ZN16QWindowContainer5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qdockwidget.cpp' l='1622' c='_ZN11QDockWidget5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qeffects.cpp' l='156' c='_ZN12QAlphaWidget11eventFilterEP7QObjectP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qeffects.cpp' l='534' u='r' c='_Z13qScrollEffectP7QWidgetji'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qeffects.cpp' l='556' u='r' c='_Z11qFadeEffectP7QWidgeti'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qfocusframe.cpp' l='248' c='_ZN11QFocusFrame11eventFilterEP7QObjectP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qfocusframe.cpp' l='287' c='_ZN11QFocusFrame11eventFilterEP7QObjectP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qfocusframe.cpp' l='307' c='_ZN11QFocusFrame5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmainwindowlayout.cpp' l='268' c='_ZN22QDockWidgetGroupWindow5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2570' c='_ZN8QMdiArea11eventFilterEP7QObjectP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtabbar.cpp' l='1734' c='_ZN7QTabBar5eventEP6QEvent'/>
