<dec f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='146' type='QFixed'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='148' u='w' c='_ZN11QFixedPointC1E6QFixedS0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='149' u='m' c='_ZNK11QFixedPoint8toPointFEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='155' u='r' c='_ZNK11QFixedPointeqERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='155' u='r' c='_ZNK11QFixedPointeqERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='161' u='m' c='_ZmiRK11QFixedPointS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='161' u='r' c='_ZmiRK11QFixedPointS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='163' u='m' c='_ZplRK11QFixedPointS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qfixed_p.h' l='163' u='r' c='_ZplRK11QFixedPointS1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qtextureglyphcache_p.h' l='135' u='m' c='_Z5qHashRKN18QTextureGlyphCache24GlyphAndSubPixelPositionEm'/>
<offset>32</offset>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine.cpp' l='735' u='m' c='_ZN12QPaintEngine12drawTextItemERK7QPointFRK9QTextItem'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2785' u='w' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2811' u='r' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2812' u='r' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2850' u='w' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2859' u='r' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2860' u='r' c='_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3014' u='r' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3025' u='r' c='_ZL17visibleGlyphRangeRK6QRectFP11QFontEnginePjP11QFixedPointi'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainter.cpp' l='5532' u='w' c='_ZN8QPainter14drawStaticTextERK7QPointFRK11QStaticText'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainter.cpp' l='6072' u='r' c='_ZL29qt_draw_decoration_for_glyphsP8QPainterRK7QPointFPKjPK11QFixedPointiP11QFontEnginebbb'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='3133' u='m' c='_ZN17QPdfEnginePrivate12drawTextItemERK7QPointFRK12QTextItemInt'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='3153' u='m' c='_ZN17QPdfEnginePrivate12drawTextItemERK7QPointFRK12QTextItemInt'/>
<use f='qtbase-6.5.0/src/gui/painting/qtextureglyphcache.cpp' l='108' u='m' c='_ZN18QTextureGlyphCache8populateEP11QFontEnginexPKjPK11QFixedPoint6QFlagsIN8QPainter10RenderHintEEb'/>
<use f='qtbase-6.5.0/src/gui/painting/qtextureglyphcache.cpp' l='112' u='w' c='_ZN18QTextureGlyphCache8populateEP11QFontEnginexPKjPK11QFixedPoint6QFlagsIN8QPainter10RenderHintEEb'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft_p.h' l='132' u='r' c='_ZNK13QFontEngineFT9QGlyphSet16useFastGlyphDataEjRK11QFixedPoint'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft_p.h' l='336' u='m' c='_Z5qHashRKN13QFontEngineFT24GlyphAndSubPixelPositionEm'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1009' u='m' c='_ZNK13QFontEngineFT9loadGlyphEPNS_9QGlyphSetEjRK11QFixedPointN11QFontEngine11GlyphFormatEbb'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1464' u='w' c='_ZN13QFontEngineFT16getUnscaledGlyphEjP12QPainterPathP15glyph_metrics_t'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1743' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/freetype/qfontengine_ft.cpp' l='1757' u='r' c='_ZN13QFontEngineFT11boundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='292' u='r' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='300' u='w' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='319' u='r' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='327' u='w' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='344' u='w' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='344' u='r' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='355' u='r' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='359' u='w' c='_ZN11QFontEngine17getGlyphPositionsERK12QGlyphLayoutRK10QTransform6QFlagsIN9QTextItem10RenderFlagEER15QVarLengthArrayIjLx256EERSA_I11QFixedPointLx256EE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='594' u='r' c='_ZN11QFontEngine16tightBoundingBoxERK12QGlyphLayout'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='759' u='r' c='_ZN11QFontEngine19addBitmapFontToPathEddRK12QGlyphLayoutP12QPainterPath6QFlagsIN9QTextItem10RenderFlagEE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='769' u='m' c='_ZN11QFontEngine15addGlyphsToPathEPjP11QFixedPointiP12QPainterPath6QFlagsIN9QTextItem10RenderFlagEE'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='852' u='r' c='_ZNK11QFontEngine19subPixelPositionForERK11QFixedPoint'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='875' u='w' c='_ZN11QFontEngine16alphaMapForGlyphEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfontengine.cpp' l='926' u='w' c='_ZN11QFontEngine16getUnscaledGlyphEjP12QPainterPathP15glyph_metrics_t'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='638' u='m' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextFrameRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='638' u='r' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextFrameRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='645' u='r' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextFrameRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='649' u='r' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextFrameRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='708' u='r' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextFrameRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='760' u='r' c='_ZNK26QTextDocumentLayoutPrivate7hitTestEP10QTextTableRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='799' u='m' c='_ZNK26QTextDocumentLayoutPrivate7hitTestERK10QTextBlockRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='802' u='m' c='_ZNK26QTextDocumentLayoutPrivate7hitTestERK10QTextBlockRK11QFixedPointPiPP11QTextLayoutN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='1095' u='r' c='_ZNK26QTextDocumentLayoutPrivate9drawFrameERK7QPointFP8QPainterRKN27QAbstractTextDocumentLayout12PaintContextEP10QTextFrame'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='1098' u='r' c='_ZNK26QTextDocumentLayoutPrivate9drawFrameERK7QPointFP8QPainterRKN27QAbstractTextDocumentLayout12PaintContextEP10QTextFrame'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2238' u='r' c='_ZL12flowPositionRKN10QTextFrame8iteratorE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2326' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutCellEP10QTextTableRK14QTextTableCell6QFixediiP14QTextTableDataS5_b'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2425' u='r' c='_ZN26QTextDocumentLayoutPrivate11layoutTableEP10QTextTableii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2872' u='w' c='_ZN26QTextDocumentLayoutPrivate13positionFloatEP10QTextFrameP9QTextLine'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2875' u='w' c='_ZN26QTextDocumentLayoutPrivate13positionFloatEP10QTextFrameP9QTextLine'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='2997' u='r' c='_ZN26QTextDocumentLayoutPrivate11layoutFrameEP10QTextFrameii6QFixedS2_S2_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3190' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3190' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3196' u='w' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3300' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3326' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3354' u='m' c='_ZN26QTextDocumentLayoutPrivate10layoutFlowEN10QTextFrame8iteratorEP17QTextLayoutStructii6QFixed'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3643' u='r' c='_ZNK26QTextDocumentLayoutPrivate12floatMarginsE6QFixedPK17QTextLayoutStructPS0_S4_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3643' u='m' c='_ZNK26QTextDocumentLayoutPrivate12floatMarginsE6QFixedPK17QTextLayoutStructPS0_S4_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3673' u='r' c='_ZNK26QTextDocumentLayoutPrivate5findYE6QFixedPK17QTextLayoutStructS0_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3673' u='m' c='_ZNK26QTextDocumentLayoutPrivate5findYE6QFixedPK17QTextLayoutStructS0_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3674' u='m' c='_ZNK26QTextDocumentLayoutPrivate5findYE6QFixedPK17QTextLayoutStructS0_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocumentlayout.cpp' l='3844' u='w' c='_ZNK19QTextDocumentLayout7hitTestERK7QPointFN2Qt15HitTestAccuracyE'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='1704' u='w' c='_ZNK11QTextEngine23shapeTextWithHarfbuzzNGERK11QScriptItemPKtiP11QFontEngineRK5QListIjEbb'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='1726' u='w' c='_ZNK11QTextEngine23shapeTextWithHarfbuzzNGERK11QScriptItemPKtiP11QFontEngineRK5QListIjEbb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1880' u='w' c='_ZN28QOpenGL2PaintEngineExPrivate16drawCachedGlyphsEN11QFontEngine11GlyphFormatEP15QStaticTextItem'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1891' u='m' c='_ZN28QOpenGL2PaintEngineExPrivate16drawCachedGlyphsEN11QFontEngine11GlyphFormatEP15QStaticTextItem'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1892' u='m' c='_ZN28QOpenGL2PaintEngineExPrivate16drawCachedGlyphsEN11QFontEngine11GlyphFormatEP15QStaticTextItem'/>
