<dec f='qtbase-6.5.0/src/gui/painting/qstroker_p.h' l='69' type='qfixed'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker_p.h' l='71' u='r' c='_ZN8qfixed2d8isFiniteEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker_p.h' l='73' u='r' c='_ZNK8qfixed2deqERKS_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker_p.h' l='73' u='r' c='_ZNK8qfixed2deqERKS_'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='631' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='641' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='647' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='668' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='684' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='694' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='721' u='r' c='_Z14qt_stroke_sidePT_P8QStrokerbP6QLineF'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1026' u='r' c='_ZL22lineRectIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1034' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1034' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1037' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1037' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1041' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1041' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1044' u='w' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1044' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1044' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1045' u='w' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1045' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1045' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1048' u='w' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1048' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1048' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1049' u='w' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1049' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1049' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1059' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1059' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1060' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1060' u='r' c='_ZL18lineIntersectsRect8qfixed2dS_RKS_S1_'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1139' u='r' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1178' u='r' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1212' u='w' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1222' u='r' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1226' u='r' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='1233' u='w' c='_ZN12QDashStroker21processCurrentSubpathEv'/>
