<dec f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='41' type='0'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='369' u='r' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='371' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='377' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='380' u='r' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='391' u='r' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='397' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='400' u='r' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='411' u='r' c='_ZN16QFragmentMapData9rebalanceEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='531' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='535' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='537' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='543' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='550' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='563' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='565' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='571' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
<use f='qtbase-6.5.0/src/gui/text/qfragmentmap_p.h' l='578' u='r' c='_ZN16QFragmentMapData12erase_singleEj'/>
