<dec f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='102' type='int'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='417' u='w' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='423' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='483' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='484' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='490' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='536' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='537' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='540' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='547' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='549' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='550' u='r' c='_ZN10QGIFFormat6decodeEP6QImagePKhiPiS4_'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='941' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='945' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='949' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='949' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='959' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='960' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='961' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='962' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='964' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='965' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='967' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='974' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='978' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='978' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='986' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='987' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='988' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='990' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='992' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='998' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1002' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1002' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1009' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1010' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1010' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1016' u='w' c='_ZN10QGIFFormat5nextYEPhi'/>
<use f='qtbase-6.5.0/src/plugins/imageformats/gif/qgifhandler.cpp' l='1020' u='r' c='_ZN10QGIFFormat5nextYEPhi'/>
<offset>1920</offset>
