<def f='qtbase-6.5.0/src/gui/rhi/qrhigles2_p_p.h' l='310' ll='521'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2_p_p.h' l='529'/>
<size>104</size>
<mbr r='QGles2CommandBuffer::Command::cmd' o='0' t='QGles2CommandBuffer::Command::Cmd'/>
<mbr r='QGles2CommandBuffer::Command::args' o='64' t='union Args'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1590' c='_ZN9QRhiGles219setGraphicsPipelineEP17QRhiCommandBufferP20QRhiGraphicsPipeline'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1701' c='_ZN9QRhiGles218setShaderResourcesEP17QRhiCommandBufferP26QRhiShaderResourceBindingsiPKSt4pairIijE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1738' c='_ZN9QRhiGles214setVertexInputEP17QRhiCommandBufferiiPKSt4pairIP10QRhiBufferjES4_jNS0_11IndexFormatE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1755' c='_ZN9QRhiGles214setVertexInputEP17QRhiCommandBufferiiPKSt4pairIP10QRhiBufferjES4_jNS0_11IndexFormatE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1778' c='_ZN9QRhiGles211setViewportEP17QRhiCommandBufferRK12QRhiViewport'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1798' c='_ZN9QRhiGles210setScissorEP17QRhiCommandBufferRK11QRhiScissor'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1811' c='_ZN9QRhiGles217setBlendConstantsEP17QRhiCommandBufferRK6QColor'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1824' c='_ZN9QRhiGles213setStencilRefEP17QRhiCommandBufferj'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1836' c='_ZN9QRhiGles24drawEP17QRhiCommandBufferjjjj'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1851' c='_ZN9QRhiGles211drawIndexedEP17QRhiCommandBufferjjjij'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1895' c='_ZL18addBoundaryCommandP19QGles2CommandBufferNS_7Command3CmdE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1916' c='_ZN9QRhiGles213beginExternalEP17QRhiCommandBuffer'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2115' c='_ZN9QRhiGles220trackedBufferBarrierEP19QGles2CommandBufferP12QGles2BufferNS2_6AccessE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2134' c='_ZN9QRhiGles219trackedImageBarrierEP19QGles2CommandBufferP13QGles2TextureNS2_6AccessE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2158' c='_ZN9QRhiGles219enqueueSubresUploadEP13QGles2TextureP19QGles2CommandBufferiiRK39QRhiTextureSubresourceUploadDescription'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2196' c='_ZN9QRhiGles219enqueueSubresUploadEP13QGles2TextureP19QGles2CommandBufferiiRK39QRhiTextureSubresourceUploadDescription'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2215' c='_ZN9QRhiGles219enqueueSubresUploadEP13QGles2TextureP19QGles2CommandBufferiiRK39QRhiTextureSubresourceUploadDescription'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2230' c='_ZN9QRhiGles219enqueueSubresUploadEP13QGles2TextureP19QGles2CommandBufferiiRK39QRhiTextureSubresourceUploadDescription'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2249' c='_ZN9QRhiGles219enqueueSubresUploadEP13QGles2TextureP19QGles2CommandBufferiiRK39QRhiTextureSubresourceUploadDescription'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2290' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2306' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2322' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2363' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2390' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2418' c='_ZN9QRhiGles222enqueueResourceUpdatesEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='2786' c='_ZN9QRhiGles220executeCommandBufferEP17QRhiCommandBuffer'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4071' c='_ZN9QRhiGles222enqueueBindFramebufferEP16QRhiRenderTargetP19QGles2CommandBufferPbS4_'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4142' c='_ZN9QRhiGles222enqueueBarriersForPassEP19QGles2CommandBuffer'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4173' c='_ZN9QRhiGles29beginPassEP17QRhiCommandBufferP16QRhiRenderTargetRK6QColorRK26QRhiDepthStencilClearValueP23QRhiResourceUpdateBatch6QFlagsINS0_13BeginPassFlagEE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4212' c='_ZN9QRhiGles27endPassEP17QRhiCommandBufferP23QRhiResourceUpdateBatch'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4278' c='_ZN9QRhiGles218setComputePipelineEP17QRhiCommandBufferP19QRhiComputePipeline'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4367' c='_ZN9QRhiGles28dispatchEP17QRhiCommandBufferiii'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4373' c='_ZN9QRhiGles28dispatchEP17QRhiCommandBufferiii'/>
<size>104</size>
