<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication_p.h' l='180' u='r' c='_ZN22QGuiApplicationPrivate8instanceEv'/>
<dec f='qtbase-6.5.0/src/gui/kernel/qguiapplication_p.h' l='340' type='QGuiApplicationPrivate *'/>
<def f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='166' type='QGuiApplicationPrivate *'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='702' u='w' c='_ZN22QGuiApplicationPrivateC1ERiPPc'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='813' u='r' c='_ZN15QGuiApplication11modalWindowEv'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='815' u='r' c='_ZN15QGuiApplication11modalWindowEv'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='836' u='r' c='_ZN22QGuiApplicationPrivate19updateBlockedStatusEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='837' u='r' c='_ZN22QGuiApplicationPrivate19updateBlockedStatusEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='851' u='r' c='_ZN22QGuiApplicationPrivate15showModalWindowEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='855' u='r' c='_ZN22QGuiApplicationPrivate15showModalWindowEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='858' u='r' c='_ZN22QGuiApplicationPrivate15showModalWindowEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='862' u='r' c='_ZN22QGuiApplicationPrivate15showModalWindowEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='876' u='r' c='_ZN22QGuiApplicationPrivate15hideModalWindowEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='1751' u='w' c='_ZN22QGuiApplicationPrivateD1Ev'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2514' u='r' c='_ZN22QGuiApplicationPrivate21processActivatedEventEPN29QWindowSystemInterfacePrivate20ActivatedWindowEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2515' u='r' c='_ZN22QGuiApplicationPrivate21processActivatedEventEPN29QWindowSystemInterfacePrivate20ActivatedWindowEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2524' u='r' c='_ZN22QGuiApplicationPrivate21processActivatedEventEPN29QWindowSystemInterfacePrivate20ActivatedWindowEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2590' u='r' c='_ZN22QGuiApplicationPrivate19processThemeChangedEPN29QWindowSystemInterfacePrivate16ThemeChangeEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2591' u='r' c='_ZN22QGuiApplicationPrivate19processThemeChangedEPN29QWindowSystemInterfacePrivate16ThemeChangeEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2893' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2894' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2895' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2912' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2914' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2919' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='2922' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3064' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3085' u='r' c='_ZN22QGuiApplicationPrivate17processTouchEventEPN29QWindowSystemInterfacePrivate10TouchEventE'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3488' u='r' c='_ZN15QGuiApplication4fontEv'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3561' u='r' c='_ZN22QGuiApplicationPrivate24notifyActiveWindowChangeEP7QWindow'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3587' u='r' c='_ZN15QGuiApplication13setWindowIconERK5QIcon'/>
<use f='qtbase-6.5.0/src/gui/kernel/qguiapplication.cpp' l='3972' u='r' c='_ZN15QGuiApplication18setLayoutDirectionEN2Qt15LayoutDirectionE'/>
