<dec f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate_p.h' l='56' type='bool'/>
<use f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate.cpp' l='186' u='w' c='_ZN19QHttpThreadDelegateC1EP7QObject'/>
<use f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate.cpp' l='247' u='r' c='_ZN19QHttpThreadDelegate12startRequestEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate.cpp' l='258' u='r' c='_ZN19QHttpThreadDelegate12startRequestEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate.cpp' l='300' u='r' c='_ZN19QHttpThreadDelegate12startRequestEv'/>
<offset>128</offset>
<doc f='qtbase-6.5.0/src/network/access/qhttpthreaddelegate_p.h' l='55'>// incoming</doc>
<use f='qtbase-6.5.0/src/network/access/qnetworkreplyhttpimpl.cpp' l='814' u='w' c='_ZN28QNetworkReplyHttpImplPrivate11postRequestERK15QNetworkRequest'/>
