<dec f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel_p.h' l='74' type='bool'/>
<offset>192</offset>
<use f='qtbase-6.5.0/src/network/access/qhttp2protocolhandler.cpp' l='152' u='r' c='_ZN21QHttp2ProtocolHandlerC1EP29QHttpNetworkConnectionChannel'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnection.cpp' l='110' u='w' c='_ZN29QHttpNetworkConnectionPrivate4initEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='52' u='w' c='_ZN29QHttpNetworkConnectionChannelC1Ev'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='296' u='r' c='_ZN29QHttpNetworkConnectionChannel16ensureConnectionEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='334' u='r' c='_ZN29QHttpNetworkConnectionChannel16ensureConnectionEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='362' u='r' c='_ZN29QHttpNetworkConnectionChannel16ensureConnectionEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='436' u='r' c='_ZN29QHttpNetworkConnectionChannel7allDoneEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='801' u='r' c='_ZN29QHttpNetworkConnectionChannel15_q_bytesWrittenEx'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkconnectionchannel.cpp' l='899' u='r' c='_ZN29QHttpNetworkConnectionChannel12_q_connectedEv'/>
