<dec f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest_p.h' l='151' type='bool'/>
<offset>1264</offset>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='32' u='w' c='_ZN26QHttpNetworkRequestPrivateC1ERKS_'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='32' u='r' c='_ZN26QHttpNetworkRequestPrivateC1ERKS_'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='59' u='r' c='_ZNK26QHttpNetworkRequestPrivateeqERKS_'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='59' u='r' c='_ZNK26QHttpNetworkRequestPrivateeqERKS_'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='189' u='r' c='_ZNK19QHttpNetworkRequest5isSslEv'/>
<use f='qtbase-6.5.0/src/network/access/qhttpnetworkrequest.cpp' l='193' u='w' c='_ZN19QHttpNetworkRequest6setSslEb'/>
