<dec f='qtbase-6.5.0/src/gui/kernel/qinputmethod.h' l='49' type='0'/>
<doc f='qtbase-6.5.0/src/gui/kernel/qinputmethod.cpp' l='338'>\value Click        A normal click/tap
    </doc>
<use f='qtbase-6.5.0/src/gui/kernel/qplatforminputcontext.cpp' l='107' u='r' c='_ZN21QPlatformInputContext12invokeActionEN12QInputMethod6ActionEi'/>
<use f='qtbase-6.5.0/src/plugins/platforminputcontexts/ibus/qibusplatforminputcontext.cpp' l='147' u='r' c='_ZN25QIBusPlatformInputContext12invokeActionEN12QInputMethod6ActionEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='287' u='r' c='_ZN16QLineEditPrivate28sendMouseEventToInputContextEP11QMouseEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgettextcontrol.cpp' l='1919' u='r' c='_ZN25QWidgetTextControlPrivate28sendMouseEventToInputContextEP6QEventNS0_4TypeEN2Qt11MouseButtonERK7QPointF6QFlagsINS3_16KeyboardModifierEES8_IS4_ERK6QPoint'/>
