<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='22' u='w' c='_ZN19QItemSelectionRangeC1ERK11QModelIndexS2_'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='23' u='w' c='_ZN19QItemSelectionRangeC1ERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='23' u='r' c='_ZN19QItemSelectionRangeC1ERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='27' u='m' c='_ZN19QItemSelectionRange4swapERS_'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='27' u='a' c='_ZN19QItemSelectionRange4swapERS_'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='31' u='m' c='_ZNK19QItemSelectionRange3topEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='32' u='m' c='_ZNK19QItemSelectionRange4leftEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='35' u='m' c='_ZNK19QItemSelectionRange5widthEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='36' u='m' c='_ZNK19QItemSelectionRange6heightEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='38' u='a' c='_ZNK19QItemSelectionRange7topLeftEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='40' u='m' c='_ZNK19QItemSelectionRange6parentEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='41' u='m' c='_ZNK19QItemSelectionRange5modelEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='46' u='m' c='_ZNK19QItemSelectionRange8containsERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='46' u='m' c='_ZNK19QItemSelectionRange8containsERK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='53' u='m' c='_ZNK19QItemSelectionRange8containsEiiRK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='53' u='m' c='_ZNK19QItemSelectionRange8containsEiiRK11QModelIndex'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='62' u='m' c='_ZNK19QItemSelectionRangeeqERKS_'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='62' u='r' c='_ZNK19QItemSelectionRangeeqERKS_'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='68' u='m' c='_ZNK19QItemSelectionRange7isValidEv'/>
<use f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='68' u='m' c='_ZNK19QItemSelectionRange7isValidEv'/>
<dec f='qtbase-6.5.0/src/corelib/itemmodels/qitemselectionmodel.h' l='77' type='QPersistentModelIndex'/>
<offset>0</offset>
