<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.h' l='107' u='w' c='_ZN16QLineEditPrivate15SideWidgetEntryC1EP7QWidgetP7QActioni'/>
<dec f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.h' l='110' type='QAction *'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='495' u='r' c='_ZN16QLineEditPrivate21setClearButtonEnabledEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='516' u='r' c='_ZN16QLineEditPrivate19positionSideWidgetsEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='526' u='r' c='_ZN16QLineEditPrivate19positionSideWidgetsEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='538' u='r' c='_ZNK16QLineEditPrivate14findSideWidgetEPK7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='544' u='r' c='_ZNK16QLineEditPrivate14findSideWidgetEPK7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='592' u='r' c='_ZN16QLineEditPrivate9addActionEP7QActionS1_N9QLineEdit14ActionPositionEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qlineedit_p.cpp' l='631' u='r' c='_ZN16QLineEditPrivate12removeActionEP7QAction'/>
