<dec f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow_p.h' l='95' type='1'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow_p.h' l='304' u='r' c='_ZNK20QMdiSubWindowPrivate17isResizeOperationEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow_p.h' l='309' u='r' c='_ZNK20QMdiSubWindowPrivate15isMoveOperationEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='921' u='r' c='_ZN20QMdiSubWindowPrivate23_q_enterInteractiveModeEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='943' u='r' c='_ZN20QMdiSubWindowPrivate23_q_enterInteractiveModeEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='1018' u='r' c='_ZN20QMdiSubWindowPrivate16initOperationMapEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='1081' u='r' c='_ZN20QMdiSubWindowPrivate12updateCursorEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='1171' u='r' c='_ZN20QMdiSubWindowPrivate14setNewGeometryERK6QPoint'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='1175' u='r' c='_ZN20QMdiSubWindowPrivate14setNewGeometryERK6QPoint'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='1546' u='r' c='_ZNK20QMdiSubWindowPrivate9getRegionENS_9OperationE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdisubwindow.cpp' l='3408' u='r' c='_ZN13QMdiSubWindow16contextMenuEventEP17QContextMenuEvent'/>
