<use f='qtbase-6.5.0/src/widgets/widgets/qmenu_p.h' l='344' u='r' c='_ZN12QMenuPrivate10DelayState5startEiP7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu_p.h' l='346' u='w' c='_ZN12QMenuPrivate10DelayState5startEiP7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu_p.h' l='351' u='w' c='_ZN12QMenuPrivate10DelayState4stopEv'/>
<dec f='qtbase-6.5.0/src/widgets/widgets/qmenu_p.h' l='356' type='QAction *'/>
<offset>64</offset>
