<dec f='qtbase-6.5.0/src/opengl/qopenglversionfunctions.h' l='91' type='QOpenGLFunctions_4_2_CoreBackend::Functions'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3340' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3345' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3350' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3355' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3360' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3365' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3370' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3375' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3380' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3385' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3390' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='3395' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2670' u='m' c='_ZN25QOpenGLFunctions_4_2_Core14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2675' u='m' c='_ZN25QOpenGLFunctions_4_2_Core14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2680' u='m' c='_ZN25QOpenGLFunctions_4_2_Core14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2685' u='m' c='_ZN25QOpenGLFunctions_4_2_Core15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2690' u='m' c='_ZN25QOpenGLFunctions_4_2_Core18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2695' u='m' c='_ZN25QOpenGLFunctions_4_2_Core32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2700' u='m' c='_ZN25QOpenGLFunctions_4_2_Core21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2705' u='m' c='_ZN25QOpenGLFunctions_4_2_Core38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2710' u='m' c='_ZN25QOpenGLFunctions_4_2_Core32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2715' u='m' c='_ZN25QOpenGLFunctions_4_2_Core45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2720' u='m' c='_ZN25QOpenGLFunctions_4_2_Core35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='2725' u='m' c='_ZN25QOpenGLFunctions_4_2_Core33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3378' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3383' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3388' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3393' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3398' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3403' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3408' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3413' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3418' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3423' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3428' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3433' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2707' u='m' c='_ZN25QOpenGLFunctions_4_3_Core14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2712' u='m' c='_ZN25QOpenGLFunctions_4_3_Core14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2717' u='m' c='_ZN25QOpenGLFunctions_4_3_Core14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2722' u='m' c='_ZN25QOpenGLFunctions_4_3_Core15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2727' u='m' c='_ZN25QOpenGLFunctions_4_3_Core18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2732' u='m' c='_ZN25QOpenGLFunctions_4_3_Core32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2737' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2742' u='m' c='_ZN25QOpenGLFunctions_4_3_Core38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2747' u='m' c='_ZN25QOpenGLFunctions_4_3_Core32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2752' u='m' c='_ZN25QOpenGLFunctions_4_3_Core45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2757' u='m' c='_ZN25QOpenGLFunctions_4_3_Core35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2762' u='m' c='_ZN25QOpenGLFunctions_4_3_Core33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3516' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3521' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3526' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3531' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3536' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3541' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3546' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3551' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3556' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3561' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3566' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3571' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3064' u='m' c='_ZN25QOpenGLFunctions_4_4_Core38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3069' u='m' c='_ZN25QOpenGLFunctions_4_4_Core32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3074' u='m' c='_ZN25QOpenGLFunctions_4_4_Core14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3079' u='m' c='_ZN25QOpenGLFunctions_4_4_Core14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3084' u='m' c='_ZN25QOpenGLFunctions_4_4_Core14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3089' u='m' c='_ZN25QOpenGLFunctions_4_4_Core15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3094' u='m' c='_ZN25QOpenGLFunctions_4_4_Core18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3099' u='m' c='_ZN25QOpenGLFunctions_4_4_Core32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3104' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3109' u='m' c='_ZN25QOpenGLFunctions_4_4_Core45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3114' u='m' c='_ZN25QOpenGLFunctions_4_4_Core35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3119' u='m' c='_ZN25QOpenGLFunctions_4_4_Core33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3640' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3645' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3650' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3655' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3660' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3665' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3670' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3675' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3680' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3685' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3690' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3695' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility33glDrawArraysInstancedBaseInstanceEjiiij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3173' u='m' c='_ZN25QOpenGLFunctions_4_5_Core38glDrawTransformFeedbackStreamInstancedEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3178' u='m' c='_ZN25QOpenGLFunctions_4_5_Core32glDrawTransformFeedbackInstancedEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3183' u='m' c='_ZN25QOpenGLFunctions_4_5_Core14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3188' u='m' c='_ZN25QOpenGLFunctions_4_5_Core14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3193' u='m' c='_ZN25QOpenGLFunctions_4_5_Core14glTexStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3198' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3203' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3208' u='m' c='_ZN25QOpenGLFunctions_4_5_Core32glGetActiveAtomicCounterBufferivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3213' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3218' u='m' c='_ZN25QOpenGLFunctions_4_5_Core45glDrawElementsInstancedBaseVertexBaseInstanceEjijPKviij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3223' u='m' c='_ZN25QOpenGLFunctions_4_5_Core35glDrawElementsInstancedBaseInstanceEjijPKvij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3228' u='m' c='_ZN25QOpenGLFunctions_4_5_Core33glDrawArraysInstancedBaseInstanceEjiiij'/>
