<dec f='qtbase-6.5.0/src/opengl/qopengltexture.h' l='262' type='6403'/>
<doc f='qtbase-6.5.0/src/opengl/qopengltexture.h' l='262'>// GL_RED</doc>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='490' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='502' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='514' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='526' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='610' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='622' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='690' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<doc f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='2317'>\value Red Equivalent to GL_RED
    </doc>
