<dec f='qtbase-6.5.0/src/opengl/qopenglversionfunctions.h' l='91' type='QOpenGLFunctions_3_1_CoreBackend::Functions'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1481' u='m' c='_ZN20QOpenGLFunctions_3_119glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1486' u='m' c='_ZN20QOpenGLFunctions_3_121glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1491' u='m' c='_ZN20QOpenGLFunctions_3_127glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1496' u='m' c='_ZN20QOpenGLFunctions_3_125glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1501' u='m' c='_ZN20QOpenGLFunctions_3_122glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1506' u='m' c='_ZN20QOpenGLFunctions_3_122glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1511' u='m' c='_ZN20QOpenGLFunctions_3_121glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1516' u='m' c='_ZN20QOpenGLFunctions_3_119glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1521' u='m' c='_ZN20QOpenGLFunctions_3_123glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1526' u='m' c='_ZN20QOpenGLFunctions_3_111glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1531' u='m' c='_ZN20QOpenGLFunctions_3_123glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_1.h' l='1536' u='m' c='_ZN20QOpenGLFunctions_3_121glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='1985' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='1990' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='1995' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2000' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2005' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2010' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2015' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2020' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2025' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2030' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2035' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_compatibility.h' l='2040' u='m' c='_ZN34QOpenGLFunctions_3_2_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1503' u='m' c='_ZN25QOpenGLFunctions_3_2_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1508' u='m' c='_ZN25QOpenGLFunctions_3_2_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1513' u='m' c='_ZN25QOpenGLFunctions_3_2_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1518' u='m' c='_ZN25QOpenGLFunctions_3_2_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1523' u='m' c='_ZN25QOpenGLFunctions_3_2_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1528' u='m' c='_ZN25QOpenGLFunctions_3_2_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1533' u='m' c='_ZN25QOpenGLFunctions_3_2_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1538' u='m' c='_ZN25QOpenGLFunctions_3_2_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1543' u='m' c='_ZN25QOpenGLFunctions_3_2_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1548' u='m' c='_ZN25QOpenGLFunctions_3_2_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1553' u='m' c='_ZN25QOpenGLFunctions_3_2_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_2_core.h' l='1558' u='m' c='_ZN25QOpenGLFunctions_3_2_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2048' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2053' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2058' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2063' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2068' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2073' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2078' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2083' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2088' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2093' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2098' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_compatibility.h' l='2103' u='m' c='_ZN34QOpenGLFunctions_3_3_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1534' u='m' c='_ZN25QOpenGLFunctions_3_3_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1539' u='m' c='_ZN25QOpenGLFunctions_3_3_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1544' u='m' c='_ZN25QOpenGLFunctions_3_3_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1549' u='m' c='_ZN25QOpenGLFunctions_3_3_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1554' u='m' c='_ZN25QOpenGLFunctions_3_3_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1559' u='m' c='_ZN25QOpenGLFunctions_3_3_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1564' u='m' c='_ZN25QOpenGLFunctions_3_3_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1569' u='m' c='_ZN25QOpenGLFunctions_3_3_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1574' u='m' c='_ZN25QOpenGLFunctions_3_3_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1579' u='m' c='_ZN25QOpenGLFunctions_3_3_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1584' u='m' c='_ZN25QOpenGLFunctions_3_3_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_3_3_core.h' l='1589' u='m' c='_ZN25QOpenGLFunctions_3_3_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2099' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2104' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2109' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2114' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2119' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2124' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2129' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2134' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2139' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2144' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2149' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_compatibility.h' l='2154' u='m' c='_ZN34QOpenGLFunctions_4_0_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1583' u='m' c='_ZN25QOpenGLFunctions_4_0_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1588' u='m' c='_ZN25QOpenGLFunctions_4_0_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1593' u='m' c='_ZN25QOpenGLFunctions_4_0_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1598' u='m' c='_ZN25QOpenGLFunctions_4_0_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1603' u='m' c='_ZN25QOpenGLFunctions_4_0_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1608' u='m' c='_ZN25QOpenGLFunctions_4_0_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1613' u='m' c='_ZN25QOpenGLFunctions_4_0_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1618' u='m' c='_ZN25QOpenGLFunctions_4_0_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1623' u='m' c='_ZN25QOpenGLFunctions_4_0_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1628' u='m' c='_ZN25QOpenGLFunctions_4_0_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1633' u='m' c='_ZN25QOpenGLFunctions_4_0_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_0_core.h' l='1638' u='m' c='_ZN25QOpenGLFunctions_4_0_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2192' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2197' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2202' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2207' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2212' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2217' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2222' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2227' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2232' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2237' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2242' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_compatibility.h' l='2247' u='m' c='_ZN34QOpenGLFunctions_4_1_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1674' u='m' c='_ZN25QOpenGLFunctions_4_1_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1679' u='m' c='_ZN25QOpenGLFunctions_4_1_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1684' u='m' c='_ZN25QOpenGLFunctions_4_1_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1689' u='m' c='_ZN25QOpenGLFunctions_4_1_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1694' u='m' c='_ZN25QOpenGLFunctions_4_1_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1699' u='m' c='_ZN25QOpenGLFunctions_4_1_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1704' u='m' c='_ZN25QOpenGLFunctions_4_1_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1709' u='m' c='_ZN25QOpenGLFunctions_4_1_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1714' u='m' c='_ZN25QOpenGLFunctions_4_1_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1719' u='m' c='_ZN25QOpenGLFunctions_4_1_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1724' u='m' c='_ZN25QOpenGLFunctions_4_1_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_1_core.h' l='1729' u='m' c='_ZN25QOpenGLFunctions_4_1_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2215' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2220' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2225' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2230' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2235' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2240' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2245' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2250' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2255' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2260' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2265' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_compatibility.h' l='2270' u='m' c='_ZN34QOpenGLFunctions_4_2_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1695' u='m' c='_ZN25QOpenGLFunctions_4_2_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1700' u='m' c='_ZN25QOpenGLFunctions_4_2_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1705' u='m' c='_ZN25QOpenGLFunctions_4_2_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1710' u='m' c='_ZN25QOpenGLFunctions_4_2_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1715' u='m' c='_ZN25QOpenGLFunctions_4_2_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1720' u='m' c='_ZN25QOpenGLFunctions_4_2_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1725' u='m' c='_ZN25QOpenGLFunctions_4_2_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1730' u='m' c='_ZN25QOpenGLFunctions_4_2_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1735' u='m' c='_ZN25QOpenGLFunctions_4_2_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1740' u='m' c='_ZN25QOpenGLFunctions_4_2_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1745' u='m' c='_ZN25QOpenGLFunctions_4_2_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_2_core.h' l='1750' u='m' c='_ZN25QOpenGLFunctions_4_2_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2253' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2258' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2263' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2268' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2273' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2278' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2283' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2288' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2293' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2298' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2303' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='2308' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1732' u='m' c='_ZN25QOpenGLFunctions_4_3_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1737' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1742' u='m' c='_ZN25QOpenGLFunctions_4_3_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1747' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1752' u='m' c='_ZN25QOpenGLFunctions_4_3_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1757' u='m' c='_ZN25QOpenGLFunctions_4_3_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1762' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1767' u='m' c='_ZN25QOpenGLFunctions_4_3_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1772' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1777' u='m' c='_ZN25QOpenGLFunctions_4_3_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1782' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='1787' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2541' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2546' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2551' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2556' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2561' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2566' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2571' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2576' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2581' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2586' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2591' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='2596' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2089' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2094' u='m' c='_ZN25QOpenGLFunctions_4_4_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2099' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2104' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2109' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2114' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2119' u='m' c='_ZN25QOpenGLFunctions_4_4_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2124' u='m' c='_ZN25QOpenGLFunctions_4_4_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2129' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2134' u='m' c='_ZN25QOpenGLFunctions_4_4_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2139' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='2144' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2665' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2670' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2675' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2680' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2685' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2690' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2695' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2700' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2705' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2710' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2715' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='2720' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2198' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2203' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2208' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2213' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2218' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glGetActiveUniformNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2223' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2228' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2233' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2238' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glPrimitiveRestartIndexEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2243' u='m' c='_ZN25QOpenGLFunctions_4_5_Core11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2248' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='2253' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glDrawArraysInstancedEjiii'/>
