<dec f='qtbase-6.5.0/src/opengl/qopengltexture.h' l='263' type='33319'/>
<doc f='qtbase-6.5.0/src/opengl/qopengltexture.h' l='263'>// GL_RG</doc>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='493' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='505' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='517' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='529' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='613' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='625' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='694' u='r' c='_ZL39pixelFormatCompatibleWithInternalFormatN14QOpenGLTexture13TextureFormatE'/>
<doc f='qtbase-6.5.0/src/opengl/qopengltexture.cpp' l='2318'>\value RG Equivalent to GL_RG
    </doc>
