<dec f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='493' type='QOpenGLExtraFunctionsPrivate::Functions'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='731' u='m' c='_ZN21QOpenGLExtraFunctions12glBeginQueryEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='739' u='m' c='_ZN21QOpenGLExtraFunctions24glBeginTransformFeedbackEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='747' u='m' c='_ZN21QOpenGLExtraFunctions16glBindBufferBaseEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='755' u='m' c='_ZN21QOpenGLExtraFunctions17glBindBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='763' u='m' c='_ZN21QOpenGLExtraFunctions13glBindSamplerEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='771' u='m' c='_ZN21QOpenGLExtraFunctions23glBindTransformFeedbackEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='779' u='m' c='_ZN21QOpenGLExtraFunctions17glBindVertexArrayEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='787' u='m' c='_ZN21QOpenGLExtraFunctions17glBlitFramebufferEiiiiiiiijj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='795' u='m' c='_ZN21QOpenGLExtraFunctions15glClearBufferfiEjifi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='803' u='m' c='_ZN21QOpenGLExtraFunctions15glClearBufferfvEjiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='811' u='m' c='_ZN21QOpenGLExtraFunctions15glClearBufferivEjiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='819' u='m' c='_ZN21QOpenGLExtraFunctions16glClearBufferuivEjiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='827' u='m' c='_ZN21QOpenGLExtraFunctions16glClientWaitSyncEP8__GLsyncjm'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='836' u='m' c='_ZN21QOpenGLExtraFunctions22glCompressedTexImage3DEjijiiiiiPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='844' u='m' c='_ZN21QOpenGLExtraFunctions25glCompressedTexSubImage3DEjiiiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='852' u='m' c='_ZN21QOpenGLExtraFunctions19glCopyBufferSubDataEjjlll'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='860' u='m' c='_ZN21QOpenGLExtraFunctions19glCopyTexSubImage3DEjiiiiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='868' u='m' c='_ZN21QOpenGLExtraFunctions15glDeleteQueriesEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='876' u='m' c='_ZN21QOpenGLExtraFunctions16glDeleteSamplersEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='884' u='m' c='_ZN21QOpenGLExtraFunctions12glDeleteSyncEP8__GLsync'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='892' u='m' c='_ZN21QOpenGLExtraFunctions26glDeleteTransformFeedbacksEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='900' u='m' c='_ZN21QOpenGLExtraFunctions20glDeleteVertexArraysEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='908' u='m' c='_ZN21QOpenGLExtraFunctions21glDrawArraysInstancedEjiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='916' u='m' c='_ZN21QOpenGLExtraFunctions13glDrawBuffersEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='924' u='m' c='_ZN21QOpenGLExtraFunctions23glDrawElementsInstancedEjijPKvi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='932' u='m' c='_ZN21QOpenGLExtraFunctions19glDrawRangeElementsEjjjijPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='940' u='m' c='_ZN21QOpenGLExtraFunctions10glEndQueryEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='948' u='m' c='_ZN21QOpenGLExtraFunctions22glEndTransformFeedbackEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='956' u='m' c='_ZN21QOpenGLExtraFunctions11glFenceSyncEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='965' u='m' c='_ZN21QOpenGLExtraFunctions24glFlushMappedBufferRangeEjll'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='973' u='m' c='_ZN21QOpenGLExtraFunctions25glFramebufferTextureLayerEjjjii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='981' u='m' c='_ZN21QOpenGLExtraFunctions12glGenQueriesEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='989' u='m' c='_ZN21QOpenGLExtraFunctions13glGenSamplersEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='997' u='m' c='_ZN21QOpenGLExtraFunctions23glGenTransformFeedbacksEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1005' u='m' c='_ZN21QOpenGLExtraFunctions17glGenVertexArraysEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1013' u='m' c='_ZN21QOpenGLExtraFunctions27glGetActiveUniformBlockNameEjjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1021' u='m' c='_ZN21QOpenGLExtraFunctions25glGetActiveUniformBlockivEjjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1029' u='m' c='_ZN21QOpenGLExtraFunctions21glGetActiveUniformsivEjiPKjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1037' u='m' c='_ZN21QOpenGLExtraFunctions24glGetBufferParameteri64vEjjPl'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1045' u='m' c='_ZN21QOpenGLExtraFunctions19glGetBufferPointervEjjPPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1053' u='m' c='_ZN21QOpenGLExtraFunctions21glGetFragDataLocationEjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1062' u='m' c='_ZN21QOpenGLExtraFunctions17glGetInteger64i_vEjjPl'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1070' u='m' c='_ZN21QOpenGLExtraFunctions15glGetInteger64vEjPl'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1078' u='m' c='_ZN21QOpenGLExtraFunctions15glGetIntegeri_vEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1086' u='m' c='_ZN21QOpenGLExtraFunctions21glGetInternalformativEjjjiPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1094' u='m' c='_ZN21QOpenGLExtraFunctions18glGetProgramBinaryEjiPiPjPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1102' u='m' c='_ZN21QOpenGLExtraFunctions19glGetQueryObjectuivEjjPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1110' u='m' c='_ZN21QOpenGLExtraFunctions12glGetQueryivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1118' u='m' c='_ZN21QOpenGLExtraFunctions23glGetSamplerParameterfvEjjPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1126' u='m' c='_ZN21QOpenGLExtraFunctions23glGetSamplerParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1134' u='m' c='_ZN21QOpenGLExtraFunctions12glGetStringiEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1143' u='m' c='_ZN21QOpenGLExtraFunctions11glGetSyncivEP8__GLsyncjiPiS2_'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1151' u='m' c='_ZN21QOpenGLExtraFunctions29glGetTransformFeedbackVaryingEjjiPiS0_PjPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1159' u='m' c='_ZN21QOpenGLExtraFunctions22glGetUniformBlockIndexEjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1168' u='m' c='_ZN21QOpenGLExtraFunctions19glGetUniformIndicesEjiPKPKcPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1176' u='m' c='_ZN21QOpenGLExtraFunctions15glGetUniformuivEjiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1184' u='m' c='_ZN21QOpenGLExtraFunctions20glGetVertexAttribIivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1192' u='m' c='_ZN21QOpenGLExtraFunctions21glGetVertexAttribIuivEjjPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1200' u='m' c='_ZN21QOpenGLExtraFunctions23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1208' u='m' c='_ZN21QOpenGLExtraFunctions26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1216' u='m' c='_ZN21QOpenGLExtraFunctions9glIsQueryEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1225' u='m' c='_ZN21QOpenGLExtraFunctions11glIsSamplerEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1234' u='m' c='_ZN21QOpenGLExtraFunctions8glIsSyncEP8__GLsync'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1243' u='m' c='_ZN21QOpenGLExtraFunctions21glIsTransformFeedbackEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1252' u='m' c='_ZN21QOpenGLExtraFunctions15glIsVertexArrayEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1261' u='m' c='_ZN21QOpenGLExtraFunctions16glMapBufferRangeEjllj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1270' u='m' c='_ZN21QOpenGLExtraFunctions24glPauseTransformFeedbackEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1278' u='m' c='_ZN21QOpenGLExtraFunctions15glProgramBinaryEjjPKvi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1286' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramParameteriEjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1294' u='m' c='_ZN21QOpenGLExtraFunctions12glReadBufferEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1302' u='m' c='_ZN21QOpenGLExtraFunctions32glRenderbufferStorageMultisampleEjijii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1310' u='m' c='_ZN21QOpenGLExtraFunctions25glResumeTransformFeedbackEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1318' u='m' c='_ZN21QOpenGLExtraFunctions19glSamplerParameterfEjjf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1326' u='m' c='_ZN21QOpenGLExtraFunctions20glSamplerParameterfvEjjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1334' u='m' c='_ZN21QOpenGLExtraFunctions19glSamplerParameteriEjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1342' u='m' c='_ZN21QOpenGLExtraFunctions20glSamplerParameterivEjjPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1350' u='m' c='_ZN21QOpenGLExtraFunctions12glTexImage3DEjiiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1358' u='m' c='_ZN21QOpenGLExtraFunctions14glTexStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1366' u='m' c='_ZN21QOpenGLExtraFunctions14glTexStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1374' u='m' c='_ZN21QOpenGLExtraFunctions15glTexSubImage3DEjiiiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1382' u='m' c='_ZN21QOpenGLExtraFunctions27glTransformFeedbackVaryingsEjiPKPKcj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1390' u='m' c='_ZN21QOpenGLExtraFunctions12glUniform1uiEij'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1398' u='m' c='_ZN21QOpenGLExtraFunctions13glUniform1uivEiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1406' u='m' c='_ZN21QOpenGLExtraFunctions12glUniform2uiEijj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1414' u='m' c='_ZN21QOpenGLExtraFunctions13glUniform2uivEiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1422' u='m' c='_ZN21QOpenGLExtraFunctions12glUniform3uiEijjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1430' u='m' c='_ZN21QOpenGLExtraFunctions13glUniform3uivEiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1438' u='m' c='_ZN21QOpenGLExtraFunctions12glUniform4uiEijjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1446' u='m' c='_ZN21QOpenGLExtraFunctions13glUniform4uivEiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1454' u='m' c='_ZN21QOpenGLExtraFunctions21glUniformBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1462' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix2x3fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1470' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix2x4fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1478' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix3x2fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1486' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix3x4fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1494' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix4x2fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1502' u='m' c='_ZN21QOpenGLExtraFunctions20glUniformMatrix4x3fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1510' u='m' c='_ZN21QOpenGLExtraFunctions13glUnmapBufferEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1519' u='m' c='_ZN21QOpenGLExtraFunctions21glVertexAttribDivisorEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1527' u='m' c='_ZN21QOpenGLExtraFunctions17glVertexAttribI4iEjiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1535' u='m' c='_ZN21QOpenGLExtraFunctions18glVertexAttribI4ivEjPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1543' u='m' c='_ZN21QOpenGLExtraFunctions18glVertexAttribI4uiEjjjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1551' u='m' c='_ZN21QOpenGLExtraFunctions19glVertexAttribI4uivEjPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1559' u='m' c='_ZN21QOpenGLExtraFunctions22glVertexAttribIPointerEjijiPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1567' u='m' c='_ZN21QOpenGLExtraFunctions10glWaitSyncEP8__GLsyncjm'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1575' u='m' c='_ZN21QOpenGLExtraFunctions21glActiveShaderProgramEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1583' u='m' c='_ZN21QOpenGLExtraFunctions18glBindImageTextureEjjihijj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1591' u='m' c='_ZN21QOpenGLExtraFunctions21glBindProgramPipelineEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1599' u='m' c='_ZN21QOpenGLExtraFunctions18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1607' u='m' c='_ZN21QOpenGLExtraFunctions22glCreateShaderProgramvEjiPKPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1616' u='m' c='_ZN21QOpenGLExtraFunctions24glDeleteProgramPipelinesEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1624' u='m' c='_ZN21QOpenGLExtraFunctions17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1632' u='m' c='_ZN21QOpenGLExtraFunctions25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1640' u='m' c='_ZN21QOpenGLExtraFunctions20glDrawArraysIndirectEjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1648' u='m' c='_ZN21QOpenGLExtraFunctions22glDrawElementsIndirectEjjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1656' u='m' c='_ZN21QOpenGLExtraFunctions23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1664' u='m' c='_ZN21QOpenGLExtraFunctions21glGenProgramPipelinesEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1672' u='m' c='_ZN21QOpenGLExtraFunctions15glGetBooleani_vEjjPh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1680' u='m' c='_ZN21QOpenGLExtraFunctions27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1688' u='m' c='_ZN21QOpenGLExtraFunctions18glGetMultisamplefvEjjPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1696' u='m' c='_ZN21QOpenGLExtraFunctions23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1704' u='m' c='_ZN21QOpenGLExtraFunctions27glGetProgramPipelineInfoLogEjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1712' u='m' c='_ZN21QOpenGLExtraFunctions22glGetProgramPipelineivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1720' u='m' c='_ZN21QOpenGLExtraFunctions25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1729' u='m' c='_ZN21QOpenGLExtraFunctions28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1738' u='m' c='_ZN21QOpenGLExtraFunctions24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1746' u='m' c='_ZN21QOpenGLExtraFunctions22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1754' u='m' c='_ZN21QOpenGLExtraFunctions24glGetTexLevelParameterfvEjijPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1762' u='m' c='_ZN21QOpenGLExtraFunctions24glGetTexLevelParameterivEjijPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1770' u='m' c='_ZN21QOpenGLExtraFunctions19glIsProgramPipelineEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1779' u='m' c='_ZN21QOpenGLExtraFunctions15glMemoryBarrierEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1787' u='m' c='_ZN21QOpenGLExtraFunctions23glMemoryBarrierByRegionEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1795' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform1fEjif'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1803' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform1fvEjiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1811' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform1iEjii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1819' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform1ivEjiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1827' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform1uiEjij'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1835' u='m' c='_ZN21QOpenGLExtraFunctions20glProgramUniform1uivEjiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1843' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform2fEjiff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1851' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform2fvEjiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1859' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform2iEjiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1867' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform2ivEjiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1875' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform2uiEjijj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1883' u='m' c='_ZN21QOpenGLExtraFunctions20glProgramUniform2uivEjiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1891' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform3fEjifff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1899' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform3fvEjiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1907' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform3iEjiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1915' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform3ivEjiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1923' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform3uiEjijjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1931' u='m' c='_ZN21QOpenGLExtraFunctions20glProgramUniform3uivEjiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1939' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform4fEjiffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1947' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform4fvEjiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1955' u='m' c='_ZN21QOpenGLExtraFunctions18glProgramUniform4iEjiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1963' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform4ivEjiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1971' u='m' c='_ZN21QOpenGLExtraFunctions19glProgramUniform4uiEjijjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1979' u='m' c='_ZN21QOpenGLExtraFunctions20glProgramUniform4uivEjiiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1987' u='m' c='_ZN21QOpenGLExtraFunctions25glProgramUniformMatrix2fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='1995' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix2x3fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2003' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix2x4fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2011' u='m' c='_ZN21QOpenGLExtraFunctions25glProgramUniformMatrix3fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2019' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix3x2fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2027' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix3x4fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2035' u='m' c='_ZN21QOpenGLExtraFunctions25glProgramUniformMatrix4fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2043' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix4x2fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2051' u='m' c='_ZN21QOpenGLExtraFunctions27glProgramUniformMatrix4x3fvEjiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2059' u='m' c='_ZN21QOpenGLExtraFunctions13glSampleMaskiEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2067' u='m' c='_ZN21QOpenGLExtraFunctions25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2075' u='m' c='_ZN21QOpenGLExtraFunctions18glUseProgramStagesEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2083' u='m' c='_ZN21QOpenGLExtraFunctions25glValidateProgramPipelineEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2091' u='m' c='_ZN21QOpenGLExtraFunctions21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2099' u='m' c='_ZN21QOpenGLExtraFunctions20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2107' u='m' c='_ZN21QOpenGLExtraFunctions21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2115' u='m' c='_ZN21QOpenGLExtraFunctions22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2125' u='m' c='_ZN21QOpenGLExtraFunctions14glBlendBarrierEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2133' u='m' c='_ZN21QOpenGLExtraFunctions24glBlendEquationSeparateiEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2141' u='m' c='_ZN21QOpenGLExtraFunctions16glBlendEquationiEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2149' u='m' c='_ZN21QOpenGLExtraFunctions20glBlendFuncSeparateiEjjjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2157' u='m' c='_ZN21QOpenGLExtraFunctions12glBlendFunciEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2165' u='m' c='_ZN21QOpenGLExtraFunctions12glColorMaskiEjhhhh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2173' u='m' c='_ZN21QOpenGLExtraFunctions18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2181' u='m' c='_ZN21QOpenGLExtraFunctions22glDebugMessageCallbackEPFvjjjjiPKcPKvES3_'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2189' u='m' c='_ZN21QOpenGLExtraFunctions21glDebugMessageControlEjjjiPKjh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2197' u='m' c='_ZN21QOpenGLExtraFunctions20glDebugMessageInsertEjjjjiPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2205' u='m' c='_ZN21QOpenGLExtraFunctions10glDisableiEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2213' u='m' c='_ZN21QOpenGLExtraFunctions24glDrawElementsBaseVertexEjijPKvi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2221' u='m' c='_ZN21QOpenGLExtraFunctions33glDrawElementsInstancedBaseVertexEjijPKvii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2229' u='m' c='_ZN21QOpenGLExtraFunctions29glDrawRangeElementsBaseVertexEjjjijPKvi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2237' u='m' c='_ZN21QOpenGLExtraFunctions9glEnableiEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2245' u='m' c='_ZN21QOpenGLExtraFunctions20glFramebufferTextureEjjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2253' u='m' c='_ZN21QOpenGLExtraFunctions20glGetDebugMessageLogEjiPjS0_S0_S0_PiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2262' u='m' c='_ZN21QOpenGLExtraFunctions24glGetGraphicsResetStatusEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2271' u='m' c='_ZN21QOpenGLExtraFunctions16glGetObjectLabelEjjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2279' u='m' c='_ZN21QOpenGLExtraFunctions19glGetObjectPtrLabelEPKviPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2287' u='m' c='_ZN21QOpenGLExtraFunctions13glGetPointervEjPPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2295' u='m' c='_ZN21QOpenGLExtraFunctions24glGetSamplerParameterIivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2303' u='m' c='_ZN21QOpenGLExtraFunctions25glGetSamplerParameterIuivEjjPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2311' u='m' c='_ZN21QOpenGLExtraFunctions20glGetTexParameterIivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2319' u='m' c='_ZN21QOpenGLExtraFunctions21glGetTexParameterIuivEjjPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2327' u='m' c='_ZN21QOpenGLExtraFunctions15glGetnUniformfvEjiiPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2335' u='m' c='_ZN21QOpenGLExtraFunctions15glGetnUniformivEjiiPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2343' u='m' c='_ZN21QOpenGLExtraFunctions16glGetnUniformuivEjiiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2351' u='m' c='_ZN21QOpenGLExtraFunctions12glIsEnablediEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2360' u='m' c='_ZN21QOpenGLExtraFunctions18glMinSampleShadingEf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2368' u='m' c='_ZN21QOpenGLExtraFunctions13glObjectLabelEjjiPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2376' u='m' c='_ZN21QOpenGLExtraFunctions16glObjectPtrLabelEPKviPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2384' u='m' c='_ZN21QOpenGLExtraFunctions17glPatchParameteriEji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2392' u='m' c='_ZN21QOpenGLExtraFunctions15glPopDebugGroupEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2400' u='m' c='_ZN21QOpenGLExtraFunctions22glPrimitiveBoundingBoxEffffffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2408' u='m' c='_ZN21QOpenGLExtraFunctions16glPushDebugGroupEjjiPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2416' u='m' c='_ZN21QOpenGLExtraFunctions13glReadnPixelsEiiiijjiPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2424' u='m' c='_ZN21QOpenGLExtraFunctions21glSamplerParameterIivEjjPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2432' u='m' c='_ZN21QOpenGLExtraFunctions22glSamplerParameterIuivEjjPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2440' u='m' c='_ZN21QOpenGLExtraFunctions11glTexBufferEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2448' u='m' c='_ZN21QOpenGLExtraFunctions16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2456' u='m' c='_ZN21QOpenGLExtraFunctions17glTexParameterIivEjjPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2464' u='m' c='_ZN21QOpenGLExtraFunctions18glTexParameterIuivEjjPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglextrafunctions.h' l='2472' u='m' c='_ZN21QOpenGLExtraFunctions25glTexStorage3DMultisampleEjijiiih'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/opengl/qopengltexturehelper.cpp' l='173' u='m' c='_ZN20QOpenGLTextureHelperC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexturehelper.cpp' l='174' u='m' c='_ZN20QOpenGLTextureHelperC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexturehelper.cpp' l='175' u='m' c='_ZN20QOpenGLTextureHelperC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopengltexturehelper.cpp' l='176' u='m' c='_ZN20QOpenGLTextureHelperC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopenglvertexarrayobject.cpp' l='57' u='m' c='_ZN30QOpenGLVertexArrayObjectHelper21initializeFromContextEP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopenglvertexarrayobject.cpp' l='58' u='m' c='_ZN30QOpenGLVertexArrayObjectHelper21initializeFromContextEP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopenglvertexarrayobject.cpp' l='59' u='m' c='_ZN30QOpenGLVertexArrayObjectHelper21initializeFromContextEP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopenglvertexarrayobject.cpp' l='60' u='m' c='_ZN30QOpenGLVertexArrayObjectHelper21initializeFromContextEP14QOpenGLContext'/>
