<dec f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='400' type='QOpenGLFunctionsPrivate::Functions'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='566' u='m' c='_ZN16QOpenGLFunctions13glBindTextureEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='577' u='m' c='_ZN16QOpenGLFunctions11glBlendFuncEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='588' u='m' c='_ZN16QOpenGLFunctions7glClearEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='599' u='m' c='_ZN16QOpenGLFunctions12glClearColorEffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='610' u='m' c='_ZN16QOpenGLFunctions14glClearStencilEi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='621' u='m' c='_ZN16QOpenGLFunctions11glColorMaskEhhhh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='632' u='m' c='_ZN16QOpenGLFunctions16glCopyTexImage2DEjijiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='643' u='m' c='_ZN16QOpenGLFunctions19glCopyTexSubImage2DEjiiiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='654' u='m' c='_ZN16QOpenGLFunctions10glCullFaceEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='665' u='m' c='_ZN16QOpenGLFunctions16glDeleteTexturesEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='676' u='m' c='_ZN16QOpenGLFunctions11glDepthFuncEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='687' u='m' c='_ZN16QOpenGLFunctions11glDepthMaskEh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='698' u='m' c='_ZN16QOpenGLFunctions9glDisableEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='709' u='m' c='_ZN16QOpenGLFunctions12glDrawArraysEjii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='720' u='m' c='_ZN16QOpenGLFunctions14glDrawElementsEjijPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='731' u='m' c='_ZN16QOpenGLFunctions8glEnableEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='742' u='m' c='_ZN16QOpenGLFunctions8glFinishEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='753' u='m' c='_ZN16QOpenGLFunctions7glFlushEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='764' u='m' c='_ZN16QOpenGLFunctions11glFrontFaceEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='775' u='m' c='_ZN16QOpenGLFunctions13glGenTexturesEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='786' u='m' c='_ZN16QOpenGLFunctions13glGetBooleanvEjPh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='797' u='m' c='_ZN16QOpenGLFunctions10glGetErrorEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='808' u='m' c='_ZN16QOpenGLFunctions11glGetFloatvEjPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='819' u='m' c='_ZN16QOpenGLFunctions13glGetIntegervEjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='830' u='m' c='_ZN16QOpenGLFunctions11glGetStringEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='842' u='m' c='_ZN16QOpenGLFunctions19glGetTexParameterfvEjjPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='853' u='m' c='_ZN16QOpenGLFunctions19glGetTexParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='864' u='m' c='_ZN16QOpenGLFunctions6glHintEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='875' u='m' c='_ZN16QOpenGLFunctions11glIsEnabledEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='887' u='m' c='_ZN16QOpenGLFunctions11glIsTextureEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='899' u='m' c='_ZN16QOpenGLFunctions11glLineWidthEf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='910' u='m' c='_ZN16QOpenGLFunctions13glPixelStoreiEji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='921' u='m' c='_ZN16QOpenGLFunctions15glPolygonOffsetEff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='932' u='m' c='_ZN16QOpenGLFunctions12glReadPixelsEiiiijjPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='943' u='m' c='_ZN16QOpenGLFunctions9glScissorEiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='954' u='m' c='_ZN16QOpenGLFunctions13glStencilFuncEjij'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='965' u='m' c='_ZN16QOpenGLFunctions13glStencilMaskEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='976' u='m' c='_ZN16QOpenGLFunctions11glStencilOpEjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='987' u='m' c='_ZN16QOpenGLFunctions12glTexImage2DEjiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='998' u='m' c='_ZN16QOpenGLFunctions15glTexParameterfEjjf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1009' u='m' c='_ZN16QOpenGLFunctions16glTexParameterfvEjjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1020' u='m' c='_ZN16QOpenGLFunctions15glTexParameteriEjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1031' u='m' c='_ZN16QOpenGLFunctions16glTexParameterivEjjPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1042' u='m' c='_ZN16QOpenGLFunctions15glTexSubImage2DEjiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1053' u='m' c='_ZN16QOpenGLFunctions10glViewportEiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1066' u='m' c='_ZN16QOpenGLFunctions15glActiveTextureEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1077' u='m' c='_ZN16QOpenGLFunctions14glAttachShaderEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1088' u='m' c='_ZN16QOpenGLFunctions20glBindAttribLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1099' u='m' c='_ZN16QOpenGLFunctions12glBindBufferEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1112' u='m' c='_ZN16QOpenGLFunctions17glBindFramebufferEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1123' u='m' c='_ZN16QOpenGLFunctions18glBindRenderbufferEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1134' u='m' c='_ZN16QOpenGLFunctions12glBlendColorEffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1145' u='m' c='_ZN16QOpenGLFunctions15glBlendEquationEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1156' u='m' c='_ZN16QOpenGLFunctions23glBlendEquationSeparateEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1167' u='m' c='_ZN16QOpenGLFunctions19glBlendFuncSeparateEjjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1178' u='m' c='_ZN16QOpenGLFunctions12glBufferDataEjlPKvj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1189' u='m' c='_ZN16QOpenGLFunctions15glBufferSubDataEjllPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1200' u='m' c='_ZN16QOpenGLFunctions24glCheckFramebufferStatusEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1212' u='m' c='_ZN16QOpenGLFunctions13glClearDepthfEf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1223' u='m' c='_ZN16QOpenGLFunctions15glCompileShaderEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1234' u='m' c='_ZN16QOpenGLFunctions22glCompressedTexImage2DEjijiiiiPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1245' u='m' c='_ZN16QOpenGLFunctions25glCompressedTexSubImage2DEjiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1256' u='m' c='_ZN16QOpenGLFunctions15glCreateProgramEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1268' u='m' c='_ZN16QOpenGLFunctions14glCreateShaderEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1280' u='m' c='_ZN16QOpenGLFunctions15glDeleteBuffersEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1291' u='m' c='_ZN16QOpenGLFunctions20glDeleteFramebuffersEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1302' u='m' c='_ZN16QOpenGLFunctions15glDeleteProgramEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1313' u='m' c='_ZN16QOpenGLFunctions21glDeleteRenderbuffersEiPKj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1324' u='m' c='_ZN16QOpenGLFunctions14glDeleteShaderEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1335' u='m' c='_ZN16QOpenGLFunctions13glDepthRangefEff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1346' u='m' c='_ZN16QOpenGLFunctions14glDetachShaderEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1357' u='m' c='_ZN16QOpenGLFunctions26glDisableVertexAttribArrayEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1368' u='m' c='_ZN16QOpenGLFunctions25glEnableVertexAttribArrayEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1379' u='m' c='_ZN16QOpenGLFunctions25glFramebufferRenderbufferEjjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1390' u='m' c='_ZN16QOpenGLFunctions22glFramebufferTexture2DEjjjji'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1401' u='m' c='_ZN16QOpenGLFunctions12glGenBuffersEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1412' u='m' c='_ZN16QOpenGLFunctions16glGenerateMipmapEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1423' u='m' c='_ZN16QOpenGLFunctions17glGenFramebuffersEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1434' u='m' c='_ZN16QOpenGLFunctions18glGenRenderbuffersEiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1445' u='m' c='_ZN16QOpenGLFunctions17glGetActiveAttribEjjiPiS0_PjPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1456' u='m' c='_ZN16QOpenGLFunctions18glGetActiveUniformEjjiPiS0_PjPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1467' u='m' c='_ZN16QOpenGLFunctions20glGetAttachedShadersEjiPiPj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1478' u='m' c='_ZN16QOpenGLFunctions19glGetAttribLocationEjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1490' u='m' c='_ZN16QOpenGLFunctions22glGetBufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1501' u='m' c='_ZN16QOpenGLFunctions37glGetFramebufferAttachmentParameterivEjjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1512' u='m' c='_ZN16QOpenGLFunctions14glGetProgramivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1523' u='m' c='_ZN16QOpenGLFunctions19glGetProgramInfoLogEjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1534' u='m' c='_ZN16QOpenGLFunctions28glGetRenderbufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1545' u='m' c='_ZN16QOpenGLFunctions13glGetShaderivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1556' u='m' c='_ZN16QOpenGLFunctions18glGetShaderInfoLogEjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1567' u='m' c='_ZN16QOpenGLFunctions26glGetShaderPrecisionFormatEjjPiS0_'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1578' u='m' c='_ZN16QOpenGLFunctions17glGetShaderSourceEjiPiPc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1589' u='m' c='_ZN16QOpenGLFunctions14glGetUniformfvEjiPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1600' u='m' c='_ZN16QOpenGLFunctions14glGetUniformivEjiPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1611' u='m' c='_ZN16QOpenGLFunctions20glGetUniformLocationEjPKc'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1623' u='m' c='_ZN16QOpenGLFunctions19glGetVertexAttribfvEjjPf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1634' u='m' c='_ZN16QOpenGLFunctions19glGetVertexAttribivEjjPi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1645' u='m' c='_ZN16QOpenGLFunctions25glGetVertexAttribPointervEjjPPv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1656' u='m' c='_ZN16QOpenGLFunctions10glIsBufferEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1668' u='m' c='_ZN16QOpenGLFunctions15glIsFramebufferEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1680' u='m' c='_ZN16QOpenGLFunctions11glIsProgramEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1692' u='m' c='_ZN16QOpenGLFunctions16glIsRenderbufferEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1704' u='m' c='_ZN16QOpenGLFunctions10glIsShaderEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1716' u='m' c='_ZN16QOpenGLFunctions13glLinkProgramEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1727' u='m' c='_ZN16QOpenGLFunctions23glReleaseShaderCompilerEv'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1738' u='m' c='_ZN16QOpenGLFunctions21glRenderbufferStorageEjjii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1749' u='m' c='_ZN16QOpenGLFunctions16glSampleCoverageEfh'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1760' u='m' c='_ZN16QOpenGLFunctions14glShaderBinaryEiPKjjPKvi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1771' u='m' c='_ZN16QOpenGLFunctions14glShaderSourceEjiPPKcPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1782' u='m' c='_ZN16QOpenGLFunctions21glStencilFuncSeparateEjjij'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1793' u='m' c='_ZN16QOpenGLFunctions21glStencilMaskSeparateEjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1804' u='m' c='_ZN16QOpenGLFunctions19glStencilOpSeparateEjjjj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1815' u='m' c='_ZN16QOpenGLFunctions11glUniform1fEif'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1826' u='m' c='_ZN16QOpenGLFunctions12glUniform1fvEiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1837' u='m' c='_ZN16QOpenGLFunctions11glUniform1iEii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1848' u='m' c='_ZN16QOpenGLFunctions12glUniform1ivEiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1859' u='m' c='_ZN16QOpenGLFunctions11glUniform2fEiff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1870' u='m' c='_ZN16QOpenGLFunctions12glUniform2fvEiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1881' u='m' c='_ZN16QOpenGLFunctions11glUniform2iEiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1892' u='m' c='_ZN16QOpenGLFunctions12glUniform2ivEiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1903' u='m' c='_ZN16QOpenGLFunctions11glUniform3fEifff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1914' u='m' c='_ZN16QOpenGLFunctions12glUniform3fvEiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1925' u='m' c='_ZN16QOpenGLFunctions11glUniform3iEiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1936' u='m' c='_ZN16QOpenGLFunctions12glUniform3ivEiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1947' u='m' c='_ZN16QOpenGLFunctions11glUniform4fEiffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1958' u='m' c='_ZN16QOpenGLFunctions12glUniform4fvEiiPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1969' u='m' c='_ZN16QOpenGLFunctions11glUniform4iEiiiii'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1980' u='m' c='_ZN16QOpenGLFunctions12glUniform4ivEiiPKi'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='1991' u='m' c='_ZN16QOpenGLFunctions18glUniformMatrix2fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2002' u='m' c='_ZN16QOpenGLFunctions18glUniformMatrix3fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2013' u='m' c='_ZN16QOpenGLFunctions18glUniformMatrix4fvEiihPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2024' u='m' c='_ZN16QOpenGLFunctions12glUseProgramEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2035' u='m' c='_ZN16QOpenGLFunctions17glValidateProgramEj'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2046' u='m' c='_ZN16QOpenGLFunctions16glVertexAttrib1fEjf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2057' u='m' c='_ZN16QOpenGLFunctions17glVertexAttrib1fvEjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2068' u='m' c='_ZN16QOpenGLFunctions16glVertexAttrib2fEjff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2079' u='m' c='_ZN16QOpenGLFunctions17glVertexAttrib2fvEjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2090' u='m' c='_ZN16QOpenGLFunctions16glVertexAttrib3fEjfff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2101' u='m' c='_ZN16QOpenGLFunctions17glVertexAttrib3fvEjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2112' u='m' c='_ZN16QOpenGLFunctions16glVertexAttrib4fEjffff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2123' u='m' c='_ZN16QOpenGLFunctions17glVertexAttrib4fvEjPKf'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.h' l='2134' u='m' c='_ZN16QOpenGLFunctions21glVertexAttribPointerEjijhiPKv'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2112' u='m' c='_ZL26qopenglfSpecialClearDepthff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2119' u='m' c='_ZL26qopenglfSpecialDepthRangefff'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2153' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2154' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2155' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2156' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2157' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2158' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2159' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2160' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2161' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2162' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2163' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/gui/opengl/qopenglfunctions.cpp' l='2164' u='m' c='_ZN23QOpenGLFunctionsPrivateC1EP14QOpenGLContext'/>
