<dec f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.h' l='34' type='32'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='230' u='r' c='_ZN20QOpenGLShaderPrivateC1EP14QOpenGLContext6QFlagsIN13QOpenGLShader13ShaderTypeBitEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='283' u='r' c='_ZN20QOpenGLShaderPrivate6createEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='336' c='_ZN20QOpenGLShaderPrivate7compileEP13QOpenGLShader'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='1057' c='_ZL20qt_shaderTypeToStage6QFlagsIN13QOpenGLShader13ShaderTypeBitEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='1077' u='r' c='_ZL20qt_shaderStageToTypeN7QShader5StageE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='3706' u='r' c='_ZN13QOpenGLShader16hasOpenGLShadersE6QFlagsINS_13ShaderTypeBitEEP14QOpenGLContext'/>
<use f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='3713' u='r' c='_ZN13QOpenGLShader16hasOpenGLShadersE6QFlagsINS_13ShaderTypeBitEEP14QOpenGLContext'/>
<doc f='qtbase-6.5.0/src/opengl/qopenglshaderprogram.cpp' l='144'>\value Compute Compute shaders written in the OpenGL shading language (GLSL)
           (requires OpenGL &gt;= 4.3 or OpenGL ES &gt;= 3.1).</doc>
