<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine_p.h' l='152' u='w' c='_ZN28QOpenGL2PaintEngineExPrivateC1EP21QOpenGL2PaintEngineEx'/>
<dec f='qtbase-6.5.0/src/opengl/qopenglpaintengine_p.h' l='242' type='QOpenGL2PaintEngineEx *'/>
<offset>4416</offset>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='310' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='318' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='325' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='386' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='399' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='402' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19updateBrushUniformsEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='429' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate12updateMatrixEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='502' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate21updateCompositionModeEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='508' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate21updateCompositionModeEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='510' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate21updateCompositionModeEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='516' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate21updateCompositionModeEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='626' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate11drawTextureERK11QOpenGLRectS2_RK5QSizebb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='626' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate11drawTextureERK11QOpenGLRectS2_RK5QSizebb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='847' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='869' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='927' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='948' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1050' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1052' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate4fillERK11QVectorPath'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1110' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1112' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1131' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1133' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1153' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1154' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate26fillStencilWithVertexArrayEPKfiPiiRK11QOpenGLRectNS_15StencilFillModeE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1234' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate14prepareForDrawEb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1235' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate14prepareForDrawEb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1236' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate14prepareForDrawEb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1274' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate14prepareForDrawEb'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1359' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate6strokeERK11QVectorPathRK4QPen'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1376' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate6strokeERK11QVectorPathRK4QPen'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1376' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate6strokeERK11QVectorPathRK4QPen'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='1377' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate6strokeERK11QVectorPathRK4QPen'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2129' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19drawPixmapFragmentsEPKN8QPainter14PixmapFragmentEiRK7QPixmap6QFlagsINS0_18PixmapFragmentHintEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2140' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19drawPixmapFragmentsEPKN8QPainter14PixmapFragmentEiRK7QPixmap6QFlagsINS0_18PixmapFragmentHintEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2154' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19drawPixmapFragmentsEPKN8QPainter14PixmapFragmentEiRK7QPixmap6QFlagsINS0_18PixmapFragmentHintEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2154' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate19drawPixmapFragmentsEPKN8QPainter14PixmapFragmentEiRK7QPixmap6QFlagsINS0_18PixmapFragmentHintEE'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2408' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9clearClipEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2426' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2426' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2427' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2428' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2428' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2430' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2439' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2440' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglpaintengine.cpp' l='2467' u='r' c='_ZN28QOpenGL2PaintEngineExPrivate9writeClipERK11QVectorPathj'/>
