<dec f='qtbase-6.5.0/src/opengl/qopenglversionfunctions.h' l='91' type='QOpenGLFunctions_4_3_CoreBackend::Functions'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3440' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3445' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3450' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3455' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3460' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3465' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3470' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3475' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3480' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3485' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3490' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3495' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3500' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3505' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3510' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3515' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3520' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3525' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3530' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3535' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3540' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3545' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3550' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3555' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3560' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3565' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3570' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3575' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3580' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3585' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3590' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3595' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_compatibility.h' l='3600' u='m' c='_ZN34QOpenGLFunctions_4_3_Compatibility17glClearBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2769' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2774' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2779' u='m' c='_ZN25QOpenGLFunctions_4_3_Core16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2784' u='m' c='_ZN25QOpenGLFunctions_4_3_Core27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2789' u='m' c='_ZN25QOpenGLFunctions_4_3_Core33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2794' u='m' c='_ZN25QOpenGLFunctions_4_3_Core28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2799' u='m' c='_ZN25QOpenGLFunctions_4_3_Core22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2804' u='m' c='_ZN25QOpenGLFunctions_4_3_Core24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2809' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2814' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2819' u='m' c='_ZN25QOpenGLFunctions_4_3_Core27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2824' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2829' u='m' c='_ZN25QOpenGLFunctions_4_3_Core26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2834' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2839' u='m' c='_ZN25QOpenGLFunctions_4_3_Core22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2844' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2849' u='m' c='_ZN25QOpenGLFunctions_4_3_Core20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2854' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2859' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2864' u='m' c='_ZN25QOpenGLFunctions_4_3_Core27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2869' u='m' c='_ZN25QOpenGLFunctions_4_3_Core23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2874' u='m' c='_ZN25QOpenGLFunctions_4_3_Core22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2879' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2884' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2889' u='m' c='_ZN25QOpenGLFunctions_4_3_Core21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2894' u='m' c='_ZN25QOpenGLFunctions_4_3_Core20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2899' u='m' c='_ZN25QOpenGLFunctions_4_3_Core18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2904' u='m' c='_ZN25QOpenGLFunctions_4_3_Core13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2909' u='m' c='_ZN25QOpenGLFunctions_4_3_Core18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2914' u='m' c='_ZN25QOpenGLFunctions_4_3_Core25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2919' u='m' c='_ZN25QOpenGLFunctions_4_3_Core17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2924' u='m' c='_ZN25QOpenGLFunctions_4_3_Core20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_3_core.h' l='2929' u='m' c='_ZN25QOpenGLFunctions_4_3_Core17glClearBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3578' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility19glGetObjectPtrLabelEPKviPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3583' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility16glObjectPtrLabelEPKviPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3588' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility16glGetObjectLabelEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3593' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility13glObjectLabelEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3598' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility15glPopDebugGroupEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3603' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility16glPushDebugGroupEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3608' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility20glGetDebugMessageLogEjiPjS0_S0_S0_PiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3613' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glDebugMessageCallbackEPFvjjjjiPKcPKvES3_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3618' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility20glDebugMessageInsertEjjjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3623' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glDebugMessageControlEjjjiPKjh'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3628' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3633' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3638' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3643' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3648' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3653' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3658' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3663' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3668' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3673' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3678' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3683' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3688' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3693' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3698' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3703' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3708' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3713' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3718' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3723' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3728' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3733' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3738' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3743' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3748' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3753' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3758' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3763' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3768' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3773' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3778' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3783' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_compatibility.h' l='3788' u='m' c='_ZN34QOpenGLFunctions_4_4_Compatibility17glClearBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3126' u='m' c='_ZN25QOpenGLFunctions_4_4_Core19glGetObjectPtrLabelEPKviPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3131' u='m' c='_ZN25QOpenGLFunctions_4_4_Core16glObjectPtrLabelEPKviPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3136' u='m' c='_ZN25QOpenGLFunctions_4_4_Core16glGetObjectLabelEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3141' u='m' c='_ZN25QOpenGLFunctions_4_4_Core13glObjectLabelEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3146' u='m' c='_ZN25QOpenGLFunctions_4_4_Core15glPopDebugGroupEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3151' u='m' c='_ZN25QOpenGLFunctions_4_4_Core16glPushDebugGroupEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3156' u='m' c='_ZN25QOpenGLFunctions_4_4_Core20glGetDebugMessageLogEjiPjS0_S0_S0_PiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3161' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glDebugMessageCallbackEPFvjjjjiPKcPKvES3_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3166' u='m' c='_ZN25QOpenGLFunctions_4_4_Core20glDebugMessageInsertEjjjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3171' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glDebugMessageControlEjjjiPKjh'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3176' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3181' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3186' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3191' u='m' c='_ZN25QOpenGLFunctions_4_4_Core21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3196' u='m' c='_ZN25QOpenGLFunctions_4_4_Core20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3201' u='m' c='_ZN25QOpenGLFunctions_4_4_Core18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3206' u='m' c='_ZN25QOpenGLFunctions_4_4_Core13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3211' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3216' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3221' u='m' c='_ZN25QOpenGLFunctions_4_4_Core16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3226' u='m' c='_ZN25QOpenGLFunctions_4_4_Core27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3231' u='m' c='_ZN25QOpenGLFunctions_4_4_Core33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3236' u='m' c='_ZN25QOpenGLFunctions_4_4_Core28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3241' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3246' u='m' c='_ZN25QOpenGLFunctions_4_4_Core24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3251' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3256' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3261' u='m' c='_ZN25QOpenGLFunctions_4_4_Core27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3266' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3271' u='m' c='_ZN25QOpenGLFunctions_4_4_Core26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3276' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3281' u='m' c='_ZN25QOpenGLFunctions_4_4_Core22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3286' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3291' u='m' c='_ZN25QOpenGLFunctions_4_4_Core20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3296' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3301' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3306' u='m' c='_ZN25QOpenGLFunctions_4_4_Core27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3311' u='m' c='_ZN25QOpenGLFunctions_4_4_Core23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3316' u='m' c='_ZN25QOpenGLFunctions_4_4_Core18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3321' u='m' c='_ZN25QOpenGLFunctions_4_4_Core25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3326' u='m' c='_ZN25QOpenGLFunctions_4_4_Core17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3331' u='m' c='_ZN25QOpenGLFunctions_4_4_Core20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_4_core.h' l='3336' u='m' c='_ZN25QOpenGLFunctions_4_4_Core17glClearBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3702' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glGetObjectPtrLabelEPKviPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3707' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glObjectPtrLabelEPKviPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3712' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glGetObjectLabelEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3717' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility13glObjectLabelEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3722' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glPopDebugGroupEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3727' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glPushDebugGroupEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3732' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glGetDebugMessageLogEjiPjS0_S0_S0_PiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3737' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glDebugMessageCallbackEPFvjjjjiPKcPKvES3_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3742' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glDebugMessageInsertEjjjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3747' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glDebugMessageControlEjjjiPKjh'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3752' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3757' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3762' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3767' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3772' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3777' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3782' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3787' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3792' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3797' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3802' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3807' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3812' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3817' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3822' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3827' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3832' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3837' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3842' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3847' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3852' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3857' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3862' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3867' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3872' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3877' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3882' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3887' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3892' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3897' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3902' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3907' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3912' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility17glClearBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3235' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glGetObjectPtrLabelEPKviPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3240' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glObjectPtrLabelEPKviPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3245' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glGetObjectLabelEjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3250' u='m' c='_ZN25QOpenGLFunctions_4_5_Core13glObjectLabelEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3255' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glPopDebugGroupEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3260' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glPushDebugGroupEjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3265' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glGetDebugMessageLogEjiPjS0_S0_S0_PiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3270' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glDebugMessageCallbackEPFvjjjjiPKcPKvES3_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3275' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glDebugMessageInsertEjjjjiPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3280' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glDebugMessageControlEjjjiPKjh'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3285' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glVertexBindingDivisorEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3290' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glVertexAttribBindingEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3295' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glVertexAttribLFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3300' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glVertexAttribIFormatEjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3305' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glVertexAttribFormatEjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3310' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glBindVertexBufferEjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3315' u='m' c='_ZN25QOpenGLFunctions_4_5_Core13glTextureViewEjjjjjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3320' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glTexStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3325' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glTexStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3330' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glTexBufferRangeEjjjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3335' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glShaderStorageBlockBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3340' u='m' c='_ZN25QOpenGLFunctions_4_5_Core33glGetProgramResourceLocationIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3345' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glGetProgramResourceLocationEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3350' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glGetProgramResourceivEjjjiPKjiPiS2_'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3355' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetProgramResourceNameEjjjiPiPc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3360' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glGetProgramResourceIndexEjjPKc'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3365' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGetProgramInterfaceivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3370' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glMultiDrawElementsIndirectEjjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3375' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glMultiDrawArraysIndirectEjPKvii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3380' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glInvalidateSubFramebufferEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3385' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glInvalidateFramebufferEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3390' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glInvalidateBufferDataEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3395' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glInvalidateBufferSubDataEjll'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3400' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glInvalidateTexImageEji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3405' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glInvalidateTexSubImageEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3410' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGetInternalformati64vEjjjiPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3415' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3420' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3425' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glCopyImageSubDataEjjiiiijjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3430' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glDispatchComputeIndirectEl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3435' u='m' c='_ZN25QOpenGLFunctions_4_5_Core17glDispatchComputeEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3440' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glClearBufferSubDataEjjlljjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3445' u='m' c='_ZN25QOpenGLFunctions_4_5_Core17glClearBufferDataEjjjjPKv'/>
