<dec f='qtbase-6.5.0/src/opengl/qopenglversionfunctions.h' l='91' type='QOpenGLFunctions_4_5_CoreBackend::Functions'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3966' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glTextureBarrierEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3971' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility13glReadnPixelsEiiiijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3976' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glGetnUniformuivEjiiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3981' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glGetnUniformivEjiiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3986' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glGetnUniformfvEjiiPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3991' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glGetnUniformdvEjiiPd'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='3996' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility14glGetnTexImageEjijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4001' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetnCompressedTexImageEjiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4006' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetGraphicsResetStatusEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4011' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility30glGetCompressedTextureSubImageEjiiiiiiiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4016' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glGetTextureSubImageEjiiiiiiijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4021' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glMemoryBarrierByRegionEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4026' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glCreateQueriesEjiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4031' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glCreateProgramPipelinesEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4036' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glCreateSamplersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4041' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetVertexArrayIndexed64ivEjjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4046' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glGetVertexArrayIndexedivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4051' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glGetVertexArrayivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4056' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glVertexArrayBindingDivisorEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4061' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glVertexArrayAttribLFormatEjjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4066' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glVertexArrayAttribIFormatEjjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4071' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glVertexArrayAttribFormatEjjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4076' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glVertexArrayAttribBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4081' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glVertexArrayVertexBuffersEjjiPKjPKlPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4086' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glVertexArrayVertexBufferEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4091' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glVertexArrayElementBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4096' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glEnableVertexArrayAttribEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4101' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glDisableVertexArrayAttribEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4106' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glCreateVertexArraysEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4111' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGetTextureParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4116' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glGetTextureParameterIuivEjjPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4121' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetTextureParameterIivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4126' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGetTextureParameterfvEjjPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4131' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glGetTextureLevelParameterivEjijPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4136' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glGetTextureLevelParameterfvEjijPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4141' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetCompressedTextureImageEjiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4146' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility17glGetTextureImageEjijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4151' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility17glBindTextureUnitEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4156' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGenerateTextureMipmapEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4161' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glTextureParameterivEjjPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4166' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glTextureParameterIuivEjjPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4171' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glTextureParameterIivEjjPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4176' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glTextureParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4181' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glTextureParameterfvEjjPKf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4186' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glTextureParameterfEjjf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4191' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glCopyTextureSubImage3DEjiiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4196' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glCopyTextureSubImage2DEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4201' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glCopyTextureSubImage1DEjiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4206' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glCompressedTextureSubImage3DEjiiiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4211' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glCompressedTextureSubImage2DEjiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4216' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glCompressedTextureSubImage1DEjiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4221' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glTextureSubImage3DEjiiiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4226' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glTextureSubImage2DEjiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4231' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility19glTextureSubImage1DEjiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4236' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glTextureStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4241' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glTextureStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4246' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glTextureStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4251' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glTextureStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4256' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glTextureStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4261' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glTextureBufferRangeEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4266' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glTextureBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4271' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glCreateTexturesEjiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4276' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility33glGetNamedRenderbufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4281' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility37glNamedRenderbufferStorageMultisampleEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4286' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glNamedRenderbufferStorageEjjii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4291' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glCreateRenderbuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4296' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility42glGetNamedFramebufferAttachmentParameterivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4301' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility32glGetNamedFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4306' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glCheckNamedFramebufferStatusEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4311' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glBlitNamedFramebufferEjjiiiiiiiijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4316' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glClearNamedFramebufferfiEjjfi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4321' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glClearNamedFramebufferfvEjjiPKf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4326' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glClearNamedFramebufferuivEjjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4331' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glClearNamedFramebufferivEjjiPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4336' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility35glInvalidateNamedFramebufferSubDataEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4341' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility32glInvalidateNamedFramebufferDataEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4346' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glNamedFramebufferReadBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4351' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glNamedFramebufferDrawBuffersEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4356' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glNamedFramebufferDrawBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4361' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility30glNamedFramebufferTextureLayerEjjjii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4366' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glNamedFramebufferTextureEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4371' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility28glNamedFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4376' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility30glNamedFramebufferRenderbufferEjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4381' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glCreateFramebuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4386' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility23glGetNamedBufferSubDataEjliPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4391' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetNamedBufferPointervEjjPPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4396' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glGetNamedBufferParameteri64vEjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4401' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetNamedBufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4406' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glFlushMappedNamedBufferRangeEjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4411' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility18glUnmapNamedBufferEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4416' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility21glMapNamedBufferRangeEjlij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4421' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility16glMapNamedBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4426' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glClearNamedBufferSubDataEjjlijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4431' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility22glClearNamedBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4436' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glCopyNamedBufferSubDataEjjlli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4441' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glNamedBufferSubDataEjliPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4446' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility17glNamedBufferDataEjiPKvj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4451' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility20glNamedBufferStorageEjiPKvj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4456' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility15glCreateBuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4461' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility27glGetTransformFeedbacki64_vEjjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4466' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility25glGetTransformFeedbacki_vEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4471' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility24glGetTransformFeedbackivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4476' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility30glTransformFeedbackBufferRangeEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4481' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility29glTransformFeedbackBufferBaseEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4486' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility26glCreateTransformFeedbacksEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_compatibility.h' l='4491' u='m' c='_ZN34QOpenGLFunctions_4_5_Compatibility13glClipControlEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3499' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glTextureBarrierEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3504' u='m' c='_ZN25QOpenGLFunctions_4_5_Core13glReadnPixelsEiiiijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3509' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glGetnUniformuivEjiiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3514' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glGetnUniformivEjiiPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3519' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glGetnUniformfvEjiiPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3524' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glGetnUniformdvEjiiPd'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3529' u='m' c='_ZN25QOpenGLFunctions_4_5_Core14glGetnTexImageEjijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3534' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetnCompressedTexImageEjiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3539' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetGraphicsResetStatusEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3544' u='m' c='_ZN25QOpenGLFunctions_4_5_Core30glGetCompressedTextureSubImageEjiiiiiiiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3549' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glGetTextureSubImageEjiiiiiiijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3554' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glMemoryBarrierByRegionEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3559' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glCreateQueriesEjiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3564' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glCreateProgramPipelinesEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3569' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glCreateSamplersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3574' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetVertexArrayIndexed64ivEjjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3579' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glGetVertexArrayIndexedivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3584' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glGetVertexArrayivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3589' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glVertexArrayBindingDivisorEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3594' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glVertexArrayAttribLFormatEjjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3599' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glVertexArrayAttribIFormatEjjijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3604' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glVertexArrayAttribFormatEjjijhj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3609' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glVertexArrayAttribBindingEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3614' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glVertexArrayVertexBuffersEjjiPKjPKlPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3619' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glVertexArrayVertexBufferEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3624' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glVertexArrayElementBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3629' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glEnableVertexArrayAttribEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3634' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glDisableVertexArrayAttribEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3639' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glCreateVertexArraysEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3644' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGetTextureParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3649' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glGetTextureParameterIuivEjjPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3654' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetTextureParameterIivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3659' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGetTextureParameterfvEjjPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3664' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glGetTextureLevelParameterivEjijPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3669' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glGetTextureLevelParameterfvEjijPf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3674' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetCompressedTextureImageEjiiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3679' u='m' c='_ZN25QOpenGLFunctions_4_5_Core17glGetTextureImageEjijjiPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3684' u='m' c='_ZN25QOpenGLFunctions_4_5_Core17glBindTextureUnitEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3689' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGenerateTextureMipmapEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3694' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glTextureParameterivEjjPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3699' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glTextureParameterIuivEjjPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3704' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glTextureParameterIivEjjPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3709' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glTextureParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3714' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glTextureParameterfvEjjPKf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3719' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glTextureParameterfEjjf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3724' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glCopyTextureSubImage3DEjiiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3729' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glCopyTextureSubImage2DEjiiiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3734' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glCopyTextureSubImage1DEjiiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3739' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glCompressedTextureSubImage3DEjiiiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3744' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glCompressedTextureSubImage2DEjiiiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3749' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glCompressedTextureSubImage1DEjiiijiPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3754' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glTextureSubImage3DEjiiiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3759' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glTextureSubImage2DEjiiiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3764' u='m' c='_ZN25QOpenGLFunctions_4_5_Core19glTextureSubImage1DEjiiijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3769' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glTextureStorage3DMultisampleEjijiiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3774' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glTextureStorage2DMultisampleEjijiih'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3779' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glTextureStorage3DEjijiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3784' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glTextureStorage2DEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3789' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glTextureStorage1DEjiji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3794' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glTextureBufferRangeEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3799' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glTextureBufferEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3804' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glCreateTexturesEjiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3809' u='m' c='_ZN25QOpenGLFunctions_4_5_Core33glGetNamedRenderbufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3814' u='m' c='_ZN25QOpenGLFunctions_4_5_Core37glNamedRenderbufferStorageMultisampleEjijii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3819' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glNamedRenderbufferStorageEjjii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3824' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glCreateRenderbuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3829' u='m' c='_ZN25QOpenGLFunctions_4_5_Core42glGetNamedFramebufferAttachmentParameterivEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3834' u='m' c='_ZN25QOpenGLFunctions_4_5_Core32glGetNamedFramebufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3839' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glCheckNamedFramebufferStatusEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3844' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glBlitNamedFramebufferEjjiiiiiiiijj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3849' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glClearNamedFramebufferfiEjjfi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3854' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glClearNamedFramebufferfvEjjiPKf'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3859' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glClearNamedFramebufferuivEjjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3864' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glClearNamedFramebufferivEjjiPKi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3869' u='m' c='_ZN25QOpenGLFunctions_4_5_Core35glInvalidateNamedFramebufferSubDataEjiPKjiiii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3874' u='m' c='_ZN25QOpenGLFunctions_4_5_Core32glInvalidateNamedFramebufferDataEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3879' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glNamedFramebufferReadBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3884' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glNamedFramebufferDrawBuffersEjiPKj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3889' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glNamedFramebufferDrawBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3894' u='m' c='_ZN25QOpenGLFunctions_4_5_Core30glNamedFramebufferTextureLayerEjjjii'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3899' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glNamedFramebufferTextureEjjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3904' u='m' c='_ZN25QOpenGLFunctions_4_5_Core28glNamedFramebufferParameteriEjji'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3909' u='m' c='_ZN25QOpenGLFunctions_4_5_Core30glNamedFramebufferRenderbufferEjjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3914' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glCreateFramebuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3919' u='m' c='_ZN25QOpenGLFunctions_4_5_Core23glGetNamedBufferSubDataEjliPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3924' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetNamedBufferPointervEjjPPv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3929' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glGetNamedBufferParameteri64vEjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3934' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetNamedBufferParameterivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3939' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glFlushMappedNamedBufferRangeEjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3944' u='m' c='_ZN25QOpenGLFunctions_4_5_Core18glUnmapNamedBufferEj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3949' u='m' c='_ZN25QOpenGLFunctions_4_5_Core21glMapNamedBufferRangeEjlij'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3954' u='m' c='_ZN25QOpenGLFunctions_4_5_Core16glMapNamedBufferEjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3959' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glClearNamedBufferSubDataEjjlijjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3964' u='m' c='_ZN25QOpenGLFunctions_4_5_Core22glClearNamedBufferDataEjjjjPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3969' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glCopyNamedBufferSubDataEjjlli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3974' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glNamedBufferSubDataEjliPKv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3979' u='m' c='_ZN25QOpenGLFunctions_4_5_Core17glNamedBufferDataEjiPKvj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3984' u='m' c='_ZN25QOpenGLFunctions_4_5_Core20glNamedBufferStorageEjiPKvj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3989' u='m' c='_ZN25QOpenGLFunctions_4_5_Core15glCreateBuffersEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3994' u='m' c='_ZN25QOpenGLFunctions_4_5_Core27glGetTransformFeedbacki64_vEjjjPl'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='3999' u='m' c='_ZN25QOpenGLFunctions_4_5_Core25glGetTransformFeedbacki_vEjjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='4004' u='m' c='_ZN25QOpenGLFunctions_4_5_Core24glGetTransformFeedbackivEjjPi'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='4009' u='m' c='_ZN25QOpenGLFunctions_4_5_Core30glTransformFeedbackBufferRangeEjjjli'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='4014' u='m' c='_ZN25QOpenGLFunctions_4_5_Core29glTransformFeedbackBufferBaseEjjj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='4019' u='m' c='_ZN25QOpenGLFunctions_4_5_Core26glCreateTransformFeedbacksEiPj'/>
<use f='qtbase-6.5.0/src/opengl/qopenglfunctions_4_5_core.h' l='4024' u='m' c='_ZN25QOpenGLFunctions_4_5_Core13glClipControlEjj'/>
