<dec f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='41' type='qreal'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='48' u='r' c='_ZNK12QPainterPath7Elementcv7QPointFEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='51' u='r' c='_ZNK12QPainterPath7ElementeqERKS0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='51' u='r' c='_ZNK12QPainterPath7ElementeqERKS0_'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='60' u='r' c='_ZN20QVectorPathConverter15QVectorPathDataC1ERK5QListIN12QPainterPath7ElementEEjb'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='186' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='193' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='202' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='222' u='r' c='_ZNK19QPainterPathPrivate8isClosedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='222' u='r' c='_ZNK19QPainterPathPrivate8isClosedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='231' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='231' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='232' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='232' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='234' u='w' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='234' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='236' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='486' u='w' c='_ZN12QPainterPath20setElementPositionAtEidd'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='697' u='w' c='_ZN12QPainterPath6moveToERK7QPointF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='858' u='r' c='_ZN12QPainterPath6quadToERK7QPointFS2_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='987' u='r' c='_ZNK12QPainterPath15currentPositionEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1515' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1522' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1525' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1576' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1579' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1584' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1585' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1586' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1587' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2001' u='r' c='_ZL29qt_painterpath_check_crossingPK12QPainterPathRK6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2126' u='w' c='_ZN12QPainterPath9translateEdd'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2425' u='r' c='_ZlsR11QDataStreamRK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3310' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3319' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3319' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3320' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3320' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3357' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3362' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3362' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3363' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3363' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3374' u='r' c='_Zls6QDebugRK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1471' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1474' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1476' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1482' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1485' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='323' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='323' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='325' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='329' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='334' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='335' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='336' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='346' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='346' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='213' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='216' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='222' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='223' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='224' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='234' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='r' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='675' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='700' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='703' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
