<dec f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='40' type='qreal'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='48' u='r' c='_ZNK12QPainterPath7Elementcv7QPointFEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='50' u='r' c='_ZNK12QPainterPath7ElementeqERKS0_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.h' l='50' u='r' c='_ZNK12QPainterPath7ElementeqERKS0_'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='59' u='r' c='_ZN20QVectorPathConverter15QVectorPathDataC1ERK5QListIN12QPainterPath7ElementEEjb'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='185' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='192' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='201' u='w' c='_ZNK11QVectorPath20convertToPainterPathEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='222' u='r' c='_ZNK19QPainterPathPrivate8isClosedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='222' u='r' c='_ZNK19QPainterPathPrivate8isClosedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='231' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='231' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='232' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='232' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='233' u='w' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='233' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath_p.h' l='236' u='r' c='_ZN19QPainterPathPrivate5closeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='485' u='w' c='_ZN12QPainterPath20setElementPositionAtEidd'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='696' u='w' c='_ZN12QPainterPath6moveToERK7QPointF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='858' u='r' c='_ZN12QPainterPath6quadToERK7QPointFS2_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='987' u='r' c='_ZNK12QPainterPath15currentPositionEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1515' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1522' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1525' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1534' u='r' c='_ZNK12QPainterPath10toReversedEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1576' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1579' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1584' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1585' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1586' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='1587' u='r' c='_ZNK12QPainterPath17toSubpathPolygonsERK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2001' u='r' c='_ZL29qt_painterpath_check_crossingPK12QPainterPathRK6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2125' u='w' c='_ZN12QPainterPath9translateEdd'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='2425' u='r' c='_ZlsR11QDataStreamRK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3309' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3317' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3317' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3318' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3318' u='r' c='_ZNK12QPainterPath19computeBoundingRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3356' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3360' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3360' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3361' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3361' u='r' c='_ZNK12QPainterPath23computeControlPointRectEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpainterpath.cpp' l='3374' u='r' c='_Zls6QDebugRK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1470' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1473' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1479' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1482' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='1485' u='r' c='_ZN12QPathClipper10pathToRectERK12QPainterPathP6QRectF'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='322' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='322' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='325' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='329' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='334' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='335' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='336' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='345' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qpdf.cpp' l='345' u='r' c='_ZN4QPdf12generatePathERK12QPainterPathRK10QTransformNS_9PathFlagsE'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='213' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='216' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='222' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='223' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='224' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qstroker.cpp' l='234' u='r' c='_ZN11QStrokerOps10strokePathERK12QPainterPathPvRK10QTransform'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='r' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/painting/qtransform.cpp' l='1684' u='w' c='_ZNK10QTransform3mapERK12QPainterPath'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='674' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='699' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
<use f='qtbase-6.5.0/src/gui/text/qfontsubset.cpp' l='702' u='r' c='_ZL11convertPathRK12QPainterPathP5QListI9TTF_POINTEPS2_IiEd'/>
