<use f='qtbase-6.5.0/src/gui/painting/qpathclipper_p.h' l='145' u='w' c='_ZN13QPathSegments7SegmentC1Eiii'/>
<dec f='qtbase-6.5.0/src/gui/painting/qpathclipper_p.h' l='154' type='int'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper_p.h' l='346' u='r' c='_ZNK13QPathSegments6lineAtEi'/>
<offset>32</offset>
<doc f='qtbase-6.5.0/src/gui/painting/qpathclipper_p.h' l='153'>// vertices</doc>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='745' u='w' c='_ZN13QPathSegments11mergePointsEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='745' u='r' c='_ZN13QPathSegments11mergePointsEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpathclipper.cpp' l='785' u='r' c='_ZN11QWingedEdge15intersectAndAddEv'/>
