<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='485' u='w' c='_ZN6QRectFC1Ev'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='499' u='r' c='_ZNK6QRectF6bottomEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='511' u='r' c='_ZNK6QRectF11bottomRightEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='513' u='r' c='_ZNK6QRectF10bottomLeftEv'/>
<dec f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='603' type='qreal'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='621' u='w' c='_ZN6QRectFC1Edddd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='626' u='w' c='_ZN6QRectFC1ERK7QPointFRK6QSizeF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='632' u='w' c='_ZN6QRectFC1ERK7QPointFS2_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='637' u='w' c='_ZN6QRectFC1ERK5QRect'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='645' u='r' c='_ZNK6QRectF6isNullEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='648' u='r' c='_ZNK6QRectF7isEmptyEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='653' u='r' c='_ZNK6QRectF7isValidEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='668' u='w' c='_ZN6QRectF6setTopEd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='671' u='w' c='_ZN6QRectF9setBottomEd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='686' u='r' c='_ZNK6QRectF6centerEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='698' u='r' c='_ZN6QRectF10moveBottomEd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='713' u='r' c='_ZN6QRectF10moveCenterERK7QPointF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='719' u='r' c='_ZNK6QRectF6heightEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='722' u='r' c='_ZNK6QRectF4sizeEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='750' u='r' c='_ZNK6QRectF10translatedEdd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='754' u='r' c='_ZNK6QRectF10translatedERK7QPointF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='764' u='r' c='_ZNK6QRectF7getRectEPdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='772' u='w' c='_ZN6QRectF7setRectEdddd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='780' u='r' c='_ZNK6QRectF9getCoordsEPdS0_S0_S0_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='788' u='w' c='_ZN6QRectF9setCoordsEdddd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='796' u='w' c='_ZN6QRectF6adjustEdddd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='801' u='r' c='_ZNK6QRectF8adjustedEdddd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='808' u='w' c='_ZN6QRectF9setHeightEd'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='813' u='w' c='_ZN6QRectF7setSizeERK6QSizeF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='853' u='r' c='_ZNK6QRectF6toRectEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='878' u='r' c='_ZNK6QRectF12marginsAddedERK9QMarginsF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.h' l='884' u='r' c='_ZNK6QRectF14marginsRemovedERK9QMarginsF'/>
<offset>192</offset>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1521' u='r' c='_ZNK6QRectF10normalizedEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1522' u='r' c='_ZNK6QRectF10normalizedEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1523' u='w' c='_ZNK6QRectF10normalizedEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1523' u='r' c='_ZNK6QRectF10normalizedEv'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1955' u='r' c='_ZNK6QRectF8containsERK7QPointF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1956' u='r' c='_ZNK6QRectF8containsERK7QPointF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='1958' u='r' c='_ZNK6QRectF8containsERK7QPointF'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2010' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2011' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2013' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2019' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2020' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2022' u='r' c='_ZNK6QRectF8containsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2147' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2148' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2150' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2152' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2153' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2157' u='r' c='_ZNK6QRectForERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2210' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2211' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2213' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2219' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2220' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2222' u='r' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2233' u='w' c='_ZNK6QRectFanERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2288' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2289' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2291' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2297' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2298' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2300' u='r' c='_ZNK6QRectF10intersectsERKS_'/>
<use f='qtbase-6.5.0/src/corelib/tools/qrect.cpp' l='2335' u='r' c='_ZNK6QRectF13toAlignedRectEv'/>
