<dec f='qtbase-6.5.0/src/gui/rhi/qrhi_p.h' l='268' type='5'/>
<doc f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='1573'>\value Compute Compute stage. Must be used only when the QRhi::Compute
    feature is supported.</doc>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4393' c='_ZL14toGlShaderTypeN15QRhiShaderStage4TypeE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='4675' c='_ZL13toShaderStageN15QRhiShaderStage4TypeE'/>
