<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2_p_p.h' l='952' u='w' c='_ZN9QRhiGles24CapsC1Ev'/>
<dec f='qtbase-6.5.0/src/gui/rhi/qrhigles2_p_p.h' l='1004' type='uint'/>
<offset>470</offset>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='840' u='w' c='_ZN9QRhiGles26createE6QFlagsIN4QRhi4FlagEE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='842' u='w' c='_ZN9QRhiGles26createE6QFlagsIN4QRhi4FlagEE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='844' u='r' c='_ZN9QRhiGles26createE6QFlagsIN4QRhi4FlagEE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1270' u='r' c='_ZNK9QRhiGles218isFeatureSupportedEN4QRhi7FeatureE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1930' u='r' c='_ZN9QRhiGles213beginExternalEP17QRhiCommandBuffer'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='3374' u='r' c='_ZN9QRhiGles220executeCommandBufferEP17QRhiCommandBuffer'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='3400' u='r' c='_ZN9QRhiGles220executeCommandBufferEP17QRhiCommandBuffer'/>
