<dec f='qtbase-6.5.0/src/gui/rhi/qrhi_p.h' l='1663' type='13'/>
<doc f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='555'>\value Compute Indicates that compute shaders, image load/store, and
    storage buffers are supported. OpenGL older than 4.3 and OpenGL ES older
    than 3.1 have no compute support.</doc>
<use f='qtbase-6.5.0/src/gui/rhi/qrhigles2.cpp' l='1269' c='_ZNK9QRhiGles218isFeatureSupportedEN4QRhi7FeatureE'/>
