<dec f='qtbase-6.5.0/src/gui/rhi/qrhi_p.h' l='1632' type='4'/>
<use f='qtbase-6.5.0/src/gui/painting/qbackingstorerhisupport.cpp' l='221' u='r' c='_ZN23QBackingStoreRhiSupport15apiToRhiBackendEN30QPlatformBackingStoreRhiConfig3ApiE'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='5573' c='_ZN4QRhi6createENS_14ImplementationEP14QRhiInitParams6QFlagsINS_4FlagEEP17QRhiNativeHandles'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='5627' u='r' c='_ZN4QRhi5probeENS_14ImplementationEP14QRhiInitParams'/>
<use f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='5705' c='_ZN4QRhi11backendNameENS_14ImplementationE'/>
<doc f='qtbase-6.5.0/src/gui/rhi/qrhi.cpp' l='407'>\value Metal</doc>
