<dec f='qtbase-6.5.0/src/network/ssl/qssl.h' l='33' type='3'/>
<doc f='qtbase-6.5.0/src/network/ssl/qssl.cpp' l='38'>\value Ec  The Elliptic Curve algorithm.
    </doc>
<use f='qtbase-6.5.0/src/network/ssl/qtlsbackend.cpp' l='1380' u='r' c='_ZNK11QTlsPrivate6TlsKey9pemHeaderEv'/>
<use f='qtbase-6.5.0/src/network/ssl/qtlsbackend.cpp' l='1401' u='r' c='_ZNK11QTlsPrivate6TlsKey9pemFooterEv'/>
<use f='qtbase-6.5.0/src/plugins/tls/shared/qx509_generic.cpp' l='243' u='r' c='_ZN11QTlsPrivate22X509CertificateGeneric5parseERK10QByteArray'/>
