<dec f='qtbase-6.5.0/src/corelib/global/qnamespace.h' l='211' type='11'/>
<use f='qtbase-6.5.0/src/opengl/qopenglcompositor.cpp' l='320' u='r' c='_ZN17QOpenGLCompositor19ensureCorrectZOrderEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglcompositor.cpp' l='320' u='r' c='_ZN17QOpenGLCompositor19ensureCorrectZOrderEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglcompositor.cpp' l='321' u='r' c='_ZN17QOpenGLCompositor19ensureCorrectZOrderEv'/>
<use f='qtbase-6.5.0/src/opengl/qopenglcompositor.cpp' l='321' u='r' c='_ZN17QOpenGLCompositor19ensureCorrectZOrderEv'/>
<use f='qtbase-6.5.0/src/widgets/graphicsview/qgraphicswidget_p.cpp' l='307' u='r' c='_ZN22QGraphicsWidgetPrivate17adjustWindowFlagsEP6QFlagsIN2Qt10WindowTypeEE'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qshortcut_widgets.cpp' l='153' u='r' c='_ZL20correctWidgetContextN2Qt15ShortcutContextEP7QWidgetS2_'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidget.cpp' l='929' u='r' c='_ZN14QWidgetPrivate11adjustFlagsER6QFlagsIN2Qt10WindowTypeEEP7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidget.cpp' l='6880' u='r' c='_ZNK7QWidget14isActiveWindowEv'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidget.cpp' l='6885' u='r' c='_ZNK7QWidget14isActiveWindowEv'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidget.cpp' l='8016' u='r' c='_ZN14QWidgetPrivate11show_helperEv'/>
<use f='qtbase-6.5.0/src/widgets/styles/qcommonstyle.cpp' l='3528' u='r' c='_ZNK12QCommonStyle18drawComplexControlEN6QStyle14ComplexControlEPK19QStyleOptionComplexP8QPainterPK7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/styles/qcommonstyle.cpp' l='4501' u='r' c='_ZNK12QCommonStyle11pixelMetricEN6QStyle11PixelMetricEPK12QStyleOptionPK7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/styles/qstylesheetstyle.cpp' l='3559' u='r' c='_ZNK16QStyleSheetStyle18drawComplexControlEN6QStyle14ComplexControlEPK19QStyleOptionComplexP8QPainterPK7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qdockwidget.cpp' l='1175' u='r' c='_ZN18QDockWidgetPrivate14setWindowStateEbbRK5QRect'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmainwindowlayout.cpp' l='2908' u='r' c='_ZN17QMainWindowLayout22createTabbedDockWindowEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenu.cpp' l='98' u='r' c='_ZN12QTornOffMenuC1EP5QMenu'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbar.cpp' l='104' u='r' c='_ZN15QToolBarPrivate17updateWindowFlagsEbb'/>
