<dec f='qtbase-6.5.0/src/gui/painting/qrasterdefs_p.h' l='834' type='int'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster_p.h' l='368' u='w' c='_ZN9QClipData10appendSpanEiiii'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='126' u='r' c='_Z9drawPixelP16QCosmeticStrokeriii'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='136' u='w' c='_Z9drawPixelP16QCosmeticStrokeriii'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3815' u='r' c='_ZL19blend_color_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3816' u='r' c='_ZL19blend_color_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3822' u='r' c='_ZL19blend_color_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3825' u='r' c='_ZL19blend_color_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3844' u='r' c='_ZL16blend_color_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3864' u='r' c='_ZL16blend_color_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3893' u='r' c='_ZL25blend_color_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3894' u='r' c='_ZL25blend_color_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3900' u='r' c='_ZL25blend_color_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3903' u='r' c='_ZL25blend_color_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3939' u='r' c='_ZL22blend_color_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3940' u='r' c='_ZL22blend_color_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3946' u='r' c='_ZL22blend_color_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3949' u='r' c='_ZL22blend_color_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3977' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3982' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4192' u='r' c='_ZL27blend_untransformed_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4207' u='r' c='_ZL27blend_untransformed_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4210' u='r' c='_ZL27blend_untransformed_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4250' u='r' c='_ZL33blend_untransformed_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4265' u='r' c='_ZL33blend_untransformed_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4268' u='r' c='_ZL33blend_untransformed_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4308' u='r' c='_ZL30blend_untransformed_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4323' u='r' c='_ZL30blend_untransformed_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4326' u='r' c='_ZL30blend_untransformed_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4364' u='r' c='_ZL24blend_untransformed_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4376' u='r' c='_ZL24blend_untransformed_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4466' u='r' c='_ZL26blend_untransformed_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4476' u='r' c='_ZL26blend_untransformed_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4518' u='r' c='_ZL19blend_tiled_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4530' u='r' c='_ZL19blend_tiled_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4533' u='r' c='_ZL19blend_tiled_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4573' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4576' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4625' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4637' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4640' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4684' u='r' c='_ZL22blend_tiled_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4696' u='r' c='_ZL22blend_tiled_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4699' u='r' c='_ZL22blend_tiled_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4740' u='r' c='_ZL16blend_tiled_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4752' u='r' c='_ZL16blend_tiled_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4798' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4812' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4830' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4848' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4996' u='r' c='_ZL28blend_vertical_gradient_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5023' u='r' c='_ZL23blend_vertical_gradientiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5324' u='r' c='_ZL23qt_alphamapblit_genericP13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5331' u='r' c='_ZL23qt_alphamapblit_genericP13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5703' u='r' c='_ZL23qt_alphargbblit_genericP13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5710' u='r' c='_ZL23qt_alphargbblit_genericP13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1149' u='r' c='gray_render_span'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1238' u='r' c='gray_hline'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1287' u='w' c='gray_hline'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='1424' u='w' c='_ZL19fillRect_normalizedRK5QRectP9QSpanDataP25QRasterPaintEnginePrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2677' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2706' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2738' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3414' u='w' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3440' u='w' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3844' u='w' c='_ZN9QClipData10initializeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3881' u='w' c='_ZN9QClipData10initializeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3918' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3919' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3930' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3931' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3933' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4033' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4033' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4037' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4037' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4038' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4038' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4039' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4044' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4044' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4063' u='w' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4063' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4117' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4124' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4747' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4753' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4759' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4765' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4765' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4775' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4775' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4781' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4781' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4784' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4784' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4790' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4790' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qrasterizer.cpp' l='73' u='w' c='_ZN11QSpanBuffer7addSpanEiiii'/>
