<dec f='qtbase-6.5.0/src/gui/painting/qrasterdefs_p.h' l='832' type='int'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster_p.h' l='366' u='w' c='_ZN9QClipData10appendSpanEiiii'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='125' u='r' c='_Z9drawPixelP16QCosmeticStrokeriii'/>
<use f='qtbase-6.5.0/src/gui/painting/qcosmeticstroker.cpp' l='134' u='w' c='_Z9drawPixelP16QCosmeticStrokeriii'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3811' u='r' c='_ZL19blend_color_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3844' u='r' c='_ZL16blend_color_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3864' u='r' c='_ZL16blend_color_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3889' u='r' c='_ZL25blend_color_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3935' u='r' c='_ZL22blend_color_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3976' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3982' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3996' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='3999' u='r' c='_Z11handleSpansiPK11QT_FT_Span_PK9QSpanDataRK8Operator'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4189' u='r' c='_ZL27blend_untransformed_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4247' u='r' c='_ZL33blend_untransformed_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4305' u='r' c='_ZL30blend_untransformed_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4361' u='r' c='_ZL24blend_untransformed_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4463' u='r' c='_ZL26blend_untransformed_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4515' u='r' c='_ZL19blend_tiled_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4517' u='r' c='_ZL19blend_tiled_genericiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4572' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4575' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4622' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4624' u='r' c='_ZL25blend_tiled_generic_rgb64iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4681' u='r' c='_ZL22blend_tiled_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4683' u='r' c='_ZL22blend_tiled_generic_fpiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4737' u='r' c='_ZL16blend_tiled_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4739' u='r' c='_ZL16blend_tiled_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4795' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4797' u='r' c='_ZL18blend_tiled_rgb565iPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='4997' u='r' c='_ZL28blend_vertical_gradient_argbiPK11QT_FT_Span_Pv'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5319' u='r' c='_ZL23qt_alphamapblit_genericP13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5320' u='r' c='_ZL23qt_alphamapblit_genericP13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5461' u='r' c='_Z23qt_alphamapblit_quint16P13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5462' u='r' c='_Z23qt_alphamapblit_quint16P13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5518' u='r' c='_ZL22qt_alphamapblit_argb32P13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5519' u='r' c='_ZL22qt_alphamapblit_argb32P13QRasterBufferiiRK7QRgba64PKhiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5698' u='r' c='_ZL23qt_alphargbblit_genericP13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5699' u='r' c='_ZL23qt_alphargbblit_genericP13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5837' u='r' c='_ZL22qt_alphargbblit_argb32P13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qdrawhelper.cpp' l='5838' u='r' c='_ZL22qt_alphargbblit_argb32P13QRasterBufferiiRK7QRgba64PKjiiiPK9QClipDatab'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1156' u='r' c='gray_render_span'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1239' u='r' c='gray_hline'/>
<use f='qtbase-6.5.0/src/gui/painting/qgrayraster.c' l='1285' u='w' c='gray_hline'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='1422' u='w' c='_ZL19fillRect_normalizedRK5QRectP9QSpanDataP25QRasterPaintEnginePrivate'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2676' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2705' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='2737' u='w' c='_ZN18QRasterPaintEngine11alphaPenBltEPKviiiiiib'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3413' u='w' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3421' u='r' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3421' u='r' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3439' u='w' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3447' u='r' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3447' u='r' c='_ZN18QRasterPaintEngine10drawBitmapERK7QPointFRK6QImageP9QSpanData'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3842' u='w' c='_ZN9QClipData10initializeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3879' u='w' c='_ZN9QClipData10initializeEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3923' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3924' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='3939' u='r' c='_ZN9QClipData5fixupEv'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4046' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4048' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4061' u='w' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4062' u='r' c='_ZL18qt_intersect_spansPK9QClipDataPiPK11QT_FT_Span_S5_PPS3_i'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4126' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4126' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4131' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4132' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4133' u='w' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4135' u='r' c='_ZL18qt_intersect_spansRP11QT_FT_Span_iRK5QRect'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4745' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4746' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4751' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4757' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4757' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4763' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4768' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4768' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4773' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4773' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4774' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4774' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4779' u='w' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4779' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4780' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qpaintengine_raster.cpp' l='4780' u='r' c='_ZL17drawEllipsePointsiiiRK5QRectS1_PFviPK11QT_FT_Span_PvES7_P9QSpanDataS9_'/>
<use f='qtbase-6.5.0/src/gui/painting/qrasterizer.cpp' l='71' u='w' c='_ZN11QSpanBuffer7addSpanEiiii'/>
