<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='160' u='w' c='_ZN10QTextBlockC1EP20QTextDocumentPrivatei'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='161' u='w' c='_ZN10QTextBlockC1Ev'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='162' u='w' c='_ZN10QTextBlockC1ERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='162' u='r' c='_ZN10QTextBlockC1ERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='163' u='w' c='_ZN10QTextBlockaSERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='163' u='r' c='_ZN10QTextBlockaSERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='167' u='r' c='_ZNK10QTextBlockeqERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='167' u='r' c='_ZNK10QTextBlockeqERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='168' u='r' c='_ZNK10QTextBlockneERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='168' u='r' c='_ZNK10QTextBlockneERKS_'/>
<dec f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='245' type='QTextDocumentPrivate *'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/text/qtextdocument_p.h' l='210' u='r' c='_ZN20QTextDocumentPrivate5blockERK10QTextBlock'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocument_p.h' l='278' u='r' c='_ZN20QTextDocumentPrivate3getER10QTextBlock'/>
<use f='qtbase-6.5.0/src/gui/text/qtextdocument_p.h' l='283' u='r' c='_ZN20QTextDocumentPrivate3getERK10QTextBlock'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='815' u='r' c='_ZNK10QTextBlock7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='815' u='r' c='_ZNK10QTextBlock7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='926' u='r' c='_ZNK10QTextBlock8positionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='929' u='r' c='_ZNK10QTextBlock8positionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='942' u='r' c='_ZNK10QTextBlock6lengthEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='945' u='r' c='_ZNK10QTextBlock6lengthEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='954' u='r' c='_ZNK10QTextBlock8containsEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='957' u='r' c='_ZNK10QTextBlock8containsEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='958' u='r' c='_ZNK10QTextBlock8containsEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='974' u='r' c='_ZNK10QTextBlock6layoutEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='977' u='r' c='_ZNK10QTextBlock6layoutEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='992' u='r' c='_ZN10QTextBlock11clearLayoutEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='995' u='r' c='_ZN10QTextBlock11clearLayoutEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1007' u='r' c='_ZNK10QTextBlock11blockFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1010' u='r' c='_ZNK10QTextBlock11blockFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1010' u='r' c='_ZNK10QTextBlock11blockFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1021' u='r' c='_ZNK10QTextBlock16blockFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1024' u='r' c='_ZNK10QTextBlock16blockFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1036' u='r' c='_ZNK10QTextBlock10charFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1039' u='r' c='_ZNK10QTextBlock10charFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1050' u='r' c='_ZNK10QTextBlock15charFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1053' u='r' c='_ZNK10QTextBlock15charFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1073' u='r' c='_ZNK10QTextBlock13textDirectionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1077' u='r' c='_ZNK10QTextBlock13textDirectionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1080' u='r' c='_ZNK10QTextBlock13textDirectionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1081' u='r' c='_ZNK10QTextBlock13textDirectionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1117' u='r' c='_ZNK10QTextBlock4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1120' u='r' c='_ZNK10QTextBlock4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1125' u='r' c='_ZNK10QTextBlock4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1126' u='r' c='_ZNK10QTextBlock4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1147' u='r' c='_ZNK10QTextBlock11textFormatsEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1150' u='r' c='_ZNK10QTextBlock11textFormatsEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1157' u='r' c='_ZNK10QTextBlock11textFormatsEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1158' u='r' c='_ZNK10QTextBlock11textFormatsEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1192' u='r' c='_ZNK10QTextBlock8documentEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1192' u='r' c='_ZNK10QTextBlock8documentEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1205' u='r' c='_ZNK10QTextBlock8textListEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1217' u='r' c='_ZNK10QTextBlock8userDataEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1220' u='r' c='_ZNK10QTextBlock8userDataEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1251' u='r' c='_ZN10QTextBlock11setUserDataEP18QTextBlockUserData'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1254' u='r' c='_ZN10QTextBlock11setUserDataEP18QTextBlockUserData'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1267' u='r' c='_ZNK10QTextBlock9userStateEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1270' u='r' c='_ZNK10QTextBlock9userStateEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1282' u='r' c='_ZN10QTextBlock12setUserStateEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1285' u='r' c='_ZN10QTextBlock12setUserStateEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1298' u='r' c='_ZNK10QTextBlock8revisionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1301' u='r' c='_ZNK10QTextBlock8revisionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1314' u='r' c='_ZN10QTextBlock11setRevisionEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1317' u='r' c='_ZN10QTextBlock11setRevisionEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1330' u='r' c='_ZNK10QTextBlock9isVisibleEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1333' u='r' c='_ZNK10QTextBlock9isVisibleEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1346' u='r' c='_ZN10QTextBlock10setVisibleEb'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1349' u='r' c='_ZN10QTextBlock10setVisibleEb'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1364' u='r' c='_ZNK10QTextBlock11blockNumberEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1366' u='r' c='_ZNK10QTextBlock11blockNumberEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1380' u='r' c='_ZNK10QTextBlock15firstLineNumberEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1382' u='r' c='_ZNK10QTextBlock15firstLineNumberEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1395' u='r' c='_ZN10QTextBlock12setLineCountEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1397' u='r' c='_ZN10QTextBlock12setLineCountEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1408' u='r' c='_ZNK10QTextBlock9lineCountEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1410' u='r' c='_ZNK10QTextBlock9lineCountEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1422' u='r' c='_ZNK10QTextBlock5beginEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1427' u='r' c='_ZNK10QTextBlock5beginEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1428' u='r' c='_ZNK10QTextBlock5beginEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1429' u='r' c='_ZNK10QTextBlock5beginEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1440' u='r' c='_ZNK10QTextBlock3endEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1445' u='r' c='_ZNK10QTextBlock3endEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1446' u='r' c='_ZNK10QTextBlock3endEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1447' u='r' c='_ZNK10QTextBlock3endEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1464' u='r' c='_ZNK10QTextBlock4nextEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1464' u='r' c='_ZNK10QTextBlock4nextEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1477' u='r' c='_ZNK10QTextBlock8previousEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1480' u='r' c='_ZNK10QTextBlock8previousEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1480' u='r' c='_ZNK10QTextBlock8previousEv'/>
