<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='258' u='w' c='_ZN13QTextFragmentC1EPK20QTextDocumentPrivateii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='259' u='w' c='_ZN13QTextFragmentC1Ev'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='260' u='w' c='_ZN13QTextFragmentC1ERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='260' u='r' c='_ZN13QTextFragmentC1ERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='261' u='w' c='_ZN13QTextFragmentaSERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='261' u='r' c='_ZN13QTextFragmentaSERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='263' u='r' c='_ZNK13QTextFragment7isValidEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='265' u='r' c='_ZNK13QTextFragmenteqERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='265' u='r' c='_ZNK13QTextFragmenteqERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='266' u='r' c='_ZNK13QTextFragmentneERKS_'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='266' u='r' c='_ZNK13QTextFragmentneERKS_'/>
<dec f='qtbase-6.5.0/src/gui/text/qtextobject.h' l='282' type='const QTextDocumentPrivate *'/>
<offset>0</offset>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1642' u='r' c='_ZNK13QTextFragment9glyphRunsEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1645' u='r' c='_ZNK13QTextFragment9glyphRunsEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1647' u='r' c='_ZNK13QTextFragment9glyphRunsEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1650' u='r' c='_ZNK13QTextFragment9glyphRunsEii'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1673' u='r' c='_ZNK13QTextFragment8positionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1676' u='r' c='_ZNK13QTextFragment8positionEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1686' u='r' c='_ZNK13QTextFragment6lengthEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1692' u='r' c='_ZNK13QTextFragment6lengthEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1693' u='r' c='_ZNK13QTextFragment6lengthEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1704' u='r' c='_ZNK13QTextFragment8containsEi'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1717' u='r' c='_ZNK13QTextFragment10charFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1719' u='r' c='_ZNK13QTextFragment10charFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1720' u='r' c='_ZNK13QTextFragment10charFormatEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1731' u='r' c='_ZNK13QTextFragment15charFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1733' u='r' c='_ZNK13QTextFragment15charFormatIndexEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1744' u='r' c='_ZNK13QTextFragment4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1748' u='r' c='_ZNK13QTextFragment4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1751' u='r' c='_ZNK13QTextFragment4textEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextobject.cpp' l='1753' u='r' c='_ZNK13QTextFragment4textEv'/>
