<dec f='qtbase-6.5.0/src/gui/text/qfontdatabase_p.h' l='32' type='QChar::Script'/>
<use f='qtbase-6.5.0/src/gui/text/qfontdatabase_p.h' l='37' u='r' c='_ZeqRK23QtFontFallbacksCacheKeyS1_'/>
<use f='qtbase-6.5.0/src/gui/text/qfontdatabase_p.h' l='37' u='r' c='_ZeqRK23QtFontFallbacksCacheKeyS1_'/>
<use f='qtbase-6.5.0/src/gui/text/qfontdatabase_p.h' l='54' u='r' c='_Z5qHashRK23QtFontFallbacksCacheKeym'/>
<offset>256</offset>
