<dec f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout_p.h' l='37' type='QAction *'/>
<offset>192</offset>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbar.cpp' l='809' u='r' c='_ZNK8QToolBar8actionAtERK6QPoint'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='36' u='w' c='_ZN12QToolBarItemC1EP7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='42' u='r' c='_ZNK12QToolBarItem7isEmptyEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='42' u='r' c='_ZNK12QToolBarItem7isEmptyEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='70' u='r' c='_ZN14QToolBarLayoutD1Ev'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='147' u='r' c='_ZN14QToolBarLayout6takeAtEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='149' u='r' c='_ZN14QToolBarLayout6takeAtEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='177' u='r' c='_ZNK14QToolBarLayout7indexOfEPK7QAction'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='309' u='r' c='_ZL19defaultWidgetActionP12QToolBarItem'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='521' u='r' c='_ZN14QToolBarLayout13layoutActionsERK5QSize'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qtoolbarlayout.cpp' l='718' u='w' c='_ZN14QToolBarLayout10createItemEP7QAction'/>
