<use f='qtbase-6.5.0/src/plugins/platforms/eglfs/api/qeglfsintegration.cpp' l='113' macro='1' u='r' c='_ZN17QEglFSIntegration7destroyEv'/>
<use f='qtbase-6.5.0/src/plugins/platforms/eglfs/api/qeglfsscreen.cpp' l='192' macro='1' u='r' c='_ZNK12QEglFSScreen10grabWindowEyiiii'/>
<use f='qtbase-6.5.0/src/widgets/graphicsview/qgraphicsanchorlayout_p.cpp' l='2557' macro='1' u='r' c='_ZN28QGraphicsAnchorLayoutPrivate28identifyNonFloatItems_helperEPKN22QtGraphicsAnchorLayout10AnchorDataEP4QSetIP19QGraphicsLayoutItemE'/>
<use f='qtbase-6.5.0/src/widgets/itemviews/qabstractitemview.cpp' l='1122' macro='1' u='r' c='_ZN17QAbstractItemView5resetEv'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='101' macro='1' u='r' c='_ZN15QGestureManager27unregisterGestureRecognizerEN2Qt11GestureTypeE'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='112' macro='1' u='r' c='_ZN15QGestureManager27unregisterGestureRecognizerEN2Qt11GestureTypeE'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='318' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='333' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='335' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='337' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='339' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='341' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='361' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='376' macro='1' u='r' c='_ZN15QGestureManager26filterEventThroughContextsERK9QMultiMapIP7QObjectN2Qt11GestureTypeEEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='553' macro='1' u='r' c='_ZN15QGestureManager17getGestureTargetsERK4QSetIP8QGestureEP5QHashIP7QWidget5QListIS2_EESC_'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qgesturemanager.cpp' l='662' macro='1' u='r' c='_ZN15QGestureManager13deliverEventsERK4QSetIP8QGestureEPS3_'/>
<use f='qtbase-6.5.0/src/widgets/kernel/qwidgetrepaintmanager.cpp' l='52' macro='1' u='r' c='_ZNK27QPlatformTextureListWatcher8isLockedEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='674' macro='1' u='r' c='_ZN15QMdiAreaPrivate23_q_deactivateAllWindowsEP13QMdiSubWindow'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='849' macro='1' u='r' c='_ZN15QMdiAreaPrivate5placeEPN4QMdi6PlacerEP13QMdiSubWindow'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='891' macro='1' u='r' c='_ZN15QMdiAreaPrivate9rearrangeEPN4QMdi10RearrangerE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1305' macro='1' u='r' c='_ZNK15QMdiAreaPrivate25setChildActivationEnabledEbb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1327' macro='1' u='r' c='_ZN15QMdiAreaPrivate22scrollBarPolicyChangedEN2Qt11OrientationENS0_15ScrollBarPolicyE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1343' macro='1' u='r' c='_ZNK15QMdiAreaPrivate13subWindowListEN8QMdiArea11WindowOrderEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1529' macro='1' u='r' c='_ZN15QMdiAreaPrivate11setViewModeEN8QMdiArea8ViewModeE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1851' macro='1' u='r' c='_ZN8QMdiArea18closeAllSubWindowsEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='1990' macro='1' u='r' c='_ZN8QMdiArea15removeSubWindowEP7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2271' macro='1' u='r' c='_ZN8QMdiArea11resizeEventEP12QResizeEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2330' macro='1' u='r' c='_ZN8QMdiArea9showEventEP10QShowEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2344' macro='1' u='r' c='_ZN8QMdiArea9showEventEP10QShowEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2481' macro='1' u='r' c='_ZN8QMdiArea5eventEP6QEvent'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmdiarea.cpp' l='2640' macro='1' u='r' c='_ZN8QMdiArea13setupViewportEP7QWidget'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qmenubar.cpp' l='1288' macro='1' u='r' c='_ZN15QMenuBarPrivate14handleReparentEv'/>
