<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='259' u='w' c='_ZN18QTranslatorPrivateC1Ev'/>
<dec f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='270' type='std::unique_ptr&lt;QResource&gt;'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='500' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='501' u='w' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='502' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='502' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='503' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='504' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='505' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='506' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='512' u='w' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='586' u='m' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='589' u='w' c='_ZN18QTranslatorPrivate7do_loadERK7QStringS2_'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='1038' u='m' c='_ZN18QTranslatorPrivate5clearEv'/>
<use f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='1042' u='w' c='_ZN18QTranslatorPrivate5clearEv'/>
<offset>1152</offset>
<doc f='qtbase-6.5.0/src/corelib/kernel/qtranslator.cpp' l='269'>// The resource object in case we loaded the translations from a resource</doc>
