<dec f='qtbase-6.5.0/src/corelib/text/qunicodetools_p.h' l='42' type='QChar::Script'/>
<offset>64</offset>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='2317' u='r' c='_ZN13QUnicodeTools8TailoredL17getCharAttributesEPKDsxPKNS_10ScriptItemExP15QCharAttributes'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='1807' u='w' c='_ZNK11QTextEngine10attributesEv'/>
<use f='qtbase-6.5.0/src/gui/text/qtextengine.cpp' l='1928' u='r' c='_ZNK11QTextEngine7itemizeEv'/>
