<def f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='552' ll='560'/>
<doc f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='546'>/* In order to implementat LB21a properly a special rule HH has been introduced and
   the following changes were made in the pair table to disallow breaks after Hebrew + Hyphen:
   (HL)(HY|BA) from IB to CI
   (HY|BA)(!CB) from DB to HH
*/</doc>
