<def f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='481' ll='486'/>
<doc f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='477'>// LB25 recommends to not break lines inside numbers of the form
// described by the following regular expression:
//  (PR|PO)?(OP|HY)?NU(NU|SY|IS)*(CL|CP)?(PR|PO)?</doc>
