<dec f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='375' type='6'/>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='391'/>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='392'/>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='393'/>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='394'/>
<use f='qtbase-6.5.0/src/corelib/text/qunicodetools.cpp' l='394'/>
