<def f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol_p.h' l='441' ll='446'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol_p.h' l='449'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol_p.h' l='450' c='_ZN18QWidgetLineControl10addCommandERKNS_7CommandE'/>
<size>16</size>
<fun r='_ZN18QWidgetLineControl7CommandC1ENS_11CommandTypeEi5QCharii'/>
<mbr r='QWidgetLineControl::Command::type' o='0' t='uint'/>
<mbr r='QWidgetLineControl::Command::uc' o='16' t='QChar'/>
<mbr r='QWidgetLineControl::Command::pos' o='32' t='int'/>
<mbr r='QWidgetLineControl::Command::selStart' o='64' t='int'/>
<mbr r='QWidgetLineControl::Command::selEnd' o='96' t='int'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='779' c='_ZN18QWidgetLineControl10addCommandERKNS_7CommandE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='784' c='_ZN18QWidgetLineControl10addCommandERKNS_7CommandE'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='816' c='_ZN18QWidgetLineControl14internalInsertERK7QString'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='826' c='_ZN18QWidgetLineControl14internalInsertERK7QString'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='827' c='_ZN18QWidgetLineControl14internalInsertERK7QString'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='846' c='_ZN18QWidgetLineControl14internalInsertERK7QString'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='870' c='_ZN18QWidgetLineControl14internalDeleteEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='871' c='_ZN18QWidgetLineControl14internalDeleteEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='879' c='_ZN18QWidgetLineControl14internalDeleteEb'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='902' c='_ZN18QWidgetLineControl18removeSelectedTextEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='907' c='_ZN18QWidgetLineControl18removeSelectedTextEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='909' c='_ZN18QWidgetLineControl18removeSelectedTextEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='912' c='_ZN18QWidgetLineControl18removeSelectedTextEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='921' c='_ZN18QWidgetLineControl18removeSelectedTextEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='1309' c='_ZN18QWidgetLineControl12internalUndoEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='1334' c='_ZN18QWidgetLineControl12internalUndoEi'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='1350' c='_ZN18QWidgetLineControl12internalRedoEv'/>
<use f='qtbase-6.5.0/src/widgets/widgets/qwidgetlinecontrol.cpp' l='1377' c='_ZN18QWidgetLineControl12internalRedoEv'/>
<size>16</size>
