<def f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='181' ll='188'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='209'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='212' c='_ZN25QXmlStreamPrivateTagStack12tagStack_popEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='213' c='_ZN25QXmlStreamPrivateTagStack12tagStack_popEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='219' c='_ZN25QXmlStreamPrivateTagStack13tagStack_pushEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream_p.h' l='220' c='_ZN25QXmlStreamPrivateTagStack13tagStack_pushEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstreamparser_p.h' l='59' c='_ZN23QXmlStreamReaderPrivate5parseEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstreamparser_p.h' l='787' c='_ZN23QXmlStreamReaderPrivate5parseEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstreamparser_p.h' l='809' c='_ZN23QXmlStreamReaderPrivate5parseEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream.cpp' l='1666' c='_ZN23QXmlStreamReaderPrivate23resolvePublicNamespacesEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream.cpp' l='3012' c='_ZN23QXmlStreamWriterPrivate18finishStartElementEb'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream.cpp' l='3537' c='_ZN16QXmlStreamWriter15writeEndElementEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream.cpp' l='3547' c='_ZN16QXmlStreamWriter15writeEndElementEv'/>
<use f='qtbase-6.5.0/src/corelib/serialization/qxmlstream.cpp' l='3758' c='_ZN23QXmlStreamWriterPrivate17writeStartElementE14QAnyStringViewS0_'/>
<size>112</size>
<mbr r='QXmlStreamPrivateTagStack::Tag::name' o='0' t='QtPrivate::XmlStringRef'/>
<mbr r='QXmlStreamPrivateTagStack::Tag::qualifiedName' o='192' t='QtPrivate::XmlStringRef'/>
<mbr r='QXmlStreamPrivateTagStack::Tag::namespaceDeclaration' o='384' t='QXmlStreamPrivateTagStack::NamespaceDeclaration'/>
<mbr r='QXmlStreamPrivateTagStack::Tag::tagStackStringStorageSize' o='768' t='qsizetype'/>
<mbr r='QXmlStreamPrivateTagStack::Tag::namespaceDeclarationsSize' o='832' t='qsizetype'/>
