<dec f='qtbase-6.5.0/qmake/generators/win32/msvc_objectmodel.h' l='886' type='VCResourceCompilerTool'/>
<offset>27392</offset>
<use f='qtbase-6.5.0/qmake/generators/win32/msbuild_objectmodel.cpp' l='497' u='r' c='_ZN16VCXProjectWriter5writeER9XmlOutputR21VCProjectSingleConfig'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msbuild_objectmodel.cpp' l='730' u='r' c='_ZN16VCXProjectWriter5writeER9XmlOutputR9VCProject'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_objectmodel.cpp' l='2927' u='r' c='_ZN15VCProjectWriter5writeER9XmlOutputRK15VCConfiguration'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_vcproj.cpp' l='1139' u='m' c='_ZN15VcprojGenerator16initResourceToolEv'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_vcproj.cpp' l='1141' u='m' c='_ZN15VcprojGenerator16initResourceToolEv'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_vcproj.cpp' l='1151' u='m' c='_ZN15VcprojGenerator16initResourceToolEv'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_vcproj.cpp' l='1158' u='m' c='_ZN15VcprojGenerator16initResourceToolEv'/>
<use f='qtbase-6.5.0/qmake/generators/win32/msvc_vcproj.cpp' l='1160' u='m' c='_ZN15VcprojGenerator16initResourceToolEv'/>
