<dec f='qtbase-6.5.0/qmake/generators/xmloutput.h' l='26' type='1'/>
<doc f='qtbase-6.5.0/qmake/generators/xmloutput.h' l='26'>// &lt;tagname attribute1=&quot;value&quot;</doc>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='230' c='_ZN9XmlOutput9closeOpenEv'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='236' u='r' c='_ZN9XmlOutput9closeOpenEv'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='250' c='_ZN9XmlOutput8closeTagEv'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='260' u='r' c='_ZN9XmlOutput8closeTagEv'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='293' c='_ZN9XmlOutput14addDeclarationERK7QStringS2_'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='315' c='_ZN9XmlOutput12addAttributeERK7QStringS2_'/>
<use f='qtbase-6.5.0/qmake/generators/xmloutput.cpp' l='333' c='_ZN9XmlOutput15addAttributeTagERK7QStringS2_'/>
